if (janrain.settings.capture.appId === "nx74vh7dvvvk7vx6479bxema3a" || janrain.settings.capture.appId === "hd3df5j8g2wkww87mt6gzhrbu9") janrain.settings.capture.accessTokenLifeHours = 3;
if(janrain&&janrain.settings&&janrain.settings.capture){var parseUri=function(d){for(var a=parseUri.options,d=a.parser[a.strictMode?"strict":"loose"].exec(d),c={},b=14;b--;)c[a.key[b]]=d[b]||"";c[a.q.name]={};c[a.key[12]].replace(a.q.parser,function(d,b,e){b&&(c[a.q.name][b]=e)});return c};parseUri.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};janrain.channel4urihash=parseUri(window.location);janrain.channel4urihash.port="https"===janrain.channel4urihash.protocol?":443":"";"/reset-password"===janrain.channel4urihash.path&&(janrain.settings.capture.redirectUri=janrain.channel4urihash.protocol+"://"+janrain.channel4urihash.host+janrain.channel4urihash.port+
"/reset-password")};
janrain&&janrain.settings&&janrain.settings.capture&&janrain.settings.capture.appId&&("nx74vh7dvvvk7vx6479bxema3a"===janrain.settings.capture.appId||"qfm5yezrh9388mj3d5kbcw7egh"===janrain.settings.capture.appId||"kjd4j3bbmh4uth2qjjqb9creyk"===janrain.settings.capture.appId)?function(){function f(c,b){function k(a){h=!0;"undefined"!==typeof i&&clearTimeout(i);if("string"===typeof a)return"function"===typeof g&&g(a),!0;if("object"===typeof a||"undefined"===typeof a)return"object"===typeof a&&"error"===
a.type?"function"===typeof g&&g(a):"function"===typeof j&&j(),!0}function e(){l++;if(h)return!0;l<f?i=setTimeout(e,50):k("Load Timeout Error")}var j=b,f=200,m=!1,g,l=0,i,d=document.createElement("script"),n=document.getElementsByTagName("script")[0],h=!1;d.src=c;d.setAttribute("type","text/javascript");d.onload=d.onerror=d.onreadystatechange=function(a){!h&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)&&k(a)};return{setTimeoutCallback:function(a){m=!0;g=a;return this},
setCallback:function(a){j=a;return this},setTimeoutLimit:function(a){f=a;return this},load:function(){n.parentNode.insertBefore(d,n);m&&e()}}}function e(c,b){if(c===b.length){var k=("https:"===document.location.protocol?"https://d16s8pqtk4uodx.cloudfront.net/":"http://d16s8pqtk4uodx.cloudfront.net/")+"manifest-prod/"+b.join("-")+".js";f(k,void 0).load()}else"login"===b[c]&&"en"===janrain.settings.language||"capture"===b[c]||"simpleshare"===b[c]?e(c+1,b):f(("https:"===document.location.protocol?"https://d29usylhdk1xyu.cloudfront.net/":
"http://widget-cdn.rpxnow.com/")+"translations/"+b[c]+"/"+janrain.settings.language,function(){e(c+1,b)}).load()}"object"!==typeof window.janrain.engage&&(window.janrain.engage={});janrain.settings.capture||(janrain.settings.capture={});janrain.settings.common||(janrain.settings.common={});janrain.settings.language||(janrain.settings.language="en");janrain.settings.packages||(janrain.settings.packages=["login"]);janrain.settings.publish||(janrain.settings.publish={});janrain.settings.share||(janrain.settings.share=
{});janrain.settings.simpleshare||(janrain.settings.simpleshare={});janrain.settings.linkClass||(janrain.settings.linkClass="janrainEngage");"undefined"===typeof janrain.settings.common.appUrl&&(janrain.settings.common.appUrl="https://channel4-test.rpxnow.com");"undefined"===typeof janrain.settings.showAttribution&&(janrain.settings.showAttribution=!0);"undefined"===typeof janrain.settings.type&&(janrain.settings.type="embed");"undefined"===typeof janrain.settings.format&&(janrain.settings.format=
"two column");"undefined"===typeof janrain.settings.width&&(janrain.settings.width="380");"undefined"===typeof janrain.settings.providersPerPage&&(janrain.settings.providersPerPage="6");"undefined"===typeof janrain.settings.actionText&&(janrain.settings.actionText="");"undefined"===typeof janrain.settings.fontColor&&(janrain.settings.fontColor="#333333");"undefined"===typeof janrain.settings.fontFamily&&(janrain.settings.fontFamily="arial");"undefined"===typeof janrain.settings.backgroundColor&&(janrain.settings.backgroundColor=
"#FFFFFF");"undefined"===typeof janrain.settings.buttonBorderColor&&(janrain.settings.buttonBorderColor="#CCCCCC");"undefined"===typeof janrain.settings.buttonBorderRadius&&(janrain.settings.buttonBorderRadius="10");"undefined"===typeof janrain.settings.buttonBackgroundStyle&&(janrain.settings.buttonBackgroundStyle="gradient");"undefined"===typeof janrain.settings.borderWidth&&(janrain.settings.borderWidth="15");"undefined"===typeof janrain.settings.borderColor&&(janrain.settings.borderColor="#CCCCCC");
"undefined"===typeof janrain.settings.borderRadius&&(janrain.settings.borderRadius="10");"undefined"===typeof janrain.settings.appId&&(janrain.settings.appId="mmiploemobkpcmcnahod");"undefined"===typeof janrain.settings.appUrl&&(janrain.settings.appUrl="https://channel4-test.rpxnow.com");janrain.settings.permissions=["customizable_auth_widget_hide_attribution","customizable_auth_widget_styling"];"undefined"===typeof janrain.settings.providers&&(janrain.settings.providers=["aol","facebook","google",
"yahoo","openid"]);"undefined"===typeof janrain.settings.noReturnExperience&&(janrain.settings.noReturnExperience=!1);"undefined"===typeof janrain.settings.share.attributionDisplay&&(janrain.settings.share.attributionDisplay=!0);"undefined"===typeof janrain.settings.share.elementColor&&(janrain.settings.share.elementColor="#cccccc");"undefined"===typeof janrain.settings.share.elementHoverBackgroundColor&&(janrain.settings.share.elementHoverBackgroundColor="#eeeeee");"undefined"===typeof janrain.settings.share.elementButtonBorderRadius&&
(janrain.settings.share.elementButtonBorderRadius="6");"undefined"===typeof janrain.settings.share.elementBorderColor&&(janrain.settings.share.elementBorderColor="#cccccc");"undefined"===typeof janrain.settings.share.elementBackgroundColor&&(janrain.settings.share.elementBackgroundColor="#f6f6f6");"undefined"===typeof janrain.settings.share.elementLinkColor&&(janrain.settings.share.elementLinkColor="#d7e0e3");"undefined"===typeof janrain.settings.share.elementBorderRadius&&(janrain.settings.share.elementBorderRadius=
"4");"undefined"===typeof janrain.settings.share.elementButtonBoxShadow&&(janrain.settings.share.elementButtonBoxShadow="2");"undefined"===typeof janrain.settings.share.modalOpacity&&(janrain.settings.share.modalOpacity="0.5");"undefined"===typeof janrain.settings.share.modalBorderRadius&&(janrain.settings.share.modalBorderRadius="5");"undefined"===typeof janrain.settings.share.bodyColor&&(janrain.settings.share.bodyColor="#333333");"undefined"===typeof janrain.settings.share.bodyTabBackgroundColor&&
(janrain.settings.share.bodyTabBackgroundColor="#f8f8f8");"undefined"===typeof janrain.settings.share.bodyTabColor&&(janrain.settings.share.bodyTabColor="#000000");"undefined"===typeof janrain.settings.share.bodyContentBackgroundColor&&(janrain.settings.share.bodyContentBackgroundColor="#ffffff");"undefined"===typeof janrain.settings.share.bodyBackgroundColorOverride&&(janrain.settings.share.bodyBackgroundColorOverride=!1);"undefined"===typeof janrain.settings.share.bodyFontFamily&&(janrain.settings.share.bodyFontFamily=
"Helvetica");"undefined"===typeof janrain.settings.share.bodyBackgroundColor&&(janrain.settings.share.bodyBackgroundColor="#009DDC");"undefined"===typeof janrain.settings.share.modalBackgroundColor&&(janrain.settings.share.modalBackgroundColor="#000000");"undefined"===typeof janrain.settings.share.appUrl&&(janrain.settings.share.appUrl="https://channel4-test.rpxnow.com");janrain.settings.share.permissions=["customizable_share_widget_hide_attribution","customizable_share_widget_styling","customizable_share_widget_contact_mode"];
"undefined"===typeof janrain.settings.share.providers&&(janrain.settings.share.providers=["email","twitter","facebook"]);"undefined"===typeof janrain.settings.share.providersEmail&&(janrain.settings.share.providersEmail=[]);"undefined"===typeof janrain.settings.share.modes&&(janrain.settings.share.modes=["broadcast","contact"]);janrain.settings.packages.sort();e(0,janrain.settings.packages)}():function(){function f(c,b){function e(a){h=!0;"undefined"!==typeof i&&clearTimeout(i);if("string"===typeof a)return"function"===
typeof g&&g(a),!0;if("object"===typeof a||"undefined"===typeof a)return"object"===typeof a&&"error"===a.type?"function"===typeof g&&g(a):"function"===typeof j&&j(),!0}function f(){l++;if(h)return!0;l<o?i=setTimeout(f,50):e("Load Timeout Error")}var j=b,o=200,m=!1,g,l=0,i,d=document.createElement("script"),n=document.getElementsByTagName("script")[0],h=!1;d.src=c;d.setAttribute("type","text/javascript");d.onload=d.onerror=d.onreadystatechange=function(a){!h&&(!this.readyState||"loaded"===this.readyState||
"complete"===this.readyState)&&e(a)};return{setTimeoutCallback:function(a){m=!0;g=a;return this},setCallback:function(a){j=a;return this},setTimeoutLimit:function(a){o=a;return this},load:function(){n.parentNode.insertBefore(d,n);m&&f()}}}function e(c,b){if(c===b.length){var k=("https:"===document.location.protocol?"https://d16s8pqtk4uodx.cloudfront.net/":"http://d16s8pqtk4uodx.cloudfront.net/")+"manifest-prod/"+b.join("-")+".js";f(k,void 0).load()}else"login"===b[c]&&"en"===janrain.settings.language||
"capture"===b[c]||"simpleshare"===b[c]?e(c+1,b):f(("https:"===document.location.protocol?"https://d29usylhdk1xyu.cloudfront.net/":"http://widget-cdn.rpxnow.com/")+"translations/"+b[c]+"/"+janrain.settings.language,function(){e(c+1,b)}).load()}"object"!==typeof window.janrain.engage&&(window.janrain.engage={});janrain.settings.capture||(janrain.settings.capture={});janrain.settings.common||(janrain.settings.common={});janrain.settings.language||(janrain.settings.language="en");janrain.settings.packages||
(janrain.settings.packages=["login"]);janrain.settings.publish||(janrain.settings.publish={});janrain.settings.share||(janrain.settings.share={});janrain.settings.simpleshare||(janrain.settings.simpleshare={});janrain.settings.linkClass||(janrain.settings.linkClass="janrainEngage");"undefined"===typeof janrain.settings.common.appUrl&&(janrain.settings.common.appUrl="https://signin.channel4.com");"undefined"===typeof janrain.settings.showAttribution&&(janrain.settings.showAttribution=!0);"undefined"===
typeof janrain.settings.type&&(janrain.settings.type="embed");"undefined"===typeof janrain.settings.format&&(janrain.settings.format="two column");"undefined"===typeof janrain.settings.width&&(janrain.settings.width="380");"undefined"===typeof janrain.settings.providersPerPage&&(janrain.settings.providersPerPage="6");"undefined"===typeof janrain.settings.actionText&&(janrain.settings.actionText="");"undefined"===typeof janrain.settings.fontColor&&(janrain.settings.fontColor="#333333");"undefined"===
typeof janrain.settings.fontFamily&&(janrain.settings.fontFamily="arial");"undefined"===typeof janrain.settings.backgroundColor&&(janrain.settings.backgroundColor="#FFFFFF");"undefined"===typeof janrain.settings.buttonBorderColor&&(janrain.settings.buttonBorderColor="#CCCCCC");"undefined"===typeof janrain.settings.buttonBorderRadius&&(janrain.settings.buttonBorderRadius="10");"undefined"===typeof janrain.settings.buttonBackgroundStyle&&(janrain.settings.buttonBackgroundStyle="gradient");"undefined"===
typeof janrain.settings.borderWidth&&(janrain.settings.borderWidth="15");"undefined"===typeof janrain.settings.borderColor&&(janrain.settings.borderColor="#CCCCCC");"undefined"===typeof janrain.settings.borderRadius&&(janrain.settings.borderRadius="10");"undefined"===typeof janrain.settings.appId&&(janrain.settings.appId="gjnmlipneflcfmmelgec");"undefined"===typeof janrain.settings.appUrl&&(janrain.settings.appUrl="https://signin.channel4.com");janrain.settings.permissions=["customizable_auth_widget_hide_attribution",
"customizable_auth_widget_styling"];"undefined"===typeof janrain.settings.providers&&(janrain.settings.providers=["aol","google","yahoo","openid"]);"undefined"===typeof janrain.settings.noReturnExperience&&(janrain.settings.noReturnExperience=!1);"undefined"===typeof janrain.settings.share.attributionDisplay&&(janrain.settings.share.attributionDisplay=!0);"undefined"===typeof janrain.settings.share.elementColor&&(janrain.settings.share.elementColor="#333333");"undefined"===typeof janrain.settings.share.elementHoverBackgroundColor&&
(janrain.settings.share.elementHoverBackgroundColor="#eeeeee");"undefined"===typeof janrain.settings.share.elementButtonBorderRadius&&(janrain.settings.share.elementButtonBorderRadius="6");"undefined"===typeof janrain.settings.share.elementBorderColor&&(janrain.settings.share.elementBorderColor="#cccccc");"undefined"===typeof janrain.settings.share.elementBackgroundColor&&(janrain.settings.share.elementBackgroundColor="#f6f6f6");"undefined"===typeof janrain.settings.share.elementLinkColor&&(janrain.settings.share.elementLinkColor=
"#009DDC");"undefined"===typeof janrain.settings.share.elementBorderRadius&&(janrain.settings.share.elementBorderRadius="3");"undefined"===typeof janrain.settings.share.elementButtonBoxShadow&&(janrain.settings.share.elementButtonBoxShadow="3");"undefined"===typeof janrain.settings.share.modalOpacity&&(janrain.settings.share.modalOpacity="0.5");"undefined"===typeof janrain.settings.share.modalBorderRadius&&(janrain.settings.share.modalBorderRadius="5");"undefined"===typeof janrain.settings.share.bodyColor&&
(janrain.settings.share.bodyColor="#333333");"undefined"===typeof janrain.settings.share.bodyTabBackgroundColor&&(janrain.settings.share.bodyTabBackgroundColor="#f8f8f8");"undefined"===typeof janrain.settings.share.bodyTabColor&&(janrain.settings.share.bodyTabColor="#000000");"undefined"===typeof janrain.settings.share.bodyContentBackgroundColor&&(janrain.settings.share.bodyContentBackgroundColor="#ffffff");"undefined"===typeof janrain.settings.share.bodyBackgroundColorOverride&&(janrain.settings.share.bodyBackgroundColorOverride=
!1);"undefined"===typeof janrain.settings.share.bodyFontFamily&&(janrain.settings.share.bodyFontFamily="Helvetica");"undefined"===typeof janrain.settings.share.bodyBackgroundColor&&(janrain.settings.share.bodyBackgroundColor="#009DDC");"undefined"===typeof janrain.settings.share.modalBackgroundColor&&(janrain.settings.share.modalBackgroundColor="#000000");"undefined"===typeof janrain.settings.share.appUrl&&(janrain.settings.share.appUrl="https://signin.channel4.com");janrain.settings.share.permissions=
["customizable_share_widget_hide_attribution","customizable_share_widget_styling","customizable_share_widget_contact_mode"];"undefined"===typeof janrain.settings.share.providers&&(janrain.settings.share.providers=[]);"undefined"===typeof janrain.settings.share.providersEmail&&(janrain.settings.share.providersEmail=[]);"undefined"===typeof janrain.settings.share.modes&&(janrain.settings.share.modes=["broadcast"]);janrain.settings.packages.sort();e(0,janrain.settings.packages)}();
