/*
 -*- Engage Auth Widget -*-
 Copyright (c) 2012, Janrain, Inc. All rights reserved.
 Version: 2012.42_ws
*/
"object"!==typeof window.janrain&&(window.janrain={});janrain.apps={};
janrain.apps=function(){var Aa,Ba,qa,ra;function xb(){return"http:"===document.location.protocol?"http://cdn.quilt.janrain.com/2.1.2/":"https://d3hmp0045zy3cs.cloudfront.net/2.1.2/"}function Hb(a,d,c){var b;if(document.getElementById(a))return!1;if(f){b="";var E=document.createElement("div");E.innerHTML=b+"<iframe "+('name="'+a+'" ')+('id="'+a+'" ')+('src="'+d+'" ')+'style="display: none;"></iframe>';document.body&&document.body.appendChild(E)}else b=document.createElement("iframe"),b.setAttribute("name",
a),b.id=a,b.setAttribute("src",d),b.style.display="none",b.className="",document.body&&document.body.appendChild(b);"function"===typeof c&&c()}function Ca(a){for(var d="",d="",c=0;c<a;c++)d+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));return d}function Z(){function a(a,b,c,d){b={action:a,key:b,messageId:c};"set"===a&&(b.value=d);return"janrainCapture:"+I.stringify(b)}function d(a,b){function c(){d++;if(10<d)return!1;if("undefined"!==typeof e[a])return clearTimeout(g),
"get"===e[a].action&&"function"===typeof b&&b(e[a].storedValue),!0;var g=setTimeout(c,50)}var d=0;c()}function c(b,c){var g=Ca(40);window.setTimeout(function(){h.contentWindow.postMessage(a("get",b,g),Da)});d(g,c)}function b(a,d){if(g)Wa?c(a,d):setTimeout(function(){b(a,d)},50);else return window.localStorage.getItem(a)}function E(a){var b;if(!(b=0!==a.data.indexOf("janrainCapture:"))){b=A;var c=a.origin.replace(/^https?:\/\/|:\d{1,4}$/g,"").toLowerCase();b=!(!fa(b)?0:-1<b.indexOf(c))}if(b)return!1;
a=I.parse(a.data.replace("janrainCapture:",""));e[a.messageId]=a}var g=!1,e={},h,Da,A=janrain.settings&&janrain.settings.whiteListedDomains?janrain.settings.whiteListedDomains:[];return{setItem:function(b,c){if(g){var E=Ca(40);window.setTimeout(function(){h.contentWindow.postMessage(a("set",b,E,c),Da)});return d(E)}return window.localStorage.setItem(b,c)},removeItem:function(b){if(g){var c=Ca(40);window.setTimeout(function(){h.contentWindow.postMessage(a("remove",b,c),Da)});return d(c)}return window.localStorage.removeItem(b)},
getItem:b,setMultiDomain:function(b){if(g=b)window.addEventListener?window.addEventListener("message",E,!1):window.attachEvent?window.attachEvent("onmessage",E):document.attachEvent&&document.attachEvent("onmessage",E),h=document.getElementById("xDomainLocalStorageJanrain"),Da=janrain.settings.storageServerDomain}}}function T(){function a(){if(E&&U){var a=new Z;a.setMultiDomain(janrain.settings.multiDomainLocalStorage);a.removeItem(b);a.removeItem(b+"_Expires")}else{var a=e?"; domain="+e:"",c=new Date;
c.setTime(c.getTime()+-864E6);document.cookie=b+"="+g+";expires="+c.toUTCString()+a+"; path="+h}}function d(c,d){var g,e,q,h,f;if(E&&U)if(f=new Z,janrain.settings.multiDomainLocalStorage)f.setMultiDomain(!0),f.getItem(c,function(g){g?f.getItem(c+"_Expires",function(j){j?Math.round((new Date).getTime()/1E3)>Math.round((new Date(j)).getTime()/1E3)?(b=c,a(),"function"===typeof d&&d(!1)):"function"===typeof d&&d(g):(new T).getCookie(c+"_session")?"function"===typeof d&&d(g):(b=c,a())}):"function"===typeof d&&
d(!1)});else if(h=f.getItem(c),g=f.getItem(c+"_Expires"),h){if(!(g&&Math.round((new Date).getTime()/1E3)>Math.round((new Date(g)).getTime()/1E3))&&(g||(new T).getCookie(c+"_session")))return h;b=c;a()}else return!1;else{g=document.cookie.split(";");e=g.length;for(var V=0;V<e;V++)if(q=g.pop(),h=q.split("="),q=h[0],h=h[1],q.trim()===c)return h;return!1}}var c,b,E=!1,g,e,h="/";return{create:function(){if(E&&U){var a=new Z;a.setMultiDomain(janrain.settings.multiDomainLocalStorage);a.setItem(b,g);c?a.setItem(b+
"_Expires",c):(new T).setName(b+"_session").setValue("session").create()}else document.cookie=b+"="+g+(c?"; expires="+c:"")+(e?"; domain="+e:"")+"; path="+h},remove:a,setExpirationDirectly:function(a){a&&(c=a);return this},setExpiration:function(a){if(a){var b=new Date;b.setTime(b.getTime()+864E5*a);c=b.toUTCString()}return this},setName:function(a){a&&(b=a);return this},setValue:function(a){"undefined"!==typeof a&&(g=a);return this},setUseLocalStorage:function(a){E=a;return this},setPath:function(a){a&&
(h=a);return this},setDomain:function(a){a&&(e=a);return this},getCookie:function(a,b){return d(a,b)}}}function Za(){return"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(P)?parseFloat(RegExp.$1):!1}function Ia(){return!/Chrome\//.test(P)&&/Safari\//.test(P)}function F(a,d,c,b,e,g){"number"===typeof c&&"number"===typeof b&&"number"===typeof e&&"number"===typeof g?("undefined"!==typeof a.style.borderRadius&&(a.style.borderRadius=c+"px "+b+"px "+e+"px "+g+"px"),
"undefined"!==typeof a.style.MozBorderRadius&&(a.style.MozBorderRadius=c+"px "+b+"px "+e+"px "+g+"px"),"undefined"!==typeof a.style.webkitBorderRadius&&(a.style.webkitBorderRadius=c+"px "+b+"px "+e+"px "+g+"px")):("undefined"!==typeof a.style.borderRadius&&(a.style.borderRadius=d+"px"),"undefined"!==typeof a.style.MozBorderRadius&&(a.style.MozBorderRadius=d+"px"),"undefined"!==typeof a.style.webkitBorderRadius&&(a.style.webkitBorderRadius=d+"px"));return a}function Qa(a,d){if("undefined"===typeof a||
"undefined"===typeof d)return!1;var c=a-d;0>c&&(c=0);c>a&&(c=a);return c}function yb(a,d){if(f&&9>=f)return a.style.backgroundImage="url('"+ob("rel/img/c7a91677d94f4a79e1b26c8ceb31af82.png")+"')",!0;var c;if(c=Ia()){a:{if(P&&(c=P.match(/(\d)[\d.]+ Safari/))&&c[1]){c=1*c[1];break a}c=0}c=4>=c}if(c||$.getMobileDevice()){var b=c="",e="",g=d.split(","),q={top:"left top, left bottom",right:"right top, right bottom",bottom:"left bottom, left top",left:"left top, left bottom"};g[0]&&q[g[0]]&&(c=q[g[0]]);
g[1]&&(b="from("+g[1]+")");g[g.length-1]&&(e="to("+g[g.length-1]+")");a.style.backgroundImage="-webkit-gradient(linear,"+c+","+b+","+e+")"}a.style.backgroundImage="-moz-linear-gradient("+d+")";a.style.backgroundImage="-webkit-linear-gradient("+d+")";a.style.backgroundImage="-ms-linear-gradient("+d+")";a.style.backgroundImage="-o-linear-gradient("+d+")";a.style.backgroundImage="linear-gradient("+d+")"}function aa(a,d,c,b){var e=Ea(c),g=Ea(c,b);if(c=Jb(c))c.a=b,g="rgba("+c.r+", "+c.g+", "+c.b+", "+
c.a+")";if(0<d){a.style.backgroundColor=e;a.style.padding=d+"px";if(0<f&&8>=f||f&&t)return!1;a.style.backgroundColor=g;a.style.padding=d+"px"}else a.style.backgroundColor="",a.style.padding="0px"}function Jb(a){var d={};if("string"!==typeof a||!a)return!1;a=a.replace(/\s+/g,"");a=a.replace(/,{2,}/g,",");a=a.replace(/[^\d.,]/g,"");a=a.split(",");if(3>a.length||4<a.length)return!1;d.r=a[0];d.g=a[1];d.b=a[2];d.a=a[3]?a[3]:1;return d}function Ea(a,d){var c=a.split("");if("#"!==c[0])return a;4===a.length&&
(a=c[0]+c[1]+c[1]+c[2]+c[2]+c[3]+c[3]);var a=a.substring(1,7),c=parseInt(a.substring(0,2),16),b=parseInt(a.substring(2,4),16),e=parseInt(a.substring(4,6),16);return isNaN(d)?"rgb("+c+","+b+","+e+")":"rgba("+c+","+b+","+e+","+d+")"}function W(a,d,c){if(null==a)return!1;"object"===typeof window.attachEvent?a.attachEvent("on"+d,c):a.addEventListener(d,c,!1)}function zb(a,d,c){"object"===typeof window.detachEvent?a.detachEvent("on"+d,c):a.removeEventListener(d,c,!1)}function Ab(){var a,d,c,b,e,g,q,h;
d=document.documentElement?document.documentElement:{clientWidth:0,clientHeight:0,scrollWidth:0,scrollHeight:0,offsetWidth:0,offsetHeight:0};q=d.scrollWidth?d.scrollWidth:0;h=d.scrollHeight?d.scrollHeight:0;e=d.offsetWidth?d.offsetWidth:0;g=d.offsetHeight?d.offsetHeight:0;c=document.body.scrollWidth?document.body.scrollWidth:0;b=document.body.scrollHeight?document.body.scrollHeight:0;a=document.body.offsetWidth?document.body.offsetWidth:0;d=document.body.offsetHeight?document.body.offsetHeight:0;
e=Math.max(c,q,a,e);return{height:Math.max(b,h,d,g),width:e}}function r(a,d,c,b,e){var g=/^(?:[^\u0000-\u0080]|[-0-9a-z?,.!&\s#()])+$/i,q=/(?:^rgb\s*\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*\)$)|(?:^#[a-f0-9]{1,6}$)/i;if("array"===a){if(!fa(b))return e||o.log(b+" is wrong type, must be array, using default value instead"),c;if(d&&fa(d))for(var h=0;h<b.length;h++)if(0>d.indexOf(b[h]))return e||o.log(b+" is not within the valid range, using default value instead"),c;return b}if("url"===a){if("string"!==typeof b)return c;
b&&(b=b.trim());if(/^http(?:s)?:\/\/[-a-z0-9._~@:!$&'()*+,;=\s/?#]+$/i.test(b))return b;e||o.log(b+" is not the valid format, using default value instead");return c}if("text"===a){if(d){if(0<=d.indexOf(b))return b;e||o.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+c+'" instead');return c}return g.test(b)?b:c}if("usertext"===a){if("string"!==typeof b&&"number"!==typeof b)return c;if(fa(d)){if(1===d.length){if(b.length<=d[0])return b;e||o.log(b+
" is too long, using default value instead");return c}if(2===d.length){if(b.length<=d[1]&&b.length>=d[0])return b;e||o.log(b+" is not within the valid range, using default value instead");return c}e||o.log("usertext range is invalid, using default value instead");return c}return b}"string"===typeof b&&0==b.length&&(b=" ");if(!g.test(b))return e||o.log(b+" contains invalid character(s)"),c;if("boolean"===a){if("boolean"===typeof b)return b;e||o.log(b+" is wrong type, must be boolean, using default value instead");
return c}if("text"===a)return b;if("number"===a){if(isNaN(parseInt(b)))return e||o.log(b+" is wrong type, must be a valid number"),c;b=parseFloat(b)}if("color"===a){b&&(b=b.trim());if("transparent"===b||q.test(b))return b;e||o.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+c+'" instead');return c}if(typeof b!=a&&"color"!=a)return e||o.log(b+" for "+arguments.callee.caller.name+" is "+typeof b+" expected "+a),c;if("object"===typeof d&&"string"===
a){if(0<=d.indexOf(b))return b;e||o.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+c+'" instead');return c}if("object"===typeof d&&"number"===a){2===d.length?(g=d[0],q=d[1]):(g=d.shift(),q=d.pop(),h=d);if(b<g)return e||o.log("Value of "+b+" for "+arguments.callee.caller.name+" is below minimum of "+g+", using minimum value of "+g+" instead"),g;if(b>q)return e||o.log("Value of "+b+" for "+arguments.callee.caller.name+" is above maximum of "+
q+", using maximum value of "+q+" instead"),q;if(h&&"number"===typeof h.indexOf(b)||b==g||b==q)return b;return h?(e||o.log("Value of "+b+" for "+arguments.callee.caller.name+" is not a valid value, using default value of "+c+" instead"),c):b}return 0!=b&&!b?c:b}function pb(a){for(var d=pb.options,a=d.parser[d.strictMode?"strict":"loose"].exec(a),c={},b=14;b--;)c[d.key[b]]=a[b]||"";c[d.q.name]={};c[d.key[12]].replace(d.q.parser,function(a,b,e){b&&(c[d.q.name][b]=e)});return c}function Kb(a,d){function c(a){o=
!0;"undefined"!==typeof A&&clearTimeout(A);if("string"===typeof a)return"function"===typeof h&&h(a),!0;if("object"===typeof a||"undefined"===typeof a)return"object"===typeof a&&"error"===a.type?"function"===typeof h&&h(a):"function"===typeof e&&e(),!0}function b(){f++;if(o)return!0;f<g?A=setTimeout(b,50):c("Load Timeout Error")}var e=d,g=200,q=!1,h,f=0,A,K=document.createElement("script"),L=document.getElementsByTagName("script")[0],o=!1;K.src=a;K.setAttribute("type","text/javascript");K.onload=K.onerror=
K.onreadystatechange=function(a){!o&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)&&c(a)};return{setTimeoutCallback:function(a){q=!0;h=a;return this},setCallback:function(a){e=a;return this},setTimeoutLimit:function(a){g=a;return this},load:function(){L.parentNode.insertBefore(K,L);q&&b()}}}function ga(a,d){Kb(a,d).load()}function Bb(a,d){function c(b){h=!1;"function"===typeof d&&d();janrain.events.onCssLoad.fire({source:a,noload:b})}function b(){if(h){for(A=f.length;0<=
--A;)if(f[A].href===g.href){c();break}q+=1;h&&(200>q?setTimeout(b,50):c(!0))}}function e(){var a;try{a=!!g.sheet.cssRules}catch(b){q+=1;200>q?setTimeout(e,50):a&&c(!0);return}c()}var g,q=0,h=!0,f=document.styleSheets,A;"undefined"===typeof janrain.events.onCssLoad&&(janrain.events.onCssLoad=new ta);X?(g=document.createElement("style"),g.innerHTML='@import "'+a+'";'):(g=document.createElement("link"),g.rel="stylesheet",g.href=a,g.type="text/css");Cb||X?(Cb&&b(),X&&e()):(g.onload=function(){c()},g.onerror=
function(){c(!0)});document.getElementsByTagName("head")[0].appendChild(g)}function fa(a){return"[object Array]"===Object.prototype.toString.call(a)}function qb(a){var d="",c;for(c in a)d+="&"+encodeURIComponent(c)+"="+encodeURIComponent(a[c]);return d="?"+d.substr(1)}function ha(a){if(!a)return!1;if(a.preventDefault)a.preventDefault();else try{a.returnValue=!1}catch(d){}}function ua(a){if(!a)return!1;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function Db(){function a(a){var a=a||"img",
c=document.createElement(a);c.style.position="absolute";c.style.cursor="pointer";c.style.zIndex=1E3;"a"===a?(c.setAttribute("href","#"),c.className="janrain_modal_closebutton",ba&&(c.innerHTML=ba)):(c.src=N,T||(c.style.right="-6px",c.style.top="-7px",c.style.height="31px",c.style.width="28px"));c.onclick=I?b:d;return c}function d(a){Y||(j.style.display="none",ia.style.display="none",y.style.display="none");R&&$.deactivate();("object"===typeof a||!a)&&janrain.events.onModalClose.fire();("object"===
typeof a||!a)&&ca.fire();"object"===typeof a&&ha(a)}function c(){var a=document.createElement("div"),b=document.createElement("div"),c=document.createElement("a"),e=document.createElement("a"),g=document.createElement("h3");c.innerHTML=Ja;e.innerHTML=va;g.innerHTML=P;c.setAttribute("href","#");e.setAttribute("href","#");a.className="janrain_close_confirm_container";b.className="janrain_close_confirm";c.className="janrain_modal_confirm";e.className="janrain_modal_cancel";W(c,"click",function(a){d();
j.removeChild(S);S=null;ha(a)});W(e,"click",function(a){j.removeChild(S);S=null;ha(a)});b.appendChild(g);b.appendChild(e);b.appendChild(c);a.appendChild(b);return a}function b(a){S||(S=c(),j.appendChild(S));ha(a)}function e(a){var b=document.documentElement.scrollTop>=document.body.scrollTop?document.documentElement.scrollTop:document.body.scrollTop,c=a.style&&a.style.width?parseInt(a.style.width):a.offsetWidth?parseInt(a.offsetWidth):0,d=a.style&&a.style.height?parseInt(a.style.height):a.offsetHeight?
parseInt(a.offsetHeight):0;a.style.left="50%";a.style.marginLeft=-1*c/2+"px";a.style.marginTop=-1*d/2+b+"px";a.style.top="50%";0>a.offsetLeft&&(a.style.left=0,a.style.marginLeft=0);0>a.offsetTop&&(a.style.marginTop=0,a.style.top="10px");"absolute"!==a.style.position&&(a.style.position="absolute")}function g(){if(Y){var a=document.getElementById("previewMode");a.style.position="relative";a.appendChild(j)}else e(j);Y||o.show()}function q(a){da||(G=r("number",[0,20],10,a),wa.fire({radius:Qa(Q,G)}))}
function h(a){da||(u=r("color",null,"#000000",a))}function Da(a){da||(Q=r("number",[0,20],10,a),xa.fire({radius:Qa(Q,G),refresh:!0}))}function A(a){da||(ja=r("number",[0,1],0.5,a),"object"==typeof j&&aa(j,G,u,ja))}function K(a){if("portrait"===a){ea="portrait";var b="one column"}"landscape"===a&&(ea="landscape",b="two column");k.fire({orientation:ea,format:b,width:V,height:Pa});setTimeout(Oa,100);g()}function L(a){a&&(ya=a);f&&t&&(ya+=G-2);"object"==typeof j&&(j.style.width=ya+"px");return this}function Ib(a){a&&
(za=a);f&&t&&(za=za+2*G-4);a&&"object"==typeof j&&(j.style.height=za+"px");return this}function sa(){qa>=ra&&"undefined"===typeof window.orientation?"landscape"!==ea&&K("landscape"):90===window.orientation||-90===window.orientation?"landscape"!==ea&&K("landscape"):"portrait"!==ea&&K("portrait");g()}function Oa(){var a=Ab();y.style.height=a.height+"px";y.style.width=a.width+"px"}var V=380,Pa=131,j,Eb="janrainModal",ia,y,M,ya=V,za=Pa,G=10,u="#000000",Q=10,ja=0.5,I=!1,N=ob("rel/img/b573cd6e318034fa17bb7e9690552ca1.png"),
ba="",da=janrain.settings&&janrain.settings.capture&&janrain.settings.capture.noModalBorderInlineCss,T=!1,P="Are you sure you want to quit?",Ja="Yes, quit",va="No, stay",S,ea="landscape",B=!0,R="boolean"===typeof R?R:"number"===typeof window.orientation?!0:!1,ka="boolean"===typeof ka?ka:janrain.settings.previewMode,Y=ka,Sa=Sa||!1;janrain.settings&&janrain.settings.capture&&janrain.settings.capture.modalCloseImage&&(N=janrain.settings.capture.modalCloseImage,T=!0);janrain.settings&&janrain.settings.capture&&
janrain.settings.capture.modalCloseHtml&&(ba=janrain.settings.capture.modalCloseHtml);window.janrain.events.onModalClose||(window.janrain.events.onModalClose=D());window.janrain.events.onModalOpen||(window.janrain.events.onModalOpen=D());var ca=D(),la=D(),xa=D(),wa=D(),k=D();$&&$.onOrientationChange&&$.onViewportChange&&($.onOrientationChange.addHandler(function(a){K(a.orientation)}),$.onViewportChange.addHandler(function(){e(j)}));return{isOpen:function(){return"object"===typeof j&&"none"!==j.style.display},
setWidth:function(a){L(a);return this},setHeight:function(a){Ib(a);return this},setBorder:function(a){("string"==typeof a||"number"==typeof a)&&q(a);da||"object"==typeof j&&aa(j,G,u,ja);return this},setBorderColor:function(a){a&&h(a);da||"object"==typeof j&&aa(j,G,u,ja);return this},setBorderRadius:function(a){("string"==typeof a||"number"==typeof a)&&Da(a);da||"object"==typeof j&&F(j,Q);return this},setBorderOpacity:function(a){("number"===typeof a||"string"===typeof a)&&A(a);return this},setZIndex:function(a){y.style.zIndex=
a},setPreviewMode:function(a){"boolean"===typeof a&&(Y=a);return this},setId:function(a){Eb=a;j&&(j.id=a);return this},show:function(){R||(j.style.display="block");"object"==typeof ia&&B&&(ia.style.display="block");Y?R&&(j.style.display="block"):(y.style.display="block",R?($.setElement(j).activate(),j.style.display="block"):(W(window,"resize",sa),W(window,"resize",Oa),sa(),Oa()));da||xa.fire({radius:Qa(Q,G),refresh:!1});la.fire();janrain.events.onModalOpen.fire();j.focus()},close:function(a){d(a)},
closeConfirm:function(){b()},refresh:function(a){Sa||j.appendChild(M);a&&a.center&&g()},remove:function(){if(Y){var a=document.getElementById("previewMode");"object"===typeof M&&j.removeChild(M);"object"===typeof j&&a.removeChild(j);"object"===typeof y&&document.body.removeChild(y);if(a=document.getElementById("janrainEngageEmbed_old"))a.id="janrainEngageEmbed";y=j=""}else"object"===typeof M&&j.removeChild(M),"object"===typeof y&&document.body.removeChild(y),"object"===typeof j&&document.body.removeChild(j)},
addContent:function(b){ia=b;if(!j){j=document.createElement("div");j.id=Eb;if("number"===typeof ya||"string"===typeof ya)j.style.width=ya+"px";j.style.height=za+"px";j.style.position="absolute";da||(j.style.padding=G+"px",F(j,Q),aa(j,G,u,ja));j.style.zIndex=1E3;j.style.display="none";b=Ab();y=document.createElement("div");janrain.settings&&janrain.settings.capture&&janrain.settings.capture.captureServer&&(y.id="janrainModalOverlay");y.style.width=b.width+"px";y.style.height=b.height+"px";y.style.left=
0;y.style.top=0;y.style.backgroundColor="#000000";y.style.position="absolute";b=y;"undefined"!==typeof b.style.filter&&(b.style.filter="alpha(opacity=40)");"undefined"!==typeof b.style.opacity&&(b.style.opacity="0.4");"undefined"!==typeof b.style.KhtmlOpacity&&(b.style.KhtmlOpacity="0.4");"undefined"!==typeof b.style.MozOpacity&&(b.style.MozOpacity="0.4");y.style.display="none";y.style.zIndex=1E3;M=ba?a("a"):a();j.appendChild(M);document.body.appendChild(y);document.body.appendChild(j)}j.appendChild(ia);
setTimeout(Oa,500);Y&&g();return this},getContent:function(){return ia},getBorderWidth:function(){return G},getState:function(){return{width:ya,borderWidth:G,borderColor:u,borderRadius:Q,borderOpacity:ja,orientation:ea}},setState:function(a){m("customizable_auth_widget_styling")&&("undefined"!==typeof a.borderWidth&&q(a.borderWidth),"undefined"!==typeof a.borderColor&&h(a.borderColor),"undefined"!==typeof a.borderOpacity&&A(a.borderOpacity),"undefined"!==typeof a.orientation&&K(a.orientation),"undefined"!==
typeof a.borderRadius&&(("string"==typeof a.borderRadius||"number"==typeof a.borderRadius)&&Da(a.borderRadius),"object"==typeof j&&F(j,Q)))},setConfirmClose:function(a){I=a;return this},setShowContentOnLoad:function(a){B=a;return this},setConfirmMessageText:function(a){P=a},setConfirmLinkText:function(a){Ja=a},setCancelLinkText:function(a){va=a},onClose:ca,onShow:la,onOrientationChange:k,onBorderRadiusChange:xa,onBorderWidthChange:wa}}function Lb(a){function d(){var a=window.open(c,"","width="+b+
", height="+e+", status=1, location=1, resizable=yes"),d=window.setInterval(function(){if(a&&a.closed||a&&"undefined"===typeof a.closed||"undefined"===typeof a)window.clearInterval(d),"function"===typeof g&&g()},500)}var c=a,b=400,e=400,g;return{show:function(){d()},setWidth:function(a){a&&(b=a);return this},setHeight:function(a){a&&(e=a);return this},setCallback:function(a){a&&(g=a);return this}}}function Mb(){function a(){L=(new Date).getTime()-b;if(L<c){var a=Math.round(d()*A+f);e.style[o]=a+"px"}else clearInterval(m),
e.style[o]=h+"px",sa()}function d(){if("flat"==r)return L*(1/c);if("sinusoidal"==r)return Math.abs(Math.sin(L*(Math.PI/(2*c))))}var c="1000",b,e,g=document,f,h,o="left",A,m,L,r="flat",sa,t;return{setAcceleration:function(a){r=a;return this},setCallback:function(a){sa=a;return this},setDuration:function(a){c=a;return this},setDirection:function(a){"horizontal"===a&&(o="left");"vertical"===a&&(o="top");return this},setElement:function(a){e=a;return this},setElementBoundry:function(a){g=a;return this},
startPosition:function(a){f=a;return this},endPosition:function(a){h=a;return this},animate:function(){A=h-f;b=(new Date).getTime();m=setInterval(a,10);return this},drag:function(a){var b=this;this.moveHandler=function(a){var b=Nb({event:ma&&a.targetTouches.length?a.targetTouches[0]:a,boundry:g}).x();e.style.left=b+"px";ua(a);ha(a);t&&clearTimeout(t);t=setTimeout(function(){sa({pos_x:b})},500)};this.upHandler=function(a){b.unbindDragHandlers();ua(a);ha(a)};W(document,Aa,this.moveHandler);W(document,
Ba,this.upHandler);ua(a);ha(a)},unbindDragHandlers:function(){zb(document,Ba,this.upHandler);zb(document,Aa,this.moveHandler);return this}}}function Nb(a){return{x:function(){var d,c=a.event.clientX;var b=a.boundry,e=curtop=0;if(b.offsetParent){do e+=b.offsetLeft,curtop+=b.offsetTop;while(b=b.offsetParent);d=e}d=c-d;d=d<this.boundry_x()?d:this.boundry_x();return 0<d?d:0},boundry_x:function(){var d=a.boundry.getBoundingClientRect();return d.width?d.width:d.right-d.left},y:function(){},boundry_y:function(){}}}
function D(){return new ta}function ta(){this.eventHandlers=[];this.firedEvents=[]}function Fb(){if(function(){if("object"!==typeof janrain.events||"object"!==typeof janrain.apps.engage||"object"!==typeof janrain.apps.engage.signin)return!1;if(!0===janrain.settings.custom)return!0;for(var a="onAuthWidgetLoad,onCustomizationChange,onProviderLoginComplete,onProviderLoginCancel,onProviderLoginError,onProviderLoginStart,onProviderLoginSuccess,onProviderLoginToken,onReturnExperienceFound,onModalWidgetReady".split(","),
c=0;c<a.length;c++)if("object"!==typeof janrain.events[a[c]])return!1;return!0}())clearTimeout(a),janrain.events.onAuthWidgetLoad.fire();else var a=setTimeout(Fb,5)}Array.prototype.indexOf||(Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var d=Object(this),c=d.length>>>0;if(0===c)return-1;var b=0;0<arguments.length&&(b=Number(arguments[1]),b!=b?b=0:0!=b&&Infinity!=b&&-Infinity!=b&&(b=(0<b||-1)*Math.floor(Math.abs(b))));if(b>=c)return-1;for(b=0<=b?b:Math.max(c-Math.abs(b),0);b<
c;b++)if(b in d&&d[b]===a)return b;return-1});Array.prototype.map||(Array.prototype.map=function(a,d){if(null===this)throw new TypeError;var c=Object(this),b=c.length>>>0;if("function"!==typeof a)throw new TypeError;for(var e=Array(b),g=0;g<b;g++)g in c&&(e[g]=a.call(d,c[g],g,c));return e});Array.prototype.filter||(Array.prototype.filter=function(a,d){if(null==this)throw new TypeError;var c=Object(this),b=c.length>>>0;if("function"!=typeof a)throw new TypeError;for(var e=[],g=0;g<b;g++)if(g in c){var f=
c[g];a.call(d,f,g,c)&&e.push(f)}return e});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});var N=window.innerWidth?window.innerWidth:document.body&&document.body.clientWidth?document.body.clientWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:0;ra=window.innerHeight?window.innerHeight:document.body&&document.body.clientHeight?document.body.clientHeight:document.documentElement&&document.documentElement.clientHeight?
document.documentElement.clientHeight:0;qa=N;var U=window.localStorage&&window.localStorage.getItem&&window.localStorage.removeItem&&window.localStorage.setItem,Wa=!1,t="CSS1Compat"!==document.compatMode,ab=!1,u=!1,e=[],N=navigator.userAgent.toLowerCase().match(/(iphone|ipod|ipad|blackberry|rim tablet|android|htc|lg|midp|mmp|mobile|nokia|opera mini|palm|pocket|psp|sgh|smartphone|symbian|treo mini|playstation portable|sonyericsson|samsung|mobileexplorer|palmsource|benq|windows phone|windows mobile|iemobile|windows ce|nintendo wii|\Wsilk\W)/i),
rb=null!==N?N[0]:!1,Ob="number"===typeof window.orientation||null!==N,ma="ontouchstart"in window;Ba=ma?"touchend":"mouseup";Aa=ma?"touchmove":"mousemove";janrain.settings&&janrain.settings.storageServer&&Hb("xDomainLocalStorageJanrain",janrain.settings.storageServer,function(){W(document.getElementById("xDomainLocalStorageJanrain"),"load",function(){Wa=!0})});var P=navigator.userAgent,f=Za(),X=/Gecko\//.test(P),Cb=/AppleWebKit\//.test(P);/Chrome\//.test(P);Ia();var m=function(){var a=function(a){for(var b=
[],d=0;d<a.length;d++)b.push(a[d]);return b},d={};janrain.settings&&janrain.settings.permissions&&(d.login=a(janrain.settings.permissions));janrain.settings&&janrain.settings.share&&janrain.settings.share.permissions&&(d.share=a(janrain.settings.share.permissions));return function(a,b){b=b||"login";return!d[b]?!1:0<=d[b].indexOf(a)}}();pb.options={strictMode:!1,key:"source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(","),q:{name:"queryKey",
parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};for(var $=function(){function a(){if("undefined"===typeof window.orientation)return!1;var a;b(document.body,L);
m=f().content;h();o();document.body.style.padding="0px";document.body.style.margin="0px";"object"===typeof window.onresize&&(a="resize");"object"===typeof window.onorientationchange&&(a="orientationchange");a&&(window.addEventListener(a,function(){Pa(window.orientation,{height:screen?screen.height:0,width:screen?screen.width:0},{height:window.innerHeight,width:window.innerWidth});g()},!1),setTimeout(g,30),window.addEventListener("beforeunload",function(){window.removeEventListener(a,g,!1)},!1));u.addHandler(function(){d({height:window.innerHeight,
width:window.innerWidth},0)});V.addHandler(function(a){ra=a.height;qa=a.width});window.addEventListener("beforeunload",function(){window.removeEventListener(eventName,g,!1)},!1)}function d(a,b){var c=window.innerHeight,e=window.innerWidth,g=!0,f=!0;c!=a.height&&(g=!1);e!=a.width&&(f=!1);g&&f?20>b?setTimeout(function(){d({height:c,width:e},++b)},100):V.fire({height:c,width:e}):setTimeout(function(){d({height:c,width:e},0)},100)}function c(){setTimeout(function(){A(m)},20);b(L,document.body)}function b(a,
b){for(var c=0;c<a.style.length;c++){var d=a.style[c];b.style.setProperty(d,a.style.getPropertyValue(d),a.style.getPropertyPriority(d))}}function e(){var a;a=(0===window.orientation||180===window.orientation)&&qa>ra||(90===window.orientation||-90===window.orientation)&&ra>qa?!1:!0;var b="landscape";if(a&&(0===window.orientation||180===window.orientation))b="portrait";if(!a&&(90===window.orientation||-90===window.orientation))b="portrait";return b}function g(){var a=e();A("width=device-width, initial-scale=1, maximum-scale=1");
u.fire({orientation:a})}function f(){var a=document.getElementsByTagName("meta"),b;for(b in a)if("viewport"===a[b].name)return a[b];return!1}function h(){if("undefined"===typeof document.getElementsByTagName||f())return!1;var a=document.getElementsByTagName("head")[0],b=document.createElement("meta");b.setAttribute("name","viewport");a.appendChild(b);return!0}function o(){if("undefined"===typeof document.getElementsByTagName)return!1;document.getElementsByTagName("head");var a=document.createElement("meta");
a.setAttribute("name","HandheldFriendly");a.content="true"}function A(a){var b=f();if(!b||b.content==a)return!1;if("undefined"===typeof a){var c=f();document.getElementsByTagName("head")[0].removeChild(c)}b.content=a;return!0}var m,L=document.createElement("div"),r=navigator.userAgent.toLowerCase().match(/(iphone|ipod|ipad|blackberry|rim tablet|android|htc|lg|midp|mmp|mobile|nokia|opera mini|palm|pocket|psp|sgh|smartphone|symbian|treo mini|playstation portable|sonyericsson|samsung|mobileexplorer|palmsource|benq|windows phone|windows mobile|iemobile|windows ce|nintendo wii|\Wsilk\W)/i),
t=null!==r?r[0]:!1,u=D(),V=D();t&&t[0].match(/android|\Wsilk\W/);var Pa=function(){var a=window.orientation,b={height:screen?screen.height:0,width:screen?screen.width:0},c={height:window.innerHeight,width:window.innerWidth},d=!1;return function(e,g,f){var h=!1,o=function(a,b){return a.height>=a.width&&b.height>=b.width||a.width>a.height&&b.width>b.height?!0:!1},A=a===e,m=o(g,b),q=o(f,c);if(!A&&(!m||!q))h=!0;!A&&!m&&(d=!0);h&&(d&&!o(g,f)&&(h=f.height,f.height=f.width,f.width=h),ra=f.height,qa=f.width);
a=e;b={height:g.height,width:g.width};c={height:f.height,width:f.width}}}();return{setElement:function(){return this},onOrientationChange:u,onViewportChange:V,getMobileDevice:function(){return t},getOrientation:function(){return e()},activate:function(){a()},deactivate:function(){c()}}}(),ob=function(a){var d;d="https:"===document.location.protocol?"https://docj27ko03fnu.cloudfront.net/":"http://cdn.rpxnow.com/";d=d.replace(/\/$/,"");return d+"/"+a},N={openId:{aol:{identifier:"aol",flow:"openid1",
width:514,height:550,color:"#0FD6FF"},blogger:{identifier:"blogger",flow:"openid1",width:800,height:600,color:"#FF6600"},livejournal:{identifier:"livejournal",flow:"openid1",width:800,height:600,color:"##213368"},netlog:{identifier:"netlog",flow:"openid1",width:800,height:600,color:"#000000"},wordpress:{identifier:"wordpress",flow:"openid1",width:800,height:600,color:"#21759b"},openid:{identifier:"openid",flow:"openid1",width:800,height:600,color:"#f79311"}},openId2:{flickr:{identifier:"https://me.yahoo.com/id",
flow:"openid",width:500,height:500,color:"#FF0084"},google:{identifier:"https://www.google.com/accounts/o8/id",flow:"openid",width:500,height:450,color:"#1C69F5"},hyves:{identifier:"http://hyves.nl/",flow:"openid",width:800,height:600,color:"#659BC8"},myopenid:{identifier:"http://myopenid.com/",flow:"openid",width:800,height:600,color:"#8cc63f"},paypal:{identifier:"https://www.paypal.com/webapps/auth/server",flow:"openid",width:800,height:600,color:"#1A3665"},verisign:{identifier:"http://pip.verisignlabs.com/",
flow:"openid",width:945,height:600,color:"#B8004D"},yahoo:{identifier:"https://me.yahoo.com/id",flow:"openid",width:500,height:500,color:"#650065",shareSettings:{broadcast:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}}},oauth:{facebook:{flow:"facebook",width:1050,height:550,color:"#3B5998",publishSettings:{},shareSettings:{broadcast:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,
media:!0,actionLink:!0}},contact:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,media:!0,actionLink:!0}}}},myspace:{flow:"myspace",width:800,height:500,color:"#000000",shareSettings:{broadcast:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},twitter:{flow:"twitter",width:800,height:500,color:"#35CCFF",shareSettings:{broadcast:{counter:{max:140,urlRegex:/\b(?:[a-z]{1}[-a-z0-9+.]+:(?:\/\/)?)?[-a-z0-9._~@:!$&'()*+,;=]+(?:\.[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\.(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx))(?::\d+)?(?:\/[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\?[-a-z0-9._~@:!$&'()*+,;=%]+)?(?:#[-a-z0-9._~@:!$&'()*+,;=%]+)?\b/ig,
urlLength:23},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}},contact:{counter:{max:140,urlRegex:/\b(?:[a-z]{1}[-a-z0-9+\.]+:(?:\/\/)?)?[-a-z0-9._~@:!$&'()*+,;=]+(?:\.[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\.(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx))(?::\d+)?(?:\/[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\?[-a-z0-9._~@:!$&'()*+,;=%]+)?(?:#[-a-z0-9._~@:!$&'()*+,;=%]+)?\b/ig,urlLength:23},
format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},linkedin:{flow:"linkedin",width:550,height:750,color:"#006699",shareSettings:{broadcast:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,media:!1,actionLink:!1}},contact:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},live_id:{flow:"liveid",width:900,height:600,
color:"#666666"},salesforce:{flow:"salesforce",width:800,height:500,color:"#333333"},orkut:{flow:"orkut",width:800,height:600,color:"#333"},vzn:{flow:"vzn",width:600,height:450,color:"#333"},foursquare:{flow:"foursquare",width:950,height:550,color:"#333"},sinaweibo:{flow:"sinaweibo",width:950,height:550,color:"#333"},renren:{flow:"renren",width:950,height:550,color:"#333"},soundcloud:{flow:"soundcloud",width:950,height:550,color:"#333"},mixi:{flow:"mixi",width:950,height:550,color:"#333",shareSettings:{broadcast:{counter:{},
format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}},contact:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},email:{color:"#009ddc",shareSettings:{email:{providers:{google:!0,yahoo:!0},counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}}}},Xa={},Ka=["openId",
"openId2","oauth"];0<Ka.length;){var Ta=Ka.pop(),Ua;for(Ua in N[Ta])Xa[Ua]=N[Ta][Ua]}_draggingSliderFx=[];var o=function(){var a=[];return{log:function(d){var c={};c.id=a.length+1;c.message=d;a.push(c);return this},show:function(){if(0!=a.length){for(var d in a)if("undefined"!==typeof a[d].id){var c=a[d];"object"===typeof console&&("function"===typeof console.error?console.error("WARNING ID:"+c.id+" MESSAGE: "+c.message):"function"===typeof console.log&&console.log("WARNING ID:"+c.id+" MESSAGE: "+
c.message))}a=[]}}}}();ta.prototype.addHandler=function(a){this.eventHandlers.push(a);return this.eventHandlers.length-1};ta.prototype.removeHandler=function(a){return this.eventHandlers[a]?(this.eventHandlers[a]=null,!0):!1};ta.prototype.fire=function(a){for(var d=this.eventHandlers.length,c=0;c<d;c++)try{if("function"===typeof this.eventHandlers[c])this.eventHandlers[c](a)}catch(b){o.log(b),o.show()}this.firedEvents.push({event:this,args:a})};"undefined"===typeof janrain.events&&(janrain.events=
{});var I;I||(I={});(function(){function a(a){return 10>a?"0"+a:a}function d(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=h[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,b){var e,h,m,r,t=g,u,j=b[a];j&&"object"===typeof j&&"function"===typeof j.toJSON&&(j=j.toJSON(a));"function"===typeof o&&(j=o.call(b,a,j));switch(typeof j){case "string":return d(j);case "number":return isFinite(j)?""+j:"null";case "boolean":case "null":return""+
j;case "object":if(!j)return"null";g+=f;u=[];if("[object Array]"===Object.prototype.toString.apply(j)){r=j.length;for(e=0;e<r;e+=1)u[e]=c(e,j)||"null";m=0===u.length?"[]":g?"[\n"+g+u.join(",\n"+g)+"\n"+t+"]":"["+u.join(",")+"]";g=t;return m}if(o&&"object"===typeof o){r=o.length;for(e=0;e<r;e+=1)"string"===typeof o[e]&&(h=o[e],(m=c(h,j))&&u.push(d(h)+(g?": ":":")+m))}else for(h in j)Object.prototype.hasOwnProperty.call(j,h)&&(m=c(h,j))&&u.push(d(h)+(g?": ":":")+m);m=0===u.length?"{}":g?"{\n"+g+u.join(",\n"+
g)+"\n"+t+"}":"{"+u.join(",")+"}";g=t;return m}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,f,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;"function"!==typeof I.stringify&&(I.stringify=function(a,b,e){var d;f=g="";if("number"===typeof e)for(d=0;d<e;d+=1)f+=" ";else"string"===typeof e&&(f=e);if((o=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})});
"function"!==typeof I.parse&&(I.parse=function(a,c){function e(a,b){var d,g,f=a[b];if(f&&"object"===typeof f)for(d in f)Object.prototype.hasOwnProperty.call(f,d)&&(g=e(f,d),void 0!==g?f[d]=g:delete f[d]);return c.call(a,b,f)}var d,a=""+a;b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),"function"===typeof c?e({"":d},""):d;throw new SyntaxError("JSON.parse");})})();janrain.events.onCustomizationChange||(janrain.events.onCustomizationChange=D());janrain.events.onProviderLoginStart||(janrain.events.onProviderLoginStart=D());janrain.events.onProviderLoginComplete||(janrain.events.onProviderLoginComplete=D());janrain.events.onProviderLoginError||(janrain.events.onProviderLoginError=D());janrain.events.onProviderLoginSuccess||
(janrain.events.onProviderLoginSuccess=D());janrain.events.onProviderLoginToken||(janrain.events.onProviderLoginToken=D());janrain.events.onProviderLogoutStart||(janrain.events.onProviderLogoutStart=D());janrain.events.onProviderLogoutComplete||(janrain.events.onProviderLogoutComplete=D());Fb();Ua=new function(){function a(){function a(){return{twoColumn:{actionText:"Sign in using your account with",providersPerPage:6},oneColumn:{actionText:"Sign in with",width:200},oneRow:{actionText:"Sign in with"},
footerHeight:10,headerHeight:20}}function b(){if(na){var a=document.createElement("div");a.style.backgroundColor=Z?"aqua":La;a.style.width=z+"px";a.style.height=Ia+"px";a.style.position="absolute";a.style.left="0px";a.style.paddingLeft=n+"px";a.style.paddingRight=n+"px";a.style.paddingBottom=n+"px";a.style.bottom="0px";a.style.fontSize="10px";a.style.textAlign="left";a.style.color=X;F(a,null,0,0,v,v);var p=document.createElement("div");p.appendChild(document.createTextNode(janrain.settings.translate.POWERED_BY_PREFIX||
"Powered by "));p.style.paddingLeft="1px";var e=document.createElement("a");e.setAttribute("href","http://www.janrain.com/products/engage/engage-introduction?utm_source=login.janrain.com&utm_medium=partner&utm_campaign=attribution");e.setAttribute("target","_blank");e.appendChild(document.createTextNode("Janrain"));p.appendChild(e);a.appendChild(p);Ra=a}w=g();a=document.createElement("div");a.style.backgroundColor=Z?"orange":La;a.className="janrainHeader";a.style.fontSize=aa+"px";a.style.color=X;
a.style.position="relative";a.style.height=oa+"px";40===pa&&(a.style.cssFloat="left");a.style.left=40===pa?"-6px":"-5px";a.style.paddingLeft=n+"px";a.style.paddingRight=n+"px";a.style.paddingTop=n+"px";a.style.paddingBottom="0px";a.style.whiteSpace="nowrap";a.style.width=40===pa?"81px":z+"px";a.style.zIndex="100";40===pa?F(a,null,v,0,0,v):F(a,null,v,v,0,0);40===pa&&(a.style.marginTop="-3px");a.style.textAlign="one column"===l?"center":"left";p=d();ba=document.createElement("div");ba.style.paddingLeft=
"1px";ba.style.fontFamily=U;" "!==p&&ba.appendChild(document.createTextNode(p));a.appendChild(ba);Qa=a;s=document.createElement("div");s.className="janrainContent";s.style.width=z+"px";s.style.height=i()+"px";s.style.paddingLeft=n+"px";s.style.paddingRight=n+"px";s.style.boxSizing="content-box";40===pa&&(s.style.paddingTop=n-1+"px");u||(s.style.backgroundColor=La);u||(s.style.border=wa?"1px solid "+ua:"1px solid "+La);s=F(s,v);u||(s.style.overflow="hidden");s.style.position=wa?"relative":"absolute";
Va=A();2==w||0==w?(Fa=(new q).setSide("right").create(),Ga=(new q).setSide("left").create()):(Fa=(new q).setSide("top").create(),Ga=(new q).setSide("bottom").create());a=document.createElement("div");a.id="janrainView";" "!==d()&&a.appendChild(Qa);p=J("blank");p.style.display="none";a.appendChild(p);a.appendChild(Va);!u&&Fa&&Ga&&(a.appendChild(Fa),a.appendChild(Ga));0<w&&na&&a.appendChild(Ra);s.appendChild(a);m("customizable_auth_widget_styling")||c(s);ab||o.show()}function c(a){function b(a){var c=
"string"===typeof a.getAttribute("style")?a.getAttribute("style"):null;c&&(c.cssText&&(c=c.cssText),a.style.setAttribute?a.style.setAttribute("cssText",c.replace(/(((?!!important).)+?);/g,"$1 !important;")):a.setAttribute("style",c.replace(/(((?!!important).)+?);/g,"$1 !important;")))}for(var p=a.getElementsByTagName("*"),d=0,e=p.length;d<e;d++)"janrainProviderPages"===p[d].id||"janrainSlideControl"===p[d].className||"janrainSlideControl"===p[d].parentNode.className||b(p[d]);b(a)}function d(){return Da?
O:e.translate.HEADER?e.translate.HEADER:"two column"===l?a().twoColumn.actionText:"one column"===l?a().oneColumn.actionText:"one row"===l?a().oneRow.actionText:O}function g(){var a=l;if("default"==a||"two column"==a)return 2;if("one column"==a)return 1;if("one row"==a)return 0}function i(){var a=" "===O?0:oa+n,b=na&&"one row"!==l?Ia+n:0;return h()+a+b}function j(){var a=parseInt(Va.style.left),b=parseInt(Va.style.top),c;1==w?parseInt(Va.style.height):parseInt(Va.style.width);2==w&&(c=(z-3*n-(2==w?
10:0))/w);if("one column"===l){if(" "===O&&(b+=11,0<b||-9<=b))return 0;if(9>b)return 1;if(0<b||b>=-(oa-(n+1)))return 0}0==w&&(c=z-100);if(0>a&&a<-c)return 1;if(0<a||a>=-n)return 0}function h(){if("two column"===l)var a=H/2;"one column"===l&&(a=H);"one row"===l&&(a=1);var b="one row"===l?0:2*a,c="one column"===l?3*n:0;if(7===f||6===f||f&&t){if("two column"===l&&(c=n,7===f||6===f))c=2*n;if("one column"===l&&(c=3*n,(7===f||6===f)&&!t))c+=n;if("one row"===l&&(7===f||6===f))c=n}"one column"===l&&Ha<=H&&
(c=f&&t?c+2*n:c-2*n);return C*a+n*(a+1)+b+c}function q(){function a(){var b;i="over";var e=j();if(0==e&&"left"===d||0==e&&"top"===d||1==e&&"right"===d||1==e&&"bottom"===d)return this.style.cursor="default",k.onclick="",!1;var Pb=this;setTimeout(function(){if(1===o){if("over"!==i)return!1;f&&(p.style.display="block");g.style.display="block";k.onclick=c;Pb.style.cursor="pointer";var a=document.getElementById("janrainProviderPages");b="top"==d||"bottom"==d?parseInt(a.style.top):parseInt(a.style.left);
var e="right"===d||"bottom"===d?b-Ea:b+Ea;"top"===d||"bottom"===d?a.style.top=e+"px":a.style.left=e+"px";o=2}},f?50:100)}function b(){var a;i="out";var c=j();if(1==c&&"right"===d||0==c&&"left"===d||0==c&&"top"===d||1==c&&"bottom"===d)return!1;setTimeout(function(){if(2===o){if("out"!==i)return!1;f&&(p.style.display="none");g.style.display="none";var b=document.getElementById("janrainProviderPages");a="top"==d||"bottom"==d?parseInt(b.style.top):parseInt(b.style.left);var c="right"===d||"bottom"===
d?a+Ea:a-Ea;"top"===d||"bottom"===d?b.style.top=c+"px":b.style.left=c+"px";o=1}},f?200:400)}function c(){g.style.display="none";k.style.cursor="default";y(d,function(a){D(a);o=1})}var p,d,e,g,x={left:"-33px -16px",right:"0px -16px",top:"-16px -33px",bottom:"-16px 0px"},i="",o=1,k;return{setSide:function(a){d=a;return this},create:function(){var f;if(Ha<=H)f=!1;else{f=document.createElement("div");f.setAttribute("id","janrainShim_"+d);f.style.background="black";"top"===d||"bottom"===d?(f.style.height=
"19px",f.style.width="100%"):(f.style.height="100%",f.style.width="17px");f.style.filter=Z?"alpha(opacity=100)":"alpha(opacity=0)";f.style.position="absolute";f.style.zindex="99";if("top"===d||"bottom"===d)f.style.left="0";f.style[d]=n+"px";f.style.top="one column"!==l?n+1+"px":"top"===d?"10px":"0px";f.style.display="none";p=f;f=document.createElement("div");f.style.backgroundColor=Z?"green":La;f.className="janrainSlideControllerMask";f.style.position="absolute";"one column"!==l&&(f.style.width=n+
"px",f.style.height="100%",f.style.top="0px",f.style[d]="0px",f.style.borderWidth="1px","right"===d&&(!na||"one row"===l)&&F(f,null,0,0,v,0),"left"===d&&(!na||"one row"===l)&&F(f,null,0,0,0,v),"right"===d&&" "===O&&F(f,null,0,v,v,0),"left"===d&&" "===O&&F(f,null,v,0,0,v));"one column"===l&&(f.style.height=n+"px",f.style.fontSize="0px",f.style.width="100%",f.style.padding="0px",f.style[d]="0px","top"===d&&" "===O?F(f,null,v,v,0,0):"bottom"===d&&!na&&F(f,null,0,0,v,v));"one row"===l&&(f.style.height=
"105.5%");e=f;f=document.createElement("div");f.setAttribute("id","janrainArrow_"+d);f.style.background="url("+ob("rel/img/ee9d3aa7c5896c69488b5941ef31c7bc.png")+") no-repeat scroll "+x[d]+" transparent";f.style.height="19px";f.style.width="17px";f.style.position="absolute";if("top"===d||"bottom"===d)f.style.left=z/2+"px";f.style[d]=n+"px";f.style.top="one column"!==l?h()/2-2*n+1+"px":"top"===d?"10px":"0px";f.style.display="none";g=f;f=document.createElement("div");f.className="janrainSlideControl";
f.style.backgroundColor=Z?"purple":"transparent";"one column"===l?(f.style.width=z+4+"px",f.style.left="3px","top"==d?(f.style.height=n+"px",f.style.top=oa+n+"px"," "===O&&(f.style.left="0px",f.style.width=z+10+"px")):(f.style.height="20px",f.style.bottom=(na?Ia+n:0)+"px",F(f,null,0,0,v,v))):(f.style.width="right"===d?"20px":"0px",f.style[d]="0px",f.style.height=h()-(n*(" "===O)?1:2)+"px",40===pa&&"one row"===l&&"left"===d&&(f.style.left=ta+"px"),"right"===d&&!na&&F(f,null,0,0,v,0),"left"===d&&!na&&
F(f,null,0,0,0,v));f.style.position="absolute";f.style.zIndex="100";f.style.cursor="pointer";f.onmouseover=a;f.onmouseout=b;f.onclick=c;k=f;k.appendChild(e);k.appendChild(p);k.appendChild(g);f=k}return f}}}function y(a,b){var c=document.getElementById("janrainProviderPages"),d=new Mb;if("top"===a||"bottom"===a){if(" "===O)var p=-(h()-C),e=0;else p=-(h()-C-oa-n),e=oa+n;50===C&&(p-=20);f&&t&&(p+=n," "!==O&&(e+=n));d.setElement(c).setAcceleration("sinusoidal").setDuration(100*H).startPosition(parseInt(c.style.top)).endPosition("bottom"===
a?p:e).setDirection("vertical").setCallback(function(){b(a)}).animate()}else f&&t?(p=-(z-2*n-39),"one row"===l&&(p=-(ta-1*n))):(p=-(z-32),"one row"===l&&(p=-(z-24))),d.setElement(c).setAcceleration("sinusoidal").setDuration(800).startPosition(parseInt(c.style.left)).endPosition("right"==a?p:n).setDirection("horizontal").setCallback(function(){b(a)}).animate()}function A(){var a,b;function c(d){d=d.touches[0];"one column"===l?a=d.pageY:b=d.pageX}function d(c){c.preventDefault();c=c.touches[0];c="one column"===
l?a-c.pageY:b-c.pageX;if(35<c||-35>c){var p;p="one column"===l?0<c?"bottom":"top":0<c?"right":"left";var e=j(),f=!0;"bottom"===p&&e+1==h&&(f=!1);"top"===p&&0==e&&(f=!1);"left"===p&&0==e&&(f=!1);"right"===p&&e+1==h&&(f=!1);f&&("one column"===l?g.style.top=parseInt(g.style.top)-c+"px":g.style.left=parseInt(g.style.left)-c+"px",y(p,function(){D()}),g.ontouchmove="")}}function p(){g.ontouchmove=d}var e,g,x,i,h,k=w,m=[];i=E();h=u?1:Math.ceil(Ha/H);2<h&&o.log("Either reduce the number of providers, or increase the setting for providersPerPage.");
g=document.createElement("div");g.setAttribute("id","janrainProviderPages");u&&(g.className="janrainConfigureMode");g.style.paddingTop=(6===f||7===f)&&f&&t?2*n:n+"px";if((6===f||7===f)&&!t)g.style.paddingTop=n+4+"px";1<h&&(g.ontouchstart=c,g.ontouchmove=d,g.ontouchend=p);40===pa&&"one row"===l?g.style.left=ta+n+"px":f&&t?"one column"!==l&&(g.style.left=n+"px"):g.style.left=n+"px";40===pa&&"one row"===l&&(g.style.cssFloat="left");40===pa&&"one row"===l&&(g.style.marginTop="1px");"one column"===l&&
(g.style.top=(f&&t?1:0)+oa+n+"px");"one row"!==l&&" "===O&&(g.style.top="0px");"one column"===l&&" "===O&&(g.style.top="0px");e=z*h;g.style.position=f&&t&&"one column"===l?"relative":"absolute";"two column"===l&&!(Ha<=H)&&(g.style.width=e+"px");"one row"===l&&(g.style.width=(!0===u?z+n:2*z)+"px");u&&(k=0);b=0;a=0;for(var sb=0;sb<h;sb++){for(x=0;x<=k;x++)m[x]=document.createElement("ul"),m[x].className="providers",m[x].id="janrainProviders_"+x,1<k&&(m[x].style.cssFloat="left"),1<k&&(m[x].style.styleFloat=
"left"),m[x].style.listStyleType="none",m[x].style.marginTop="0px",m[x].style.marginLeft="0px",m[x].style.marginRight="0px",m[x].style.marginBottom="0px",m[x].style.padding="0px";e=document.createElement("div");e.className="janrainPage";e.setAttribute("pageIndex",sb);f&&t&&1===h&&(e.style.width="110%");for(x=0;x<=k;x++)e.appendChild(m[x]);for(var q=i.length%2,r=u?Ha:H,Gb=0;Gb<r&&!(0==i.length);Gb++){if(2==k)var s=1==q?m[i.length%2?0:1]:m[i.length%2];if(1==k||0==k)s=m[0];x=i.shift();s.appendChild(x)}g.appendChild(e)}return g}
function D(a){0==j()?("left"===a&&(Ga.style.width=n+"px",Fa.style.display="block",Fa.style.width="20px"),"top"===a&&(Fa.style.height=n+"px",Ga.style.display="block",Ga.style.height="20px")):("right"===a&&(Fa.style.width=n+"px",Ga.style.display="block",Ga.style.width="20px"),"bottom"===a&&(Ga.style.height=n+"px",Fa.style.display="block",Fa.style.height="20px"))}function E(){for(var a=[],b=0;b<Ha;b++){var c=J(ma[b]);a.push(c)}return a}function G(a,b){b.style.cursor="pointer";b.setAttribute("id","janrain-"+
a);b.setAttribute("role","button");"one row"===l?b.style.background="transparent":("gradient"===Ma&&yb(b,"bottom, #eeeeee, #ffffff"),"gray"===Ma&&(b.style.backgroundColor="#eeeeee"),"white"===Ma&&(b.style.backgroundColor="#ffffff"));W(b,"mouseover",function(){Za();"one row"===l?b.style.background="transparent":(b.style.backgroundColor="#E3E3E3",b.style.backgroundImage="")});W(b,"mouseout",function(){Za();"one row"===l?b.style.background="transparent":("gradient"===Ma&&yb(b,"bottom, #eeeeee, #ffffff"),
"gray"===Ma&&(b.style.backgroundColor="#eeeeee"),"white"===Ma&&(b.style.backgroundColor="#ffffff"))});ab||K(b,a);return b}function J(a){var b=document.createElement("li");b.style.listStyle="none";0==w&&!1===u&&(b.style.cssFloat="left");0==w&&!1===u&&(b.style.styleFloat="left");b.style.textAlign="center";b.style.height=f&&t?C-2:C+"px";if("two column"==l){var c=u?3*n:Ha<=H?0:3*n;b.style.width=6===f||Za&&t?(z-c-4*n)/w+"px":(z-c-(2==w?10:0))/w+"px"}b.style.marginTop="0px";if("one column"==l){if(7==f||
6==f)b.style.marginTop="-1px";f&&t?b.style.marginRight="0px":b.style.width=z-n/2+"px";b.style.marginLeft="0px"}else b.style.marginRight=n+"px";0==w&&(b.style.width=C+"px");b.style.marginBottom=(7===f||6===f||f&&t?3:n)+"px";b.style.position="relative";0!=w&&(b.style.border="1px solid "+sa);0!=w&&F(b,ga);if("customopenid"===a){c=document.createElement("img");if(1==w||2==w)30==C&&(c.src=xa.smallLogo),50==C&&(c.src=xa.largeLogo);0==w&&(30==C&&(c.src=xa.smallIcon),50==C&&(c.src=xa.largeIcon))}else if(c=
document.createElement("span"),"blank"!==a){if(1==w||2==w)30==C&&(c.className="janrain-provider100-"+a,c.style.width=100),50==C&&(c.className="janrain-provider150-"+a,c.style.width=150);0==w&&(30==C&&(c.className="janrain-provider-icon-32 janrain-provider-icon-"+a,c.style.width=32),50==C&&(c.className="janrain-provider-icon-48 janrain-provider-icon-"+a,c.style.width=48))}f&&t&&(c.style.height=C-2+"px");if(6===f&&"one row"!==l){var d=document.createElement("div");d.style.height=c.style.height;d.style.width=
"90px";d.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enable=true,sizingMethod=crop,src='"+c.src+"')";c.style.filter="alpha(opacity=0)";d.appendChild(c);b.appendChild(d)}else b.appendChild(c);return G(a,b)}function N(a,b){var c=document.createElement("div"),d=e.translate.SIGN_IN_AS||"Sign in as {name}",d=d.replace("{name}",b),d=document.createTextNode(d),p=document.createElement("div");p.style.cssFloat="right";p.style.styleFloat="right";p.style.fontFamily=U;p.style.position="relative";
p.style.top="one row"===l?"2px":C/4-3+"px";p.appendChild(d);var g=document.createElement("div"),x=7.5*d.length+30,h=i();g.style.fontSize="16px";g.style.height="100%";g.style.position="relative";if(0==w||120>h)15<=d.length&&(g.style.fontSize="14px",x=7*d.length+30),20<=d.length&&(g.style.fontSize="12px",x=6*d.length+30),24<=d.length&&(g.style.fontSize="10px",x=5*d.length+25),30<=d.length&&(d.textContent=d.textContent.substr(0,26)+"...",x=162);g.style.width=x+"px";if(0==w||116>h){if("customopenid"===
a){var j=document.createElement("img");j.src=xa.smallIcon}else j=document.createElement("span"),j.className="janrain-provider-icon-20 janrain-provider-icon-"+a;j.style.width="20px";j.style.height="20px";j.style.cssFloat="left";j.style.styleFloat="left"}c.style.overflow="hidden";c.style.position="relative";c.style.height=("one row"!==l?C:25)+"px";c.style.marginBottom="one row"===l?"-4px":"4px";"one row"===l&&(c.style.top="-4px");c.style.left="0px";f&&t&&(c.style.marginRight="5px");f&&t&&(c.style.marginLeft=
"3px");c.style.border="1px solid "+sa;F(c,ga);"customopenid"===a&&(c.style.color=Xa[a].color);if(0==w||116>h)g.style.paddingTop="2px",g.appendChild(j);6===f||7===f||f&&t?g.style.left="10px":g.style.margin="0 auto";g.appendChild(p);0==w||116>h?c.appendChild(g):(50===C&&parseInt(c.style.height),p.style.cssFloat="none",p.style.styleFloat="none",c.appendChild(p));return G(a,c)}function K(a,b){W(a,"click",function(){L(b)})}function L(a){var b=Xa[a],c={appUrl:e.appUrl,mobileDevice:rb,language:e.language,
popup:Sa,tokenUrl:ea||e.tokenUrl||window.location.href,facebookPermissions:da,forceReauth:Ja,widgetType:"auth",tokenAction:va,bpChannel:Ka,customOpenid:Ta,customOpenidOpxblob:e.customOpenidOpxblob};b.name=a;new Ua(b,c,function(){ca||(Ya=setTimeout(function(){Ca(b)},300))})}function I(a){var b=document.createElement("div");if("customopenid"===a){var c=document.createElement("img");c.src=xa.largeLogo}else c=document.createElement("span"),c.className="janrain-provider150-"+a;c.style.width="150px";c.style.height=
"50px";b.style.position="absolute";b.style.top="0px";b.style.left="0px";b.style.width=z+"px";b.style.zIndex="102";b.style.textAlign="center";b.style.padding=n+"px";b.style.backgroundColor="transparent"===La?"#ffffff":La;b.style.height=i()-(f&&t?0:2*n)+"px";F(b,v);"one row"!==l&&116<=i()&&b.appendChild(c);return b}function P(a){var b=document.createElement("a"),c=document.createTextNode(e.translate.USE_ANOTHER_ACCOUNT||"switch accounts");b.setAttribute("class","janrainSwitchAccountLink");b.setAttribute("href",
"");b.style.fontSize="12px";b.style.fontFamily=U;b.style.color=X;b.onclick=a;b.appendChild(c);return b}function Q(){return"modal"===B?document.getElementById("janrainModal"):"embed"===B?document.getElementById("janrainEngageEmbed"):!1}function S(){var a=parseInt(s.style.width);return a=a+2*n+2}function T(){var a=Q();null!==a&&"object"===typeof s&&s.parentNode===a&&a.removeChild(s)}function V(){var a="";"object"===typeof k&&(a=k.getState());return{type:B,width:S(),fontFamily:U,fontSize:aa,fontColor:X,
backgroundColor:La,borderColor:ua,borderRadius:v,format:l,providersPerPage:H,providers:ma,buttonBackgroundStyle:Ma,buttonBorderColor:sa,buttonBorderRadius:ga,actionText:d(),showAttribution:na,modalState:a}}function Y(a){l=r("string",["default","two column","one column","one row"],"two column",a);"default"===l&&(l="two column");"one row"==a&&(v=r("number",[0,10],5,v));ia()}function R(a){"two column"===l&&(z=r("number",[225,600],380,a));"one column"===l&&(z=r("number",[160,600],200,a));"one row"===
l&&(C=30,a=Ha<=H?n*(parseInt(H)-1):n*(parseInt(H)+2),40===pa&&(a+=ta-n),z=C*H+a);if(("two column"===l||"one column"===l)&&!u)z=z-2*n-2;f&&t&&(z=z+2*n+2);"one row"!==l&&(C=380<z?50:30)}function $(b){"string"===typeof b&&(Da=!0,O=r("text",null,O,b)," "===O?v=r("number",[0,5],5,v,!0):oa="two column"!==l?a().headerHeight-5:a().headerHeight)}function fa(a){Ma=r("string",["gray","white","gradient"],"gradient",a)}function ha(a){sa=r("color",null,"#CCCCCC",a)}function ka(a){La=r("color",null,"#ffffff",a)}
function la(a){"undefined"===typeof a&&(a=5);v=" "===O||!na||"one row"===l?r("number",[0,5],5,a,!0):r("number",[0,10],10,a)}function qa(a){na=r("boolean",null,!0,a);i();v=a?r("number",[0,10],5,v,!0):r("number",[0,5],5,v,!0)}function ra(a){ua=r("color",null,"#C0C0C0",a)}function ia(){"two column"===l&&(aa=18);if("one column"===l||"one row"===l)aa=14}function za(a){X=r("color",null,"#333333",a)}function Aa(a){if("object"==typeof a){w=g();for(var b=0,c=a.length;b<c;b++)Xa[a[b]]||(o.log(a[b]+" is not a valid provider: removing."),
a.splice(b,1),--b,--c);ma=a;Ha=a.length;"object"===typeof k&&k.setHeight(i()-2*n).refresh()}}function Ba(a){"two column"===l&&(H=r("number",[4,6,8],6,a));"one column"===l&&(H=r("number",[1,6],6,a));"one row"===l&&(H=tb?Ha:r("number",[4,8],6,a),R(z))}function Ca(a){var b=document.createTextNode(e.translate&&e.translate.SIGNING_IN?e.translate.SIGNING_IN:"Signing in ..."),c=document.createElement("div");Na=I(a.name);c.appendChild(b);Na.appendChild(c);s&&s.appendChild(Na)}var Z=!1,z=380,Da=!1,U="lucida grande, Helvetica, Verdana, sans-serif",
aa=18,X="#666666",La="#ffffff",ua="#C0C0C0",v=10,s,ba,l="two column",w,wa,H=6,ma=["aol","google","yahoo","openid"],Ha=4,sa="#CCCCCC",ga=5,Ma="gradient",C=30,oa=a().headerHeight,pa=60,ta=89,Ia=a().footerHeight,n=5,Ea=10,O="Sign in using your account with",Na,Va,Fa,Ga,na=!0,Oa=!1,Pa=!1,Qa,Ra;janrain.events.onProviderLoginStart.addHandler(function(a){ya("login_tab",a.provider,1)});return{build:b,setFormat:function(b){b&&Y(b);"two column"!==l&&(oa=a().headerHeight-5);"two column"===l&&(H=a().twoColumn.providersPerPage,
oa=a().headerHeight);return this},setActionText:function(a){"string"===typeof a&&$(a);return this},setFontSize:function(a){a&&ia(a);return this},setFontFamily:function(a){a&&a&&(U=a);return this},setFontColor:function(a){a&&za(a);return this},setButtonBorderColor:function(a){a&&ha(a);return this},setButtonBorderRadius:function(a){if("string"==typeof a||"number"==typeof a)ga=r("number",[0,20],5,a);return this},setButtonBackgroundStyle:function(a){a&&fa(a);return this},setWidth:function(a){("string"==
typeof a||"number"==typeof a)&&R(a);return this},refresh:function(){T();var a=Q();b();var c=M("expected_tab");c&&!Wa?ja("expected_tab",c):(null!==a&&"object"===typeof s&&a.appendChild(s),"object"===typeof k&&k.setHeight(parseInt(s.style.height)+2).refresh());janrain.events.onCustomizationChange.fire(V());return this},remove:function(){T();return this},setRowHeight:function(a){if(0!==g())return this;a||(a=60);oneRowHeaderHeight=r("number",[40,60,90],60,a);40===oneRowHeaderHeight&&(C=30,pa=40);60===
oneRowHeaderHeight&&(C=30);90===oneRowHeaderHeight&&(C=50);return this},setHeight:function(a){"object"==typeof s&&(s.style.height=a+"px");return this},setBackgroundColor:function(a){a&&ka(a);return this},setBorderColor:function(a){a&&ra(a);return this},setBorderRadius:function(a){("string"==typeof a||"number"==typeof a)&&la(a);return this},setProviders:function(a){"object"==typeof a&&Aa(a);return this},setProvidersPerPage:function(a){if("string"==typeof a||"number"==typeof a)Ba(a),"object"===typeof k&&
k.setHeight(i()).refresh("janrainModal");return this},setShowAttribution:function(a){"boolean"===typeof a&&qa(a);return this},setPreviewMode:function(a){"boolean"===typeof a&&(ab=a);return this},setProviderFlow:function(a,b){return K(a,b)},triggerFlow:function(a){return L(a)},setNoReturnExperience:function(a){"boolean"===typeof a&&(Oa=a);return this},setNoReturnExperienceSwitchAccountLink:function(a){"boolean"===typeof a&&(Pa=a);return this},setConfigureMode:function(a){"boolean"===typeof a&&(u=a,
w=g());return this},embed:function(a){if((wa=a)&&"object"==typeof s)s.style.position="relative";return this},getContentsDiv:function(){return s},getErrorPage:function(a,b){var c=document.createTextNode(b.msg),d=document.createElement("div");d.appendChild(c);d.style.color=X;d.style.fontSize=aa+"px";d.style.width="100%";var p=I(a);p.appendChild(d);p.appendChild(P(function(){s.removeChild(p);s.removeChild(Na);Ja=!0;return!1},a));s.appendChild(p);return s},getReturnExperience:function(a,b){if(ab||Oa||
-1===ma.indexOf(a))return s;var c=N(a,b),d=I(a),p=function(){Ja=Wa=!0;s.removeChild(d);return!1};d.id="janrainAuthReturnExperience";d.appendChild(c);Pa||d.appendChild(P(p,a));s.appendChild(d);return s},getWidth:function(){return S()},getActualHeight:function(){return parseInt(s.style.height)+2},getHeight:function(){return i()-2*n},getState:function(){return V()},setState:function(b){if(m("customizable_auth_widget_styling")){var c=b.fontFamily;c&&(U=c);ia(b.fontSize);za(b.fontColor);ka(b.backgroundColor);
ra(b.borderColor);"embed"===B&&b.format&&(b.format&&Y(b.format),"two column"!==l&&(oa=a().headerHeight-5),"two column"===l&&(H=a().twoColumn.providersPerPage,oa=a().headerHeight));if("string"==typeof b.providersPerPage||"number"==typeof b.providersPerPage)Ba(b.providersPerPage),"object"===typeof k&&k.setHeight(i()).refresh("janrainModal");fa(b.buttonBackgroundStyle);ha(b.buttonBorderColor);ga=r("number",[0,20],5,b.buttonBorderRadius);$(b.actionText);qa(b.showAttribution);la(b.borderRadius);"embed"===
B&&("string"==typeof width||"number"==typeof width)&&R(b.width)}Aa(b.providers)},showNotice:function(){Ca()},removeNotice:function(){Na&&Na.parentNode&&Na.parentNode.removeChild(Na)},removeReturnExperience:function(){var a=document.getElementById("janrainAuthReturnExperience");a&&a.parentNode&&a.parentNode.removeChild(a)}}}function d(){if("object"===typeof i)if("object"===typeof J){var a=i.getState();a.width=J.width;J=a}else J=i.getState();"object"===typeof i&&i.remove();"object"===typeof k&&k.remove();
q();B="modal";"object"===typeof i&&J&&m("customizable_auth_widget_styling")&&i.setState(J);"object"===typeof k&&wa&&m("customizable_auth_widget_styling")&&k.setState(wa);"object"===typeof k&&k.show();"object"===typeof i&&i.refresh()}function c(){if("object"===typeof i){if("object"===typeof J){var a=i.getState();a.borderRadius=J.borderRadius;a.format=J.format;a.width=J.width;J=a}else J=i.getState();wa=J.modalState;delete wa.orientation}"object"===typeof i&&i.remove();"object"===typeof k&&k.remove();
"object"===typeof k&&(k="");E();B="embed";"object"===typeof i&&J&&m("customizable_auth_widget_styling")&&i.setState(J);"object"===typeof i&&i.refresh()}function b(){var a,b;q();b=document.getElementsByTagName("a");var c=RegExp("(\\s|^)"+e.linkClass+"(\\s|$)");for(a in b)c.test(b[a].className)&&(b[a].onclick=g)}function E(){var b=M("expected_tab");i=new a;i.setBackgroundColor(bb).embed(!0).setPreviewMode(cb).setShowAttribution(db).setNoReturnExperience(eb).setNoReturnExperienceSwitchAccountLink(ub).setFormat(ua).setRowHeight(X).setFontSize(fb).setFontFamily(gb).setFontColor(hb).setActionText(ib).setProviders(ma).setProvidersPerPage(jb).setWidth(U).setBorderColor(Z).setBorderRadius(Ca).setButtonBorderColor(kb).setButtonBorderRadius(lb).setButtonBackgroundStyle(mb).build();
var c=document.getElementById("janrainEngageEmbed");null===c&&(c=document.getElementById("janrainModal"));ka||(b?(Q("welcome_info_name",unescape(M("welcome_info_name"))),ja("expected_tab",b)):fa(c,i.getContentsDiv()))}function g(){"object"===typeof k&&k.show();return!1}function q(){var b=Qa($a,Ra),c=M("expected_tab");if("undefined"===typeof b||0>b)b=5;i=new a;i.setBackgroundColor(bb).setPreviewMode(cb).setShowAttribution(db).setNoReturnExperience(eb).setNoReturnExperienceSwitchAccountLink(ub).setFontSize(fb).setFontFamily(gb).setFontColor(hb).setActionText(ib).setProviders(ma).setProvidersPerPage(jb).setBorderRadius(b).setButtonBorderColor(kb).setButtonBorderRadius(lb).setButtonBackgroundStyle(mb).build();
if("object"!==typeof k){k=new Db;k.ready=!1;var d=k.addContent;k.addContent=function(a){k.ready=!0;d(a);janrain.events.onModalWidgetReady.fire()}}k.setHeight(i.getActualHeight()).setWidth(i.getWidth()).setPreviewMode(cb).setBorderColor(Aa).setBorder(Ra).setBorderOpacity(Ba).setBorderRadius($a);ka||(c?(Q("welcome_info_name",unescape(M("welcome_info_name"))),ja("expected_tab",c)):k.addContent(i.getContentsDiv()));k.onOrientationChange.addHandler(function(a){"portrait"===a.orientation&&i.setFormat(a.format).setWidth(200).refresh({center:!0});
"landscape"===a.orientation&&i.setHeight(a.height).setWidth(a.width).setFormat(a.format).refresh({center:!0});k.setHeight(i.getActualHeight());k.setWidth(i.getWidth())});k.onShow.addHandler(function(){"object"==typeof i&&k.setWidth(i.getWidth())});k.onBorderWidthChange.addHandler(function(a){"object"===typeof k&&"object"===typeof i&&(i.setBorderRadius(a.radius).refresh(),a=i.getState(),a.borderRadius<a.modalState.borderRadius-a.modalState.borderWidth&&k.setBorderRadius(a.borderRadius+a.modalState.borderWidth))});
k.onBorderRadiusChange.addHandler(function(a){"object"===typeof i&&(i.setBorderRadius(a.radius).refresh(),a=i.getState(),a.borderRadius<a.modalState.borderRadius-a.modalState.borderWidth&&k.setBorderRadius(a.borderRadius+a.modalState.borderWidth))})}function h(a,b){if(!m("customizable_auth_widget_styling"))return!1;if("object"===typeof i)return b(a),!0}function N(a){return h(a,function(a){i.setBackgroundColor(a).refresh()})}function A(a){return h(a,function(a){i.setBorderRadius(a).refresh()})}function K(a){return h(a,
function(a){i.setBorderColor(a).refresh()})}function L(a){return"modal"===B?!1:h(a,function(a){i.setWidth(a).refresh({center:!0})})}function P(a){return h(a,function(a){i.setActionText(a).refresh()})}function $(a){return h(a,function(a){i.setButtonBorderColor(a).refresh()})}function ha(a){return h(a,function(a){i.setButtonBorderRadius(a).refresh()})}function V(a){return h(a,function(a){i.setButtonBackgroundStyle(a).refresh()})}function qa(a){return"modal"==B?!1:h(a,function(a){i.setFormat(a).refresh()})}
function j(a){return h(a,function(a){i.setProvidersPerPage(a).refresh()})}function ra(a){return h(a,function(a){i.setFontFamily(a).refresh()})}function ia(a){return h(a,function(a){i.setFontSize(a).refresh()})}function y(a){return h(a,function(a){i.setFontColor(a).refresh()})}function M(a){var b;if("single cookie"===la){b=T().getCookie("janrain_engage_login_data");if(!b)return;b=I.parse(b);return!b[a]?void 0:a=b[a]}if("default"===la)return a=T().getCookie(a),!a?void 0:a}function ya(a,b,c){var d;if(!a||
!b)return!1;c||(c=1);if("single cookie"===la)return(oldCookieJSON=T().getCookie("janrain_engage_login_data"))||(oldCookieJSON="{}"),c=I.parse(oldCookieJSON),c[a]=b,d=new T,d.setName("janrain_engage_login_data").setValue(I.stringify(c)).setExpiration(1826).create(),!0;return"default"===la?(d=new T,d.setName(a).setValue(b).setExpiration(c).create(),!0):!1}function za(a,b){if(eb)return!1;if("expected_tab"===a&&!b){var c=M("login_tab");c&&za("expected_tab",c);return!1}if(!b||"undefined"===b||"expected_tab"!==
a&&"expected_user_input"!==a&&"welcome_info_name"!==a)return!1;b="welcome_info_name"===a?escape(b):b;ya(a,b,1826)}function G(a,b){var c={};a||(a=vb);b||(b=vb.appUrl);if(f&&3>Ea)return c.widget_type=a.widget_type,c.provider=a.provider,c.time=(new Date).getTime(),c=qb(c),ga(b+"/signin/get_login_info"+c),Ea++,!0;"object"===typeof janrain.events.onProviderLoginCancel&&janrain.events.onProviderLoginCancel.fire(a);"undefined"!==typeof Ya&&clearTimeout(Ya);return!1}function Ua(a,b,c){var d=b.appUrl+"/"+
a.flow+"/start",e=window.location.href;b.mobileDevice&&(e="mobile");var f=b.language||"en",g=b.popup?"xdr":"xdrsw",i=b.tokenUrl||window.location.href,h={};vb={appUrl:b.appUrl,provider:a.name,widget_type:b.widgetType};h.language_preference=f;h.token_url=i;h.display="popup";h.widget=!0;"object"===typeof b.facebookPermissions&&(h.ext_perm=b.facebookPermissions.toString());h.openid_identifier=a.identifier;h.origin_url=e;h.provider_name=a.name;h.force_reauth=b.forceReauth;h.xdReceiver=b.appUrl+"/"+g;h.callback=
"none";h.widget_type=b.widgetType;h.token_action="url";if("event"===b.tokenAction||"hybrid"===b.tokenAction)h.token_action="event";b.mobileDevice&&"hybrid"===b.tokenAction&&(h.token_action="url");b.bpChannel&&(h.bpChannel=b.bpChannel);b.customOpenid&&"string"===typeof b.customOpenidOpxblob&&(h.opx_blob=b.customOpenidOpxblob);d+=qb(h);(function(){janrain.events.onProviderLoginStart.fire({provider:a.name,width:a.width,height:a.height});var e;b.mobileDevice&&"event"!==b.tokenAction||!b.popup?ga(b.appUrl+
"/signin/set_login_tab?login_tab="+a.name+"&origin_url="+encodeURIComponent(window.location.href),function(){window.top.location.href=d}):(e=new Lb(d),e.setWidth(a.width).setHeight(a.height).setCallback(function(){var d={},e="";d.widget_type=b.widgetType;d.provider=a.name||"";d.time=(new Date).getTime();e=qb(d);"function"===typeof c&&c();ga(b.appUrl+"/signin/get_login_info"+e);janrain.events.onProviderLoginComplete.fire({provider:a.name})}).show())})()}function Q(a,b){if(!b||"undefined"===b||"welcome_info_name"!==
a)return!1;b&&(R=b)}function ja(a,b){function c(){janrain.events.onReturnExperienceFound.fire({returnProvider:b,welcomeName:R})}var d=function(a){var c=function(){600>a&&setTimeout(function(){d(++a)},50)};if("object"!==typeof i)return c(),!1;"modal"===B?k.addContent(i.getReturnExperience(b,R)):"embed"===B&&fa(document.getElementById("janrainEngageEmbed"),i.getReturnExperience(b,R));"modal"===B&&janrain.events.onModalWidgetReady.fire()};if("expected_tab"!==a||!b)return!1;"object"===typeof i&&i.removeReturnExperience();
Ia?c():janrain.events.onAuthWidgetLoad.addHandler(c);d(0)}function fa(a,b){janrain.settings.capture&&(a?a.appendChild(b):(a=document.createElement("div"),a.id="janrainEngageEmbed",a.style.display="none",document.body.appendChild(a)));a?a.appendChild(b):o.log('Missing container div, please place this div where you want the embedded widget to be displayed on your page - <div id="janrainEngageEmbed"></div>.').show();return a}function aa(a,b){ea=ea||S;tokenUrl=b?ea:S;var c="";if(!pb(tokenUrl).query)var c=
c+"?",d=!0;for(var e in a)d?(c+=e+"="+a[e],d=!1):c+="&"+e+"="+a[e];ea=tokenUrl+c}function ba(){e=janrain.settings;if("en"!==janrain.settings.language&&"undefined"===typeof janrain.settings.translate)return setTimeout(ba,5),!1;Bb(xb()+"providers.css");f&&9>=f&&Bb(xb()+"providers-ie.css");if(e.stop)return!0;Ob&&ga(e.appUrl+"/signin/establish_session");va=e.tokenAction?e.tokenAction:va;if(!e.tokenUrl&&"event"===va)S=window.location.href;else if(e.tokenUrl)S=e.tokenUrl;else return o.log("Missing tokenUrl.  tokenUrl is required."),
o.show(),!1;B=r("string",["modal","embed"],"embed",e.type?e.type:B);ka=e.multi?e.multi:rb?!0:ka;ca=e.custom?e.custom:ca;Ja=e.forceReauth?e.forceReauth:Ja;Ka=e.bpChannel?e.bpChannel:Ka;da=e.facebookPermissions?e.facebookPermissions:da;la=e.storageType?r("string",["default","single cookie"],"default",e.storageType):la;Sa="boolean"===typeof e.popup?e.popup:Sa;rb&&"event"!==va&&(Sa=!1);Y=e.returnExperienceTimeout?e.returnExperienceTimeout:Y;ka&&(setTimeout(function(){var a=M("expected_tab");a?(Q("welcome_info_name",
unescape(M("welcome_info_name"))),ja("expected_tab",a)):"modal"===B?k.addContent(i.getContentsDiv()):"embed"===B&&(a=document.getElementById("janrainEngageEmbed"),fa(a,i.getContentsDiv()))},Y),ga(e.appUrl+"/signin/get_cookies"));if(e.customOpenid&&m("customizable_auth_widget_styling")){Ta=!0;if(!e.customOpenidFlow)return o.log("Missing customOpenidFlow. customOpenidFlow is required when adding a custom openid provider."),o.show(),!1;if(!e.customOpenidIdentifier)return o.log("Missing customOpenidIdentifier. customOpenidIdentifier is required when adding a custom openid provider."),
o.show(),!1;Xa.customopenid={flow:e.customOpenidFlow,identifier:e.customOpenidIdentifier,width:e.customOpenidModalWidth||800,height:e.customOpenidModalHeight||600}}if(ca)return!0;va=e.tokenAction?e.tokenAction:va;Ra=m("customizable_auth_widget_styling")?e.modalBorderWidth:Ra;Aa=m("customizable_auth_widget_styling")?e.modalBorderColor:Aa;$a=m("customizable_auth_widget_styling")?e.modalBorderRadius:$a;Ba=m("customizable_auth_widget_styling")?e.modalBorderOpacity:Ba;bb=m("customizable_auth_widget_styling")?
e.backgroundColor:bb;Ca=m("customizable_auth_widget_styling")?e.borderRadius:Ca;Z=m("customizable_auth_widget_styling")?e.borderColor:Z;ua=m("customizable_auth_widget_styling")?e.format:ua;hb=m("customizable_auth_widget_styling")?e.fontColor:hb;fb=m("customizable_auth_widget_styling")?e.fontSize:fb;gb=m("customizable_auth_widget_styling")?e.fontFamily:gb;U=m("customizable_auth_widget_styling")?e.width:U;X=m("customizable_auth_widget_styling")?e.rowHeight:X;jb=m("customizable_auth_widget_styling")?
e.providersPerPage:jb;tb=m("customizable_auth_widget_styling")?e.providersNotPaged:tb;ib=m("customizable_auth_widget_styling")?e.actionText:ib;kb=m("customizable_auth_widget_styling")?e.buttonBorderColor:kb;lb=m("customizable_auth_widget_styling")?e.buttonBorderRadius:lb;mb=m("customizable_auth_widget_styling")?e.buttonBackgroundStyle:mb;db=m("customizable_auth_widget_hide_attribution")?e.showAttribution:db;cb=e.previewMode;eb=e.noReturnExperience;ub=e.noReturnExperienceSwitchAccountLink;ma=e.providers;
"undefined"===typeof janrain.settings.translate&&(janrain.settings.translate=e.translate={});if(e.customOpenid&&m("customizable_auth_widget_styling")){if(!e.customOpenidSmallLogo)return o.log("Missing customOpenidSmallLogo.  customOpenidSmallLogo is required and should be the full path to an image that has a width of 90px and height of 30px."),o.show(),!1;if(!e.customOpenidSmallIcon)return o.log("Missing customOpenidSmallIcon.  customOpenidSmallIcon is required and should be the full path to an image that is 30px x 30px."),
o.show(),!1;if(!e.customOpenidLargeLogo)return o.log("Missing customOpenidLargeLogo.  customOpenidLargeLogo is required and should be the full path to an image that has a width of 150px and height of 50px."),o.show(),!1;if(!e.customOpenidLargeIcon)return o.log("Missing customOpenidLargeIcon.  customOpenidLargeIcon is required and should be the full path to an image that is 50px x 50px."),o.show(),!1;xa={smallLogo:e.customOpenidSmallLogo,smallIcon:e.customOpenidSmallIcon,largeLogo:e.customOpenidLargeLogo,
largeIcon:e.customOpenidLargeIcon}}e.previewMode?("modal"===B&&(janrain.ready?d():W(window,"load",d)),"embed"===B&&(janrain.ready?c():W(window,"load",c))):("modal"===B&&(janrain.ready?b():W(window,"load",b)),"embed"===B&&(janrain.ready?E():W(window,"load",E)))}var da,Ka,Ta=!1,Ja=!1,va="url",S,ea,B="embed",R="unknown",ka=!1,Y=300,Ja=!1,Sa=!0,ca=!1,la="default",xa,wa,k,Ra,Aa,$a,Ba,i,J,bb,Ca,Z,U,X,ua,ma=[],tb=!1,jb,ib,fb,gb,hb,kb,lb,mb,cb,eb,ub,db,Wa=!1,Ia=!1;janrain.events.onAuthWidgetLoad||(janrain.events.onAuthWidgetLoad=
D());janrain.events.onModalWidgetReady||(janrain.events.onModalWidgetReady=D());janrain.events.onReturnExperienceFound||(janrain.events.onReturnExperienceFound=D());janrain.events.onAuthWidgetLoad.addHandler(function(){Ia=!0});janrain.events.onAuthWidgetLoad.addHandler(function(){"function"===typeof janrainWidgetOnload&&(ca?janrainWidgetOnload():i?janrainWidgetOnload(i.getState()):janrainWidgetOnload())});for(var Ya,Ea=0,vb,wb="onProviderLoginStart,onProviderLoginError,onProviderLoginToken,onProviderLoginCancel,onProviderLoginSuccess,onProviderLoginComplete,onProviderLogoutStart,onProviderLogoutComplete".split(","),
nb=0;nb<wb.length;nb++)"undefined"===typeof janrain.events[wb[nb]]&&(janrain.events[wb[nb]]=new ta);janrain.events.onProviderLoginError.addHandler(function(a){if(ca)return!0;var b=M("login_tab");if("modal"===B){var c=document.getElementById("janrainModal");c&&c.appendChild(i.getErrorPage(b,a.err))}"embed"===B&&(c=document.getElementById("janrainEngageEmbed"))&&fa(c,i.getErrorPage(b,a.err))});ba();return{appendTokenParams:function(a,b){aa(a,b)},appendTokenParamsCumulative:function(a){aa(a,!0)},setBackplaneChannel:function(a){Ka=
a},setLoginCookie:function(a,b){za(a,b)},loginHandler:function(a){var b=va;a?("ok"===a.stat&&("event"===b||"hybrid"===b?ga(a.redirectUrl):(b=document.createElement("form"),b.action=a.redirectUrl,b.method="POST",janrain.settings.targetTop&&(b.target="_top"),document.body.appendChild(b),b.submit())),"fail"===a.stat&&(janrain.events.onProviderLoginError.fire(a),"undefined"!==typeof Ya&&clearTimeout(Ya))):G()},cancelLogin:function(a){G(a,e.appUrl);ca||i.removeNotice()},removeNotice:function(){i.removeNotice()},
setWelcomeInfoName:function(a,b){Q(a,b)},setReturnExperience:function(a,b){ja(a,b)},setNoReturnExperience:function(a,b){var c;"boolean"===typeof a&&i?(i.setNoReturnExperience(a),b||i.refresh(),c=!0):c=!1;return c},setNoReturnExperienceSwitchAccountLink:function(a){"boolean"===typeof a&&i?(i.setNoReturnExperienceSwitchAccountLink(a).refresh(),a=!0):a=!1;return a},setPreviewMode:function(a){"boolean"===typeof a&&i?(i.setPreviewMode(a).refresh(),a=!0):a=!1;return a},setConfigureMode:function(a){"boolean"===
typeof a&&i?(i.setConfigureMode(a).refresh(),a=!0):a=!1;return a},setCustom:function(a){ca=a},getState:function(){return"object"===typeof i?i.getState():!1},setProviderFlow:function(b,c){var d;d=!m("customizable_auth_widget_styling")||!ca?!1:a().setProviderFlow(b,c);return d},triggerFlow:function(b){b=!m("customizable_auth_widget_styling")||!ca?!1:a().triggerFlow(b);return b},debugDump:function(){if("undefined"!==typeof console){console.log("-------------START---------------");null!==document.doctype?
(console.log("DOCTYPE Name: "+document.doctype.name),console.log("DOCTYPE NodeType: "+document.doctype.nodeType)):console.log("DOCTYPE name: not available (probably quirks mode)");console.log("User Agent: "+navigator.userAgent);console.log("App Version: "+navigator.appVersion);console.log("Platform: "+navigator.platform);console.log("OS CPU: "+navigator.oscpu);console.log("Language: "+navigator.language);console.log("Release: ");console.log("Web Address: "+location.href);console.log("Cookies Enabled: "+
navigator.cookieEnabled);console.log("COOKIES::: "+document.cookie);console.log("AUTH SETTINGS:::");for(var a in janrain.settings)if(console.log(" ---- "+a+": "+janrain.settings[a]),"object"===typeof janrain.settings[a])for(var b in janrain.settings[a])"function"!==typeof janrain.settings[a][b]&&console.log(" --- --- "+b+": "+janrain.settings[a][b]);console.log("-------------END---------------")}},version:"not sure",widget:{init:function(){c()},setBackgroundColor:function(a){return N(a)},setBorderColor:function(a){return K(a)},
setBorderRadius:function(a){return A(a)},setWidth:function(a){return L(a)},setActionText:function(a){return P(a)},setFontFamily:function(a){return ra(a)},setFontSize:function(a){return ia(a)},setFontColor:function(a){return y(a)},setFormat:function(a){return qa(a)},setButtonBorderColor:function(a){return $(a)},setButtonBorderRadius:function(a){return ha(a)},setButtonBackgroundStyle:function(a){return V(a)},setProviders:function(a){var b;"object"===typeof i&&(u?i.setProviders(a):i.setProviders(a).refresh(),
b=!0);return b},setProvidersPerPage:function(a){return j(a)},setShowAttribution:function(a){var b;m("customizable_auth_widget_hide_attribution")?"object"===typeof i&&i.setShowAttribution(a).refresh():b=!1;return b},refresh:function(){return i.refresh()},getWidth:function(){return i.getWidth()}},modal:{init:function(){d()},close:function(){"object"==typeof k&&k.close()},create:function(){return new Db},setBorder:function(a){m("customizable_auth_widget_styling")?("object"===typeof k&&(k.setBorder(a),
k.refresh({center:!0})),a=!0):a=!1;return a},setBorderColor:function(a){m("customizable_auth_widget_styling")?("object"===typeof k&&(k.setBorderColor(a),k.refresh()),a=!0):a=!1;return a},setBorderOpacity:function(a){m("customizable_auth_widget_styling")?("object"===typeof k&&(k.setBorderOpacity(a),k.refresh()),a=!0):a=!1;return a},setBorderRadius:function(a){m("customizable_auth_widget_styling")?("object"==typeof k&&(k.setBorderRadius(a),k.refresh()),a=!0):a=!1;return a}}}};var N=new function(){return{status:"not loaded"}},
Ka=new function(){return{status:"not loaded"}},Ta=new function(){return{status:"not loaded"}},Qb=new function(){return{status:"not loaded"}};return{engage:{signin:janrain&&janrain.engage&&janrain.engage.signin?janrain.engage.signin:Ua,share:janrain&&janrain.engage&&janrain.engage.share?janrain.engage.share:N,publish:janrain&&janrain.engage&&janrain.engage.publish?janrain.engage.publish:Ka,simpleshare:janrain&&janrain.engage&&janrain.engage.simpleshare?janrain.engage.simpleshare:Ta},capture:{ui:Qb}}}();
janrain.engage=janrain.apps.engage;janrain.capture=janrain.apps.capture;