/*
 -*- Engage Auth Widget -*-
 Copyright (c) 2012, Janrain, Inc. All rights reserved.
 Version: 2012.48
*/
"object"!==typeof window.janrain&&(window.janrain={});janrain.apps={};
janrain.apps=function(){var Aa,Ba,ra,sa;function zb(){return"http:"===document.location.protocol?"http://cdn.quilt.janrain.com/2.1.3/":"https://d3hmp0045zy3cs.cloudfront.net/2.1.3/"}function Ib(a,d,c){var b;if(document.getElementById(a))return!1;if(f){b="";var G=document.createElement("div");G.innerHTML=b+"<iframe "+('name="'+a+'" ')+('id="'+a+'" ')+('src="'+d+'" ')+'style="display: none;"></iframe>';document.body&&document.body.appendChild(G)}else b=document.createElement("iframe"),b.setAttribute("name",
a),b.id=a,b.setAttribute("src",d),b.style.display="none",b.className="",document.body&&document.body.appendChild(b);"function"===typeof c&&c()}function Ca(a){for(var d="",d="",c=0;c<a;c++)d+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));return d}function Da(){function a(a,b,c,d){b={action:a,key:b,messageId:c};"set"===a&&(b.value=d);return"janrainCapture:"+M.stringify(b)}function d(a,b){function c(){d++;if(10<d)return!1;if("undefined"!==typeof e[a])return clearTimeout(g),
"get"===e[a].action&&"function"===typeof b&&b(e[a].storedValue),!0;var g=setTimeout(c,50)}var d=0;c()}function c(b,c){var g=Ca(40);window.setTimeout(function(){f.contentWindow.postMessage(a("get",b,g),ba)});d(g,c)}function b(a,d){if(g)Za?c(a,d):setTimeout(function(){b(a,d)},50);else return window.localStorage.getItem(a)}function G(a){var b;if(!(b=0!==a.data.indexOf("janrainCapture:"))){b=C;var c=a.origin.replace(/^https?:\/\/|:\d{1,4}$/g,"").toLowerCase();b=!(!ua(b)?0:-1<b.indexOf(c))}if(b)return!1;
a=M.parse(a.data.replace("janrainCapture:",""));e[a.messageId]=a}var g=!1,e={},f,ba,C=janrain.settings&&janrain.settings.whiteListedDomains?janrain.settings.whiteListedDomains:[];return{setItem:function(b,c){if(g){var G=Ca(40);window.setTimeout(function(){f.contentWindow.postMessage(a("set",b,G,c),ba)});return d(G)}return window.localStorage.setItem(b,c)},removeItem:function(b){if(g){var c=Ca(40);window.setTimeout(function(){f.contentWindow.postMessage(a("remove",b,c),ba)});return d(c)}return window.localStorage.removeItem(b)},
getItem:b,setMultiDomain:function(a){if(g=a)window.addEventListener?window.addEventListener("message",G,!1):window.attachEvent?window.attachEvent("onmessage",G):document.attachEvent&&document.attachEvent("onmessage",G),f=document.getElementById("xDomainLocalStorageJanrain"),ba=janrain.settings.storageServerDomain}}}function N(){function a(){if(G&&va){var a=new Da;a.setMultiDomain(janrain.settings.multiDomainLocalStorage);a.removeItem(b);a.removeItem(b+"_Expires")}else{var a=e?"; domain="+e:"",c=new Date;
c.setTime(c.getTime()+-864E6);document.cookie=b+"="+g+";expires="+c.toUTCString()+a+"; path="+f}}function d(c,d){var g,e,f,E,o;if(G&&va)if(o=new Da,janrain.settings.multiDomainLocalStorage)o.setMultiDomain(!0),o.getItem(c,function(g){g?o.getItem(c+"_Expires",function(e){e?Math.round((new Date).getTime()/1E3)>Math.round((new Date(e)).getTime()/1E3)?(b=c,a(),"function"===typeof d&&d(!1)):"function"===typeof d&&d(g):(new N).getCookie(c+"_session")?"function"===typeof d&&d(g):(b=c,a())}):"function"===
typeof d&&d(!1)});else if(E=o.getItem(c),g=o.getItem(c+"_Expires"),E){if(!(g&&Math.round((new Date).getTime()/1E3)>Math.round((new Date(g)).getTime()/1E3))&&(g||(new N).getCookie(c+"_session")))return E;b=c;a()}else return!1;else{g=document.cookie.split(";");e=g.length;for(var R=0;R<e;R++)if(f=g.pop(),E=f.split("="),f=E[0],E=E[1],f.trim()===c)return E;return!1}}var c,b,G=!1,g,e,f="/";return{create:function(){if(G&&va){var a=new Da;a.setMultiDomain(janrain.settings.multiDomainLocalStorage);a.setItem(b,
g);c?a.setItem(b+"_Expires",c):(new N).setName(b+"_session").setValue("session").create()}else document.cookie=b+"="+g+(c?"; expires="+c:"")+(e?"; domain="+e:"")+"; path="+f},remove:a,setExpirationDirectly:function(a){a&&(c=a);return this},setExpiration:function(a){if(a){var b=new Date;b.setTime(b.getTime()+864E5*a);c=b.toUTCString()}return this},setName:function(a){a&&(b=a);return this},setValue:function(a){"undefined"!==typeof a&&(g=a);return this},setUseLocalStorage:function(a){G=a;return this},
setPath:function(a){a&&(f=a);return this},setDomain:function(a){a&&(e=a);return this},getCookie:function(a,b){return d(a,b)}}}function ab(){return"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(P)?parseFloat(RegExp.$1):!1}function Na(){return!/Chrome\//.test(P)&&/Safari\//.test(P)}function I(a,d,c,b,e,g){"number"===typeof c&&"number"===typeof b&&"number"===typeof e&&"number"===typeof g?("undefined"!==typeof a.style.borderRadius&&(a.style.borderRadius=c+"px "+
b+"px "+e+"px "+g+"px"),"undefined"!==typeof a.style.MozBorderRadius&&(a.style.MozBorderRadius=c+"px "+b+"px "+e+"px "+g+"px"),"undefined"!==typeof a.style.webkitBorderRadius&&(a.style.webkitBorderRadius=c+"px "+b+"px "+e+"px "+g+"px")):("undefined"!==typeof a.style.borderRadius&&(a.style.borderRadius=d+"px"),"undefined"!==typeof a.style.MozBorderRadius&&(a.style.MozBorderRadius=d+"px"),"undefined"!==typeof a.style.webkitBorderRadius&&(a.style.webkitBorderRadius=d+"px"));return a}function Ua(a,d){if("undefined"===
typeof a||"undefined"===typeof d)return!1;var c=a-d;0>c&&(c=0);c>a&&(c=a);return c}function Ab(a,d){if(f&&9>=f)return a.style.backgroundImage="url('"+sb("rel/img/c7a91677d94f4a79e1b26c8ceb31af82.png")+"')",!0;var c;if(c=Na()){a:{if(P&&(c=P.match(/(\d)[\d.]+ Safari/))&&c[1]){c=1*c[1];break a}c=0}c=4>=c}if(c||U.getMobileDevice()){var b=c="",e="",g=d.split(","),E={top:"left top, left bottom",right:"right top, right bottom",bottom:"left bottom, left top",left:"left top, left bottom"};g[0]&&E[g[0]]&&(c=
E[g[0]]);g[1]&&(b="from("+g[1]+")");g[g.length-1]&&(e="to("+g[g.length-1]+")");a.style.backgroundImage="-webkit-gradient(linear,"+c+","+b+","+e+")"}a.style.backgroundImage="-moz-linear-gradient("+d+")";a.style.backgroundImage="-webkit-linear-gradient("+d+")";a.style.backgroundImage="-ms-linear-gradient("+d+")";a.style.backgroundImage="-o-linear-gradient("+d+")";a.style.backgroundImage="linear-gradient("+d+")"}function ca(a,d,c,b){var e=Oa(c),g=Oa(c,b);if(c=Kb(c))c.a=b,g="rgba("+c.r+", "+c.g+", "+
c.b+", "+c.a+")";if(0<d){a.style.backgroundColor=e;a.style.padding=d+"px";if(0<f&&8>=f||f&&u)return!1;a.style.backgroundColor=g;a.style.padding=d+"px"}else a.style.backgroundColor="",a.style.padding="0px"}function Kb(a){var d={};if("string"!==typeof a||!a)return!1;a=a.replace(/\s+/g,"");a=a.replace(/,{2,}/g,",");a=a.replace(/[^\d.,]/g,"");a=a.split(",");if(3>a.length||4<a.length)return!1;d.r=a[0];d.g=a[1];d.b=a[2];d.a=a[3]?a[3]:1;return d}function Oa(a,d){var c=a.split("");if("#"!==c[0])return a;
4===a.length&&(a=c[0]+c[1]+c[1]+c[2]+c[2]+c[3]+c[3]);var a=a.substring(1,7),c=parseInt(a.substring(0,2),16),b=parseInt(a.substring(2,4),16),e=parseInt(a.substring(4,6),16);return isNaN(d)?"rgb("+c+","+b+","+e+")":"rgba("+c+","+b+","+e+","+d+")"}function V(a,d,c){if(null==a)return!1;"object"===typeof window.attachEvent?a.attachEvent("on"+d,c):a.addEventListener(d,c,!1)}function Bb(a,d,c){"object"===typeof window.detachEvent?a.detachEvent("on"+d,c):a.removeEventListener(d,c,!1)}function Cb(){var a,
d,c,b,e,g,E,f;d=document.documentElement?document.documentElement:{clientWidth:0,clientHeight:0,scrollWidth:0,scrollHeight:0,offsetWidth:0,offsetHeight:0};E=d.scrollWidth?d.scrollWidth:0;f=d.scrollHeight?d.scrollHeight:0;e=d.offsetWidth?d.offsetWidth:0;g=d.offsetHeight?d.offsetHeight:0;c=document.body.scrollWidth?document.body.scrollWidth:0;b=document.body.scrollHeight?document.body.scrollHeight:0;a=document.body.offsetWidth?document.body.offsetWidth:0;d=document.body.offsetHeight?document.body.offsetHeight:
0;e=Math.max(c,E,a,e);return{height:Math.max(b,f,d,g),width:e}}function r(a,d,c,b,e){var g=/^(?:[^\u0000-\u0080]|[-0-9a-z?,.!&\s#()])+$/i,f=/(?:^rgb\s*\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*\)$)|(?:^#[a-f0-9]{1,6}$)/i;if("array"===a){if(!ua(b))return e||p.log(b+" is wrong type, must be array, using default value instead"),c;if(d&&ua(d))for(var o=0;o<b.length;o++)if(0>d.indexOf(b[o]))return e||p.log(b+" is not within the valid range, using default value instead"),c;return b}if("url"===a){if("string"!==typeof b)return c;
b&&(b=b.trim());if(/^http(?:s)?:\/\/[-a-z0-9._~@:!$&'()*+,;=\s/?#]+$/i.test(b))return b;e||p.log(b+" is not the valid format, using default value instead");return c}if("text"===a){if(d){if(0<=d.indexOf(b))return b;e||p.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+c+'" instead');return c}return g.test(b)?b:c}if("usertext"===a){if("string"!==typeof b&&"number"!==typeof b)return c;if(ua(d)){if(1===d.length){if(b.length<=d[0])return b;e||p.log(b+
" is too long, using default value instead");return c}if(2===d.length){if(b.length<=d[1]&&b.length>=d[0])return b;e||p.log(b+" is not within the valid range, using default value instead");return c}e||p.log("usertext range is invalid, using default value instead");return c}return b}"string"===typeof b&&0==b.length&&(b=" ");if(!g.test(b))return e||p.log(b+" contains invalid character(s)"),c;if("boolean"===a){if("boolean"===typeof b)return b;e||p.log(b+" is wrong type, must be boolean, using default value instead");
return c}if("text"===a)return b;if("number"===a){if(isNaN(parseInt(b)))return e||p.log(b+" is wrong type, must be a valid number"),c;b=parseFloat(b)}if("color"===a){b&&(b=b.trim());if("transparent"===b||f.test(b))return b;e||p.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+c+'" instead');return c}if(typeof b!=a&&"color"!=a)return e||p.log(b+" for "+arguments.callee.caller.name+" is "+typeof b+" expected "+a),c;if("object"===typeof d&&"string"===
a){if(0<=d.indexOf(b))return b;e||p.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+c+'" instead');return c}if("object"===typeof d&&"number"===a){2===d.length?(g=d[0],f=d[1]):(g=d.shift(),f=d.pop(),o=d);if(b<g)return e||p.log("Value of "+b+" for "+arguments.callee.caller.name+" is below minimum of "+g+", using minimum value of "+g+" instead"),g;if(b>f)return e||p.log("Value of "+b+" for "+arguments.callee.caller.name+" is above maximum of "+
f+", using maximum value of "+f+" instead"),f;if(o&&"number"===typeof o.indexOf(b)||b==g||b==f)return b;return o?(e||p.log("Value of "+b+" for "+arguments.callee.caller.name+" is not a valid value, using default value of "+c+" instead"),c):b}return 0!=b&&!b?c:b}function bb(a){for(var d=bb.options,a=d.parser[d.strictMode?"strict":"loose"].exec(a),c={},b=14;b--;)c[d.key[b]]=a[b]||"";c[d.q.name]={};c[d.key[12]].replace(d.q.parser,function(a,b,e){b&&(c[d.q.name][b]=e)});return c}function Lb(a,d){function c(a){p=
!0;"undefined"!==typeof C&&clearTimeout(C);if("string"===typeof a)return"function"===typeof o&&o(a),!0;if("object"===typeof a||"undefined"===typeof a)return"object"===typeof a&&"error"===a.type?"function"===typeof o&&o(a):"function"===typeof e&&e(),!0}function b(){l++;if(p)return!0;l<g?C=setTimeout(b,50):c("Load Timeout Error")}var e=d,g=200,f=!1,o,l=0,C,L=document.createElement("script"),H=document.getElementsByTagName("script")[0],p=!1;L.src=a;L.setAttribute("type","text/javascript");L.onload=L.onerror=
L.onreadystatechange=function(a){!p&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)&&c(a)};return{setTimeoutCallback:function(a){f=!0;o=a;return this},setCallback:function(a){e=a;return this},setTimeoutLimit:function(a){g=a;return this},load:function(){H.parentNode.insertBefore(L,H);f&&b()}}}function ia(a,d){Lb(a,d).load()}function Db(a,d){function c(b){o=!1;"function"===typeof d&&d();janrain.events.onCssLoad.fire({source:a,noload:b})}function b(){if(o){for(C=l.length;0<=
--C;)if(l[C].href===g.href){c();break}f+=1;o&&(200>f?setTimeout(b,50):c(!0))}}function e(){var a;try{a=!!g.sheet.cssRules}catch(b){f+=1;200>f?setTimeout(e,50):a&&c(!0);return}c()}if(!(!ua(W)?0:-1<W.indexOf(a))){W.push(a);var g,f=0,o=!0,l=document.styleSheets,C;"undefined"===typeof janrain.events.onCssLoad&&(janrain.events.onCssLoad=new Fa);wa?(g=document.createElement("style"),g.innerHTML='@import "'+a+'";'):(g=document.createElement("link"),g.rel="stylesheet",g.href=a,g.type="text/css");Eb||wa?(Eb&&
b(),wa&&e()):(g.onload=function(){c()},g.onerror=function(){c(!0)});document.getElementsByTagName("head")[0].appendChild(g)}}function ua(a){return"[object Array]"===Object.prototype.toString.call(a)}function tb(a){var d="",c;for(c in a)d+="&"+encodeURIComponent(c)+"="+encodeURIComponent(a[c]);return d="?"+d.substr(1)}function ja(a){if(!a)return!1;if(a.preventDefault)a.preventDefault();else try{a.returnValue=!1}catch(d){}}function da(a){if(!a)return!1;a.stopPropagation?a.stopPropagation():a.cancelBubble=
!0}function Fb(){function a(a){var a=a||"img",c=document.createElement(a);c.style.position="absolute";c.style.cursor="pointer";c.style.zIndex=1E3;"a"===a?(c.setAttribute("href","#"),c.className="janrain_modal_closebutton",N&&(c.innerHTML=N)):(c.src=O,P||(c.style.right="-6px",c.style.top="-7px",c.style.height="31px",c.style.width="28px"));c.onclick=M?b:d;return c}function d(a){ka||(i.style.display="none",xa.style.display="none",v.style.display="none");S&&U.deactivate();("object"===typeof a||!a)&&janrain.events.onModalClose.fire();
("object"===typeof a||!a)&&Q.fire();"object"===typeof a&&ja(a)}function c(){var a=document.createElement("div"),c=document.createElement("div"),b=document.createElement("a"),e=document.createElement("a"),g=document.createElement("h3");b.innerHTML=ya;e.innerHTML=Ha;g.innerHTML=La;b.setAttribute("href","#");e.setAttribute("href","#");a.className="janrain_close_confirm_container";c.className="janrain_close_confirm";b.className="janrain_modal_confirm";e.className="janrain_modal_cancel";V(b,"click",function(a){d();
i.removeChild(ea);ea=null;ja(a)});V(e,"click",function(a){i.removeChild(ea);ea=null;ja(a)});c.appendChild(g);c.appendChild(e);c.appendChild(b);a.appendChild(c);return a}function b(a){ea||(ea=c(),i.appendChild(ea));ja(a)}function e(a){var c,b,d=document.documentElement.scrollTop>=document.body.scrollTop?document.documentElement.scrollTop:document.body.scrollTop,g=document.documentElement.scrollLeft>=document.body.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft;"undefined"!=
typeof window.innerWidth?(c=window.innerWidth,b=window.innerHeight):(c=document.documentElement.offsetWidth,b=document.documentElement.offsetHeight);var f=a.style&&a.style.width?parseInt(a.style.width):a.offsetWidth?parseInt(a.offsetWidth):0,i=a.style&&a.style.height?parseInt(a.style.height):a.offsetHeight?parseInt(a.offsetHeight):0;b-=i;c-=f;d+=b/2;g+=c/2;0>b&&(document.documentElement.scrollTop=0,document.body.scrollTop=0,d=10);0>c&&(document.documentElement.scrollLeft=0,g=document.body.scrollLeft=
0);a.style.top=d+"px";a.style.left=g+"px";"absolute"!==a.style.position&&(a.style.position="absolute")}function g(){if(ka){var a=document.getElementById("previewMode");a.style.position="relative";a.appendChild(i)}else e(i);ka||p.show()}function E(a){X||(T=r("number",[0,20],10,a),za.fire({radius:Ua(Y,T)}))}function o(a){X||(Z=r("color",null,"#000000",a))}function ba(a){X||(Y=r("number",[0,20],10,a),k.fire({radius:Ua(Y,T),refresh:!0}))}function C(a){X||($=r("number",[0,1],0.5,a),"object"==typeof i&&
ca(i,T,Z,$))}function L(a){if("portrait"===a){A="portrait";var c="one column"}"landscape"===a&&(A="landscape",c="two column");ia.fire({orientation:A,format:c,width:Ta,height:z});setTimeout(Ea,100);g()}function H(a){a&&(aa=a);f&&u&&(aa+=T-2);"object"==typeof i&&(i.style.width=aa+"px");return this}function Jb(a){a&&(t=a);f&&u&&(t=t+2*T-4);a&&"object"==typeof i&&(i.style.height=t+"px");return this}function ta(){ra>=sa&&"undefined"===typeof window.orientation?"landscape"!==A&&L("landscape"):90===window.orientation||
-90===window.orientation?"landscape"!==A&&L("landscape"):"portrait"!==A&&L("portrait");g()}function Ea(){var a=Cb();v.style.height=a.height+"px";v.style.width=a.width+"px"}function R(){return"object"===typeof i&&"none"!==i.style.display}var Ta=380,z=131,i,Gb="janrainModal",xa,v,Ga,aa=Ta,t=z,T=10,Z="#000000",Y=10,$=0.5,M=!1,O=sb("rel/img/b573cd6e318034fa17bb7e9690552ca1.png"),N="",X=janrain.settings&&janrain.settings.capture&&janrain.settings.capture.noModalBorderInlineCss,P=!1,La="Are you sure you want to quit?",
ya="Yes, quit",Ha="No, stay",ea,A="landscape",la=!0,S="boolean"===typeof S?S:"number"===typeof window.orientation?!0:!1,ma="boolean"===typeof ma?ma:janrain.settings.previewMode,ka=ma,fa=fa||!1,ga=!1;janrain.settings&&janrain.settings.capture&&janrain.settings.capture.modalCloseImage&&(O=janrain.settings.capture.modalCloseImage,P=!0);janrain.settings&&janrain.settings.capture&&janrain.settings.capture.modalCloseHtml&&(N=janrain.settings.capture.modalCloseHtml);window.janrain.events.onModalClose||(window.janrain.events.onModalClose=
D());window.janrain.events.onModalOpen||(window.janrain.events.onModalOpen=D());var Q=D(),ha=D(),k=D(),za=D(),ia=D();U&&U.onOrientationChange&&U.onViewportChange&&(U.onOrientationChange.addHandler(function(a){L(a.orientation)}),U.onViewportChange.addHandler(function(){e(i)}));"undefined"!==typeof janrain.events.onCaptureRenderComplete&&(janrain.events.onCaptureRenderComplete.addHandler(function(){R()&&(ga=!0)}),janrain.events.onCaptureContentChange.addHandler(function(){R()&&ga&&(g(),setTimeout(Ea,
500),ga=!1)}));return{isOpen:function(){return R()},setWidth:function(a){H(a);return this},setHeight:function(a){Jb(a);return this},setBorder:function(a){("string"==typeof a||"number"==typeof a)&&E(a);X||"object"==typeof i&&ca(i,T,Z,$);return this},setBorderColor:function(a){a&&o(a);X||"object"==typeof i&&ca(i,T,Z,$);return this},setBorderRadius:function(a){("string"==typeof a||"number"==typeof a)&&ba(a);X||"object"==typeof i&&I(i,Y);return this},setBorderOpacity:function(a){("number"===typeof a||
"string"===typeof a)&&C(a);return this},setZIndex:function(a){v.style.zIndex=a},setPreviewMode:function(a){"boolean"===typeof a&&(ka=a);return this},setId:function(a){Gb=a;i&&(i.id=a);return this},show:function(){S||(i.style.display="block");"object"==typeof xa&&la&&(xa.style.display="block");ka?S&&(i.style.display="block"):(v.style.display="block",S?(U.setElement(i).activate(),i.style.display="block"):(V(window,"resize",ta),V(window,"resize",Ea),ta(),Ea()));X||k.fire({radius:Ua(Y,T),refresh:!1});
ha.fire();janrain.events.onModalOpen.fire();i.focus()},close:function(a){d(a)},closeConfirm:function(){b()},refresh:function(a){fa||i.appendChild(Ga);a&&a.center&&g()},remove:function(){if(ka){var a=document.getElementById("previewMode");"object"===typeof Ga&&i.removeChild(Ga);"object"===typeof i&&a.removeChild(i);"object"===typeof v&&document.body.removeChild(v);if(a=document.getElementById("janrainEngageEmbed_old"))a.id="janrainEngageEmbed";v=i=""}else"object"===typeof Ga&&i.removeChild(Ga),"object"===
typeof v&&document.body.removeChild(v),"object"===typeof i&&document.body.removeChild(i)},addContent:function(c){janrain.events.onAuthWidgetContentPlaced.fire();xa=c;if(!i){i=document.createElement("div");i.id=Gb;if("number"===typeof aa||"string"===typeof aa)i.style.width=aa+"px";i.style.height=t+"px";i.style.position="absolute";X||(i.style.padding=T+"px",I(i,Y),ca(i,T,Z,$));i.style.zIndex=1E3;i.style.display="none";c=Cb();v=document.createElement("div");janrain.settings&&janrain.settings.capture&&
janrain.settings.capture.captureServer&&(v.id="janrainModalOverlay");v.style.width=c.width+"px";v.style.height=c.height+"px";v.style.left=0;v.style.top=0;v.style.backgroundColor="#000000";v.style.position="absolute";c=v;"undefined"!==typeof c.style.filter&&(c.style.filter="alpha(opacity=40)");"undefined"!==typeof c.style.opacity&&(c.style.opacity="0.4");"undefined"!==typeof c.style.KhtmlOpacity&&(c.style.KhtmlOpacity="0.4");"undefined"!==typeof c.style.MozOpacity&&(c.style.MozOpacity="0.4");v.style.display=
"none";v.style.zIndex=1E3;Ga=N?a("a"):a();i.appendChild(Ga);document.body.appendChild(v);document.body.appendChild(i)}i.appendChild(xa);setTimeout(Ea,500);ka&&g();return this},getContent:function(){return xa},getBorderWidth:function(){return T},getState:function(){return{width:aa,borderWidth:T,borderColor:Z,borderRadius:Y,borderOpacity:$,orientation:A}},setState:function(a){l("customizable_auth_widget_styling")&&("undefined"!==typeof a.borderWidth&&E(a.borderWidth),"undefined"!==typeof a.borderColor&&
o(a.borderColor),"undefined"!==typeof a.borderOpacity&&C(a.borderOpacity),"undefined"!==typeof a.orientation&&L(a.orientation),"undefined"!==typeof a.borderRadius&&(("string"==typeof a.borderRadius||"number"==typeof a.borderRadius)&&ba(a.borderRadius),"object"==typeof i&&I(i,Y)))},setConfirmClose:function(a){M=a;return this},setShowContentOnLoad:function(a){la=a;return this},setConfirmMessageText:function(a){La=a},setConfirmLinkText:function(a){ya=a},setCancelLinkText:function(a){Ha=a},onClose:Q,
onShow:ha,onOrientationChange:ia,onBorderRadiusChange:k,onBorderWidthChange:za}}function Mb(a){function d(){var a=window.open(c,"","width="+b+", height="+e+", status=1, location=1, resizable=yes"),d=window.setInterval(function(){if(a&&a.closed||a&&"undefined"===typeof a.closed||"undefined"===typeof a)window.clearInterval(d),"function"===typeof g&&g()},500)}var c=a,b=400,e=400,g;return{show:function(){d()},setWidth:function(a){a&&(b=a);return this},setHeight:function(a){a&&(e=a);return this},setCallback:function(a){a&&
(g=a);return this}}}function Nb(){function a(){H=(new Date).getTime()-b;if(H<c){var a=Math.round(d()*C+f);e.style[l]=a+"px"}else clearInterval(p),e.style[l]=o+"px",ta()}function d(){if("flat"==r)return H*(1/c);if("sinusoidal"==r)return Math.abs(Math.sin(H*(Math.PI/(2*c))))}var c="1000",b,e,g=document,f,o,l="left",C,p,H,r="flat",ta,u;return{setAcceleration:function(a){r=a;return this},setCallback:function(a){ta=a;return this},setDuration:function(a){c=a;return this},setDirection:function(a){"horizontal"===
a&&(l="left");"vertical"===a&&(l="top");return this},setElement:function(a){e=a;return this},setElementBoundry:function(a){g=a;return this},startPosition:function(a){f=a;return this},endPosition:function(a){o=a;return this},animate:function(){C=o-f;b=(new Date).getTime();p=setInterval(a,10);return this},drag:function(a){var c=this;this.moveHandler=function(a){var c=Ob({event:Va&&a.targetTouches.length?a.targetTouches[0]:a,boundry:g}).x();e.style.left=c+"px";da(a);ja(a);u&&clearTimeout(u);u=setTimeout(function(){ta({pos_x:c})},
500)};this.upHandler=function(a){c.unbindDragHandlers();da(a);ja(a)};V(document,Aa,this.moveHandler);V(document,Ba,this.upHandler);da(a);ja(a)},unbindDragHandlers:function(){Bb(document,Ba,this.upHandler);Bb(document,Aa,this.moveHandler);return this}}}function Ob(a){return{x:function(){var d,c=a.event.clientX;var b=a.boundry,e=curtop=0;if(b.offsetParent){do e+=b.offsetLeft,curtop+=b.offsetTop;while(b=b.offsetParent);d=e}d=c-d;d=d<this.boundry_x()?d:this.boundry_x();return 0<d?d:0},boundry_x:function(){var d=
a.boundry.getBoundingClientRect();return d.width?d.width:d.right-d.left},y:function(){},boundry_y:function(){}}}function D(){return new Fa}function Fa(){this.eventHandlers=[];this.firedEvents=[]}function Hb(){if(function(){if("object"!==typeof janrain.events||"object"!==typeof janrain.apps.engage||"object"!==typeof janrain.apps.engage.signin)return!1;if(!0===janrain.settings.custom)return!0;for(var a="onAuthWidgetLoad,onAuthWidgetContentPlaced,onCustomizationChange,onProviderLoginComplete,onProviderLoginCancel,onProviderLoginError,onProviderLoginStart,onProviderLoginSuccess,onProviderLoginToken,onReturnExperienceFound,onModalWidgetReady".split(","),
c=0;c<a.length;c++)if("object"!==typeof janrain.events[a[c]])return!1;return!0}())clearTimeout(a),janrain.events.onAuthWidgetLoad.fire();else var a=setTimeout(Hb,5)}Array.prototype.indexOf||(Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var d=Object(this),c=d.length>>>0;if(0===c)return-1;var b=0;0<arguments.length&&(b=Number(arguments[1]),b!=b?b=0:0!=b&&Infinity!=b&&-Infinity!=b&&(b=(0<b||-1)*Math.floor(Math.abs(b))));if(b>=c)return-1;for(b=0<=b?b:Math.max(c-Math.abs(b),0);b<
c;b++)if(b in d&&d[b]===a)return b;return-1});Array.prototype.map||(Array.prototype.map=function(a,d){if(null===this)throw new TypeError;var c=Object(this),b=c.length>>>0;if("function"!==typeof a)throw new TypeError;for(var e=Array(b),g=0;g<b;g++)g in c&&(e[g]=a.call(d,c[g],g,c));return e});Array.prototype.filter||(Array.prototype.filter=function(a,d){if(null==this)throw new TypeError;var c=Object(this),b=c.length>>>0;if("function"!=typeof a)throw new TypeError;for(var e=[],g=0;g<b;g++)if(g in c){var f=
c[g];a.call(d,f,g,c)&&e.push(f)}return e});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});var O=window.innerWidth?window.innerWidth:document.body&&document.body.clientWidth?document.body.clientWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:0;sa=window.innerHeight?window.innerHeight:document.body&&document.body.clientHeight?document.body.clientHeight:document.documentElement&&document.documentElement.clientHeight?
document.documentElement.clientHeight:0;ra=O;var va=window.localStorage&&window.localStorage.getItem&&window.localStorage.removeItem&&window.localStorage.setItem,W=[],Za=!1,u="CSS1Compat"!==document.compatMode,fb=!1,t=!1,e=[],O=navigator.userAgent.toLowerCase().match(/(iphone|ipod|ipad|blackberry|rim tablet|android|htc|lg|midp|mmp|mobile|nokia|opera mini|palm|pocket|psp|sgh|smartphone|symbian|treo mini|playstation portable|sonyericsson|samsung|mobileexplorer|palmsource|benq|windows phone|windows mobile|iemobile|windows ce|nintendo wii|\Wsilk\W)/i),
ub=null!==O?O[0]:!1,Pb="number"===typeof window.orientation||null!==O,Va="ontouchstart"in window;Ba=Va?"touchend":"mouseup";Aa=Va?"touchmove":"mousemove";janrain.settings&&janrain.settings.storageServer&&Ib("xDomainLocalStorageJanrain",janrain.settings.storageServer,function(){V(document.getElementById("xDomainLocalStorageJanrain"),"load",function(){Za=!0})});var P=navigator.userAgent,f=ab(),wa=/Gecko\//.test(P),Eb=/AppleWebKit\//.test(P);/Chrome\//.test(P);Na();var l=function(){var a=function(a){for(var b=
[],d=0;d<a.length;d++)b.push(a[d]);return b},d={};janrain.settings&&janrain.settings.permissions&&(d.login=a(janrain.settings.permissions));janrain.settings&&janrain.settings.share&&janrain.settings.share.permissions&&(d.share=a(janrain.settings.share.permissions));return function(a,b){b=b||"login";return!d[b]?!1:0<=d[b].indexOf(a)}}();bb.options={strictMode:!1,key:"source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(","),q:{name:"queryKey",
parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};for(var U=function(){function a(){if("undefined"===typeof window.orientation)return!1;var a;b(document.body,H);
p=f().content;o();l();document.body.style.padding="0px";document.body.style.margin="0px";"object"===typeof window.onresize&&(a="resize");"object"===typeof window.onorientationchange&&(a="orientationchange");a&&(window.addEventListener(a,function(){Ta(window.orientation,{height:screen?screen.height:0,width:screen?screen.width:0},{height:window.innerHeight,width:window.innerWidth});g()},!1),setTimeout(g,30),window.addEventListener("beforeunload",function(){window.removeEventListener(a,g,!1)},!1));t.addHandler(function(){d({height:window.innerHeight,
width:window.innerWidth},0)});R.addHandler(function(a){sa=a.height;ra=a.width});window.addEventListener("beforeunload",function(){window.removeEventListener(eventName,g,!1)},!1)}function d(a,c){var b=window.innerHeight,e=window.innerWidth,g=!0,f=!0;b!=a.height&&(g=!1);e!=a.width&&(f=!1);g&&f?20>c?setTimeout(function(){d({height:b,width:e},++c)},100):R.fire({height:b,width:e}):setTimeout(function(){d({height:b,width:e},0)},100)}function c(){setTimeout(function(){C(p)},20);b(H,document.body)}function b(a,
c){for(var b=0;b<a.style.length;b++){var d=a.style[b];c.style.setProperty(d,a.style.getPropertyValue(d),a.style.getPropertyPriority(d))}}function e(){var a;a=(0===window.orientation||180===window.orientation)&&ra>sa||(90===window.orientation||-90===window.orientation)&&sa>ra?!1:!0;var c="landscape";if(a&&(0===window.orientation||180===window.orientation))c="portrait";if(!a&&(90===window.orientation||-90===window.orientation))c="portrait";return c}function g(){var a=e();C("width=device-width, initial-scale=1, maximum-scale=1");
t.fire({orientation:a})}function f(){var a=document.getElementsByTagName("meta"),c;for(c in a)if("viewport"===a[c].name)return a[c];return!1}function o(){if("undefined"===typeof document.getElementsByTagName||f())return!1;var a=document.getElementsByTagName("head")[0],c=document.createElement("meta");c.setAttribute("name","viewport");a.appendChild(c);return!0}function l(){if("undefined"===typeof document.getElementsByTagName)return!1;document.getElementsByTagName("head");var a=document.createElement("meta");
a.setAttribute("name","HandheldFriendly");a.content="true"}function C(a){var c=f();if(!c||c.content==a)return!1;if("undefined"===typeof a){var b=f();document.getElementsByTagName("head")[0].removeChild(b)}c.content=a;return!0}var p,H=document.createElement("div"),r=navigator.userAgent.toLowerCase().match(/(iphone|ipod|ipad|blackberry|rim tablet|android|htc|lg|midp|mmp|mobile|nokia|opera mini|palm|pocket|psp|sgh|smartphone|symbian|treo mini|playstation portable|sonyericsson|samsung|mobileexplorer|palmsource|benq|windows phone|windows mobile|iemobile|windows ce|nintendo wii|\Wsilk\W)/i),
u=null!==r?r[0]:!1,t=D(),R=D();u&&u[0].match(/android|\Wsilk\W/);var Ta=function(){var a=window.orientation,c={height:screen?screen.height:0,width:screen?screen.width:0},b={height:window.innerHeight,width:window.innerWidth},d=!1;return function(e,g,f){var o=!1,l=function(a,c){return a.height>=a.width&&c.height>=c.width||a.width>a.height&&c.width>c.height?!0:!1},C=a===e,p=l(g,c),H=l(f,b);if(!C&&(!p||!H))o=!0;!C&&!p&&(d=!0);o&&(d&&!l(g,f)&&(o=f.height,f.height=f.width,f.width=o),sa=f.height,ra=f.width);
a=e;c={height:g.height,width:g.width};b={height:f.height,width:f.width}}}();return{setElement:function(){return this},onOrientationChange:t,onViewportChange:R,getMobileDevice:function(){return u},getOrientation:function(){return e()},activate:function(){a()},deactivate:function(){c()}}}(),sb=function(a){var d;d="https:"===document.location.protocol?"https://docj27ko03fnu.cloudfront.net/":"http://cdn.rpxnow.com/";d=d.replace(/\/$/,"");return d+"/"+a},O={openId:{aol:{identifier:"aol",flow:"openid1",
width:514,height:550,color:"#0FD6FF",friendlyName:"AOL"},blogger:{identifier:"blogger",flow:"openid1",width:800,height:600,color:"#FF6600",friendlyName:"Blogger"},livejournal:{identifier:"livejournal",flow:"openid1",width:800,height:600,color:"##213368",friendlyName:"LiveJournal"},netlog:{identifier:"netlog",flow:"openid1",width:800,height:600,color:"#000000",friendlyName:"Netlog"},wordpress:{identifier:"wordpress",flow:"openid1",width:800,height:600,color:"#21759b",friendlyName:"WordPress"},openid:{identifier:"openid",
flow:"openid1",width:800,height:600,color:"#f79311",friendlyName:"OpenID"}},openId2:{flickr:{identifier:"https://me.yahoo.com/id",flow:"openid",width:500,height:500,color:"#FF0084",friendlyName:"Flickr"},google:{identifier:"https://www.google.com/accounts/o8/id",flow:"openid",width:500,height:450,color:"#1C69F5",friendlyName:"Google"},hyves:{identifier:"http://hyves.nl/",flow:"openid",width:800,height:600,color:"#659BC8",friendlyName:"Hyves"},myopenid:{identifier:"http://myopenid.com/",flow:"openid",
width:800,height:600,color:"#8cc63f",friendlyName:"MyOpenID"},paypal:{identifier:"https://www.paypal.com/webapps/auth/server",flow:"openid",width:800,height:600,color:"#1A3665",friendlyName:"PayPal"},verisign:{identifier:"http://pip.verisignlabs.com/",flow:"openid",width:945,height:600,color:"#B8004D",friendlyName:"VeriSign"},yahoo:{identifier:"https://me.yahoo.com/id",flow:"openid",width:500,height:500,color:"#650065",friendlyName:"Yahoo!",shareSettings:{broadcast:{counter:{},format:{message:"#{MESSAGE} #{URL}"},
features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}}},oauth:{facebook:{flow:"facebook",width:1050,height:550,color:"#3B5998",friendlyName:"Facebook",publishSettings:{},shareSettings:{broadcast:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,media:!0,actionLink:!0}},contact:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,media:!0,actionLink:!0}}}},myspace:{flow:"myspace",width:800,height:500,color:"#000000",
friendlyName:"Myspace",shareSettings:{broadcast:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},twitter:{flow:"twitter",width:800,height:500,color:"#35CCFF",friendlyName:"Twitter",shareSettings:{broadcast:{counter:{max:140,urlRegex:/\b(?:[a-z]{1}[-a-z0-9+.]+:(?:\/\/)?)?[-a-z0-9._~@:!$&'()*+,;=]+(?:\.[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\.(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx))(?::\d+)?(?:\/[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\?[-a-z0-9._~@:!$&'()*+,;=%]+)?(?:#[-a-z0-9._~@:!$&'()*+,;=%]+)?\b/ig,
urlLength:23},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}},contact:{counter:{max:140,urlRegex:/\b(?:[a-z]{1}[-a-z0-9+\.]+:(?:\/\/)?)?[-a-z0-9._~@:!$&'()*+,;=]+(?:\.[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\.(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx))(?::\d+)?(?:\/[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\?[-a-z0-9._~@:!$&'()*+,;=%]+)?(?:#[-a-z0-9._~@:!$&'()*+,;=%]+)?\b/ig,urlLength:23},
format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},linkedin:{flow:"linkedin",width:550,height:750,color:"#006699",friendlyName:"LinkedIn",shareSettings:{broadcast:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,media:!1,actionLink:!1}},contact:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},live_id:{flow:"liveid",
width:900,height:600,color:"#666666",friendlyName:"Windows Live ID"},salesforce:{flow:"salesforce",width:800,height:500,color:"#333333",friendlyName:"Salesforce"},orkut:{flow:"orkut",width:800,height:600,color:"#333",friendlyName:"Orkut"},vzn:{flow:"vzn",width:600,height:450,color:"#333",friendlyName:"VZnet"},foursquare:{flow:"foursquare",width:950,height:550,color:"#333",friendlyName:"Foursquare"},sinaweibo:{flow:"sinaweibo",width:950,height:550,color:"#333",friendlyName:"Sina Weibo"},tumblr:{flow:"tumblr",
width:950,height:550,color:"#333",friendlyName:"Tumblr"},microsoft_live_connect:{flow:"microsoft_live_connect",width:950,height:550,color:"#333",friendlyName:"Microsoft Live Connect"},renren:{flow:"renren",width:950,height:550,color:"#333",friendlyName:"Renren"},disqus:{flow:"disqus",width:950,height:550,color:"#333",friendlyName:"Disqus"},soundcloud:{flow:"soundcloud",width:950,height:550,color:"#333",friendlyName:"SoundCloud"},vk:{flow:"vk",width:950,height:550,color:"#333",friendlyName:"VK"},mixi:{flow:"mixi",
width:950,height:550,color:"#333",friendlyName:"Mixi",shareSettings:{broadcast:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}},contact:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},email:{color:"#009ddc",shareSettings:{email:{providers:{google:!0,yahoo:!0},counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,
title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}}}},Ha={},Pa=["openId","openId2","oauth"];0<Pa.length;){var Wa=Pa.pop(),na;for(na in O[Wa])Ha[na]=O[Wa][na]}_draggingSliderFx=[];var p=function(){var a=[];return{log:function(d){var c={};c.id=a.length+1;c.message=d;a.push(c);return this},show:function(){if(0!=a.length){for(var d in a)if("undefined"!==typeof a[d].id){var c=a[d];"object"===typeof console&&("function"===typeof console.error?console.error("WARNING ID:"+c.id+" MESSAGE: "+
c.message):"function"===typeof console.log&&console.log("WARNING ID:"+c.id+" MESSAGE: "+c.message))}a=[]}}}}();Fa.prototype.addHandler=function(a){this.eventHandlers.push(a);return this.eventHandlers.length-1};Fa.prototype.removeHandler=function(a){return this.eventHandlers[a]?(this.eventHandlers[a]=null,!0):!1};Fa.prototype.fire=function(a){for(var d=this.eventHandlers.length,c=0;c<d;c++)try{if("function"===typeof this.eventHandlers[c])this.eventHandlers[c](a)}catch(b){p.log(b),p.show()}this.firedEvents.push({event:this,
args:a})};"undefined"===typeof janrain.events&&(janrain.events={});var M;M||(M={});(function(){function a(a){return 10>a?"0"+a:a}function d(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var c=o[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,b){var e,o,p,r,u=g,t,z=b[a];z&&"object"===typeof z&&"function"===typeof z.toJSON&&(z=z.toJSON(a));"function"===typeof l&&(z=l.call(b,a,z));switch(typeof z){case "string":return d(z);
case "number":return isFinite(z)?""+z:"null";case "boolean":case "null":return""+z;case "object":if(!z)return"null";g+=f;t=[];if("[object Array]"===Object.prototype.toString.apply(z)){r=z.length;for(e=0;e<r;e+=1)t[e]=c(e,z)||"null";p=0===t.length?"[]":g?"[\n"+g+t.join(",\n"+g)+"\n"+u+"]":"["+t.join(",")+"]";g=u;return p}if(l&&"object"===typeof l){r=l.length;for(e=0;e<r;e+=1)"string"===typeof l[e]&&(o=l[e],(p=c(o,z))&&t.push(d(o)+(g?": ":":")+p))}else for(o in z)Object.prototype.hasOwnProperty.call(z,
o)&&(p=c(o,z))&&t.push(d(o)+(g?": ":":")+p);p=0===t.length?"{}":g?"{\n"+g+t.join(",\n"+g)+"\n"+u+"}":"{"+t.join(",")+"}";g=u;return p}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});
var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,f,o={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;"function"!==typeof M.stringify&&(M.stringify=function(a,b,e){var d;f=g="";if("number"===typeof e)for(d=0;d<e;d+=1)f+=" ";else"string"===typeof e&&(f=e);if((l=b)&&"function"!==
typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})});"function"!==typeof M.parse&&(M.parse=function(a,c){function e(a,b){var d,g,f=a[b];if(f&&"object"===typeof f)for(d in f)Object.prototype.hasOwnProperty.call(f,d)&&(g=e(f,d),void 0!==g?f[d]=g:delete f[d]);return c.call(a,b,f)}var d,a=""+a;b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),"function"===typeof c?e({"":d},""):d;throw new SyntaxError("JSON.parse");})})();janrain.events.onCustomizationChange||(janrain.events.onCustomizationChange=D());janrain.events.onProviderLoginStart||(janrain.events.onProviderLoginStart=D());janrain.events.onProviderLoginComplete||(janrain.events.onProviderLoginComplete=D());janrain.events.onProviderLoginError||
(janrain.events.onProviderLoginError=D());janrain.events.onProviderLoginSuccess||(janrain.events.onProviderLoginSuccess=D());janrain.events.onProviderLoginToken||(janrain.events.onProviderLoginToken=D());janrain.events.onProviderLogoutStart||(janrain.events.onProviderLogoutStart=D());janrain.events.onProviderLogoutComplete||(janrain.events.onProviderLogoutComplete=D());Hb();na=new function(){function a(){function a(){return{twoColumn:{actionText:"Sign in using your account with",providersPerPage:6},
oneColumn:{actionText:"Sign in with",width:200},oneRow:{actionText:"Sign in with"},footerHeight:10,headerHeight:20}}function c(){if(oa){var a=document.createElement("div");a.style.backgroundColor=ba?"aqua":Ma;a.style.width=B+"px";a.style.height=Fa+"px";a.style.position="absolute";a.style.left="0px";a.style.paddingLeft=n+"px";a.style.paddingRight=n+"px";a.style.paddingBottom=n+"px";a.style.bottom="0px";a.style.fontSize="10px";a.style.textAlign="left";a.style.color=W;a.style.fontFamily=Qa;I(a,null,
0,0,y,y);var j=document.createElement("div");j.appendChild(document.createTextNode(janrain.settings.translate.POWERED_BY_PREFIX||"Powered by "));j.style.paddingLeft="1px";var e=document.createElement("a");e.setAttribute("href","http://www.janrain.com/products/engage/engage-introduction?utm_source="+bb(janrain.settings.appUrl).host+"&utm_medium=partner&utm_campaign=attribution");e.setAttribute("target","_blank");e.appendChild(document.createTextNode("Janrain"));j.appendChild(e);a.appendChild(j);Ua=
a}w=g();a=document.createElement("div");a.style.backgroundColor=ba?"orange":Ma;a.className="janrainHeader";a.style.fontSize=ca+"px";a.style.color=W;a.style.position="relative";a.style.height=pa+"px";40===qa&&(a.style.cssFloat="left");a.style.left=40===qa?"-6px":"-5px";a.style.paddingLeft=n+"px";a.style.paddingRight=n+"px";a.style.paddingTop=n+"px";a.style.paddingBottom="0px";a.style.whiteSpace="nowrap";a.style.width=40===qa?"81px":B+"px";a.style.zIndex="100";40===qa?I(a,null,y,0,0,y):I(a,null,y,y,
0,0);40===qa&&(a.style.marginTop="-3px");a.style.textAlign="one column"===m?"center":"left";j=d();da=document.createElement("div");da.style.paddingLeft="1px";da.style.fontFamily=Qa;" "!==j&&da.appendChild(document.createTextNode(j));a.appendChild(da);Ta=a;s=document.createElement("div");s.className="janrainContent";s.style.width=B+"px";s.style.height=h()+"px";s.style.paddingLeft=n+"px";s.style.paddingRight=n+"px";s.style.boxSizing="content-box";40===qa&&(s.style.paddingTop=n-1+"px");t||(s.style.backgroundColor=
Ma);t||(s.style.border=za?"1px solid "+wa:"1px solid "+Ma);s=I(s,y);t||(s.style.overflow="hidden");s.style.position=za?"relative":"absolute";Ya=E();2==w||0==w?(Ia=(new z).setSide("right").create(),Ja=(new z).setSide("left").create()):(Ia=(new z).setSide("top").create(),Ja=(new z).setSide("bottom").create());a=document.createElement("div");a.id="janrainView";" "!==d()&&a.appendChild(Ta);t&&(j=K("blank"),j.style.display="none",a.appendChild(j));a.appendChild(Ya);!t&&Ia&&Ja&&(a.appendChild(Ia),a.appendChild(Ja));
0<w&&oa&&a.appendChild(Ua);s.appendChild(a);l("customizable_auth_widget_styling")||b(s);fb||p.show()}function b(a){function c(a){var b="string"===typeof a.getAttribute("style")?a.getAttribute("style"):null;b&&(b.cssText&&(b=b.cssText),a.style.setAttribute?a.style.setAttribute("cssText",b.replace(/(((?!!important).)+?);/g,"$1 !important;")):a.setAttribute("style",b.replace(/(((?!!important).)+?);/g,"$1 !important;")))}for(var j=a.getElementsByTagName("*"),d=0,e=j.length;d<e;d++)"janrainProviderPages"===
j[d].id||"janrainSlideControl"===j[d].className||"janrainSlideControl"===j[d].parentNode.className||c(j[d]);c(a)}function d(){if(F&&(F==a().twoColumn.actionText||F==a().oneColumn.actionText||F==a().oneRow.actionText))va=!1;return va&&F?F:e.translate.HEADER?e.translate.HEADER:"two column"===m?a().twoColumn.actionText:"one column"===m?a().oneColumn.actionText:"one row"===m?a().oneRow.actionText:F}function g(){var a=m;if("default"==a||"two column"==a)return 2;if("one column"==a)return 1;if("one row"==
a)return 0}function h(){var a=" "===F?0:pa+n,c=oa&&"one row"!==m?Fa+n:0;return i()+a+c}function o(){var a=parseInt(Ya.style.left),c=parseInt(Ya.style.top),b;1==w?parseInt(Ya.style.height):parseInt(Ya.style.width);2==w&&(b=(B-3*n-(2==w?10:0))/w);if("one column"===m){if(" "===F&&(c+=11,0<c||-9<=c))return 0;if(9>c)return 1;if(0<c||c>=-(pa-(n+1)))return 0}0==w&&(b=B-100);if(0>a&&a<-b)return 1;if(0<a||a>=-n)return 0}function i(){if("two column"===m)var a=J/2;"one column"===m&&(a=J);"one row"===m&&(a=1);
var c="one row"===m?0:2*a,b="one column"===m?3*n:0;if(7===f||6===f||f&&u){if("two column"===m&&(b=n,7===f||6===f))b=2*n;if("one column"===m&&(b=3*n,(7===f||6===f)&&!u))b+=n;if("one row"===m&&(7===f||6===f))b=n}"one column"===m&&Ka<=J&&(b=f&&u?b+2*n:b-2*n);return x*a+n*(a+1)+c+b}function z(){function a(){var c;h="over";var Xa=o();if(0==Xa&&"left"===d||0==Xa&&"top"===d||1==Xa&&"right"===d||1==Xa&&"bottom"===d)return this.style.cursor="default",k.onclick="",!1;var e=this;setTimeout(function(){if(1===
l){if("over"!==h)return!1;f&&(j.style.display="block");g.style.display="block";k.onclick=b;e.style.cursor="pointer";var a=document.getElementById("janrainProviderPages");c="top"==d||"bottom"==d?parseInt(a.style.top):parseInt(a.style.left);var Xa="right"===d||"bottom"===d?c-Ea:c+Ea;"top"===d||"bottom"===d?a.style.top=Xa+"px":a.style.left=Xa+"px";l=2}},f?50:100)}function c(){var a;h="out";var b=o();if(1==b&&"right"===d||0==b&&"left"===d||0==b&&"top"===d||1==b&&"bottom"===d)return!1;setTimeout(function(){if(2===
l){if("out"!==h)return!1;f&&(j.style.display="none");g.style.display="none";var c=document.getElementById("janrainProviderPages");a="top"==d||"bottom"==d?parseInt(c.style.top):parseInt(c.style.left);var b="right"===d||"bottom"===d?a+Ea:a-Ea;"top"===d||"bottom"===d?c.style.top=b+"px":c.style.left=b+"px";l=1}},f?200:400)}function b(){g.style.display="none";k.style.cursor="default";C(d,function(a){D(a);l=1})}var j,d,e,g,q={left:"-33px -16px",right:"0px -16px",top:"-16px -33px",bottom:"-16px 0px"},h=
"",l=1,k;return{setSide:function(a){d=a;return this},create:function(){var f;if(Ka<=J)f=!1;else{f=document.createElement("div");f.setAttribute("id","janrainShim_"+d);f.style.background="black";"top"===d||"bottom"===d?(f.style.height="19px",f.style.width="100%"):(f.style.height="100%",f.style.width="17px");f.style.filter=ba?"alpha(opacity=100)":"alpha(opacity=0)";f.style.position="absolute";f.style.zindex="99";if("top"===d||"bottom"===d)f.style.left="0";f.style[d]=n+"px";f.style.top="one column"!==
m?n+1+"px":"top"===d?"10px":"0px";f.style.display="none";j=f;f=document.createElement("div");f.style.backgroundColor=ba?"green":Ma;f.className="janrainSlideControllerMask";f.style.position="absolute";"one column"!==m&&(f.style.width=n+"px",f.style.height="100%",f.style.top="0px",f.style[d]="0px",f.style.borderWidth="1px","right"===d&&(!oa||"one row"===m)&&I(f,null,0,0,y,0),"left"===d&&(!oa||"one row"===m)&&I(f,null,0,0,0,y),"right"===d&&" "===F&&I(f,null,0,y,y,0),"left"===d&&" "===F&&I(f,null,y,0,
0,y));"one column"===m&&(f.style.height=n+"px",f.style.fontSize="0px",f.style.width="100%",f.style.padding="0px",f.style[d]="0px","top"===d&&" "===F?I(f,null,y,y,0,0):"bottom"===d&&!oa&&I(f,null,0,0,y,y));"one row"===m&&(f.style.height="105.5%");e=f;f=document.createElement("div");f.setAttribute("id","janrainArrow_"+d);f.style.background="url("+sb("rel/img/ee9d3aa7c5896c69488b5941ef31c7bc.png")+") no-repeat scroll "+q[d]+" transparent";f.style.height="19px";f.style.width="17px";f.style.position="absolute";
if("top"===d||"bottom"===d)f.style.left=B/2+"px";f.style[d]=n+"px";f.style.top="one column"!==m?i()/2-2*n+1+"px":"top"===d?"10px":"0px";f.style.display="none";g=f;f=document.createElement("div");f.className="janrainSlideControl";f.style.backgroundColor=ba?"purple":"transparent";"one column"===m?(f.style.width=B+4+"px",f.style.left="3px","top"==d?(f.style.height=n+"px",f.style.top=pa+n+"px"," "===F&&(f.style.left="0px",f.style.width=B+10+"px")):(f.style.height="20px",f.style.bottom=(oa?Fa+n:0)+"px",
I(f,null,0,0,y,y))):(f.style.width="right"===d?"20px":"0px",f.style[d]="0px",f.style.height=i()-(n*(" "===F)?1:2)+"px",40===qa&&"one row"===m&&"left"===d&&(f.style.left=ta+"px"),"right"===d&&!oa&&I(f,null,0,0,y,0),"left"===d&&!oa&&I(f,null,0,0,0,y));f.style.position="absolute";f.style.zIndex="100";f.style.cursor="pointer";f.onmouseover=a;f.onmouseout=c;f.onclick=b;k=f;k.appendChild(e);k.appendChild(j);k.appendChild(g);f=k}return f}}}function C(a,c){var b=document.getElementById("janrainProviderPages"),
d=new Nb;if("top"===a||"bottom"===a){if(" "===F)var j=-(i()-x),e=0;else j=-(i()-x-pa-n),e=pa+n;50===x&&(j-=20);f&&u&&(j+=n," "!==F&&(e+=n));d.setElement(b).setAcceleration("sinusoidal").setDuration(100*J).startPosition(parseInt(b.style.top)).endPosition("bottom"===a?j:e).setDirection("vertical").setCallback(function(){c(a)}).animate()}else f&&u?(j=-(B-2*n-39),"one row"===m&&(j=-(ta-1*n))):(j=-(B-32),"one row"===m&&(j=-(B-24))),d.setElement(b).setAcceleration("sinusoidal").setDuration(800).startPosition(parseInt(b.style.left)).endPosition("right"==
a?j:n).setDirection("horizontal").setCallback(function(){c(a)}).animate()}function E(){var a,c;function b(d){d=d.touches[0];"one column"===m?a=d.pageY:c=d.pageX}function d(b){b.preventDefault();b=b.touches[0];b="one column"===m?a-b.pageY:c-b.pageX;if(35<b||-35>b){var j;j="one column"===m?0<b?"bottom":"top":0<b?"right":"left";var e=o(),f=!0;"bottom"===j&&e+1==k&&(f=!1);"top"===j&&0==e&&(f=!1);"left"===j&&0==e&&(f=!1);"right"===j&&e+1==k&&(f=!1);f&&("one column"===m?g.style.top=parseInt(g.style.top)-
b+"px":g.style.left=parseInt(g.style.left)-b+"px",C(j,function(){D()}),g.ontouchmove="")}}function j(){g.ontouchmove=d}var e,g,q,h,k,l=w,i=[];h=G();k=t?1:Math.ceil(Ka/J);2<k&&p.log("Either reduce the number of providers, or increase the setting for providersPerPage.");g=document.createElement("div");g.setAttribute("id","janrainProviderPages");t&&(g.className="janrainConfigureMode");g.style.paddingTop=(6===f||7===f)&&f&&u?2*n:n+"px";if((6===f||7===f)&&!u)g.style.paddingTop=n+4+"px";1<k&&(g.ontouchstart=
b,g.ontouchmove=d,g.ontouchend=j);40===qa&&"one row"===m?g.style.left=ta+n+"px":f&&u?"one column"!==m&&(g.style.left=n+"px"):g.style.left=n+"px";40===qa&&"one row"===m&&(g.style.cssFloat="left");40===qa&&"one row"===m&&(g.style.marginTop="1px");"one column"===m&&(g.style.top=(f&&u?1:0)+pa+n+"px");"one row"!==m&&" "===F&&(g.style.top="0px");"one column"===m&&" "===F&&(g.style.top="0px");e=B*k;g.style.position=f&&u&&"one column"===m?"relative":"absolute";"two column"===m&&!(Ka<=J)&&(g.style.width=e+
"px");"one row"===m&&(g.style.width=(!0===t?B+n:2*B)+"px");t&&(l=0);c=0;a=0;for(var vb=0;vb<k;vb++){for(q=0;q<=l;q++)i[q]=document.createElement("ul"),i[q].className="providers",i[q].id="janrainProviders_"+q,1<l&&(i[q].style.cssFloat="left"),1<l&&(i[q].style.styleFloat="left"),i[q].style.listStyleType="none",i[q].style.marginTop="0px",i[q].style.marginLeft="0px",i[q].style.marginRight="0px",i[q].style.marginBottom="0px",i[q].style.padding="0px";e=document.createElement("div");e.className="janrainPage";
e.setAttribute("pageIndex",vb);f&&u&&1===k&&(e.style.width="110%");for(q=0;q<l;q++)e.appendChild(i[q]);if(t||1>w)for(q=0;q<=l;q++)e.appendChild(i[q]);for(var r=h.length%2,Qb=t?Ka:J,s=0;s<Qb&&!(0==h.length);s++){if(2==l)var v=1==r?i[h.length%2?0:1]:i[h.length%2];if(1==l||0==l)v=i[0];q=h.shift();v.appendChild(q)}g.appendChild(e)}return g}function D(a){0==o()?("left"===a&&(Ja.style.width=n+"px",Ia.style.display="block",Ia.style.width="20px"),"top"===a&&(Ia.style.height=n+"px",Ja.style.display="block",
Ja.style.height="20px")):("right"===a&&(Ia.style.width=n+"px",Ja.style.display="block",Ja.style.width="20px"),"bottom"===a&&(Ja.style.height=n+"px",Ia.style.display="block",Ia.style.height="20px"))}function G(){for(var a=[],c=0;c<Ka;c++){var b=K(la[c],c+1);a.push(b)}if("one column"==m){var d=a.slice(0),c=function(){var a=-Infinity,c,b,j=function(){c=d[b].children[0].children[1];return void 0!==c};for(b=0;b<d.length;b++)j()&&(a=Math.max(a,c.offsetWidth));for(b=0;b<d.length;b++)j()&&(c.style.width=
a+5+"px")};janrain.events.onModalOpen?janrain.events.onModalOpen.addHandler(c):janrain.events.onAuthWidgetContentPlaced.addHandler(c)}return a}function H(a,c){c.style.cursor="pointer";c.setAttribute("id","janrain-"+a);c.setAttribute("role","button");"one row"===m?c.style.background="transparent":("gradient"===Ra&&Ab(c,"bottom, #eeeeee, #ffffff"),"gray"===Ra&&(c.style.backgroundColor="#eeeeee"),"white"===Ra&&(c.style.backgroundColor="#ffffff"));V(c,"mouseover",function(){ab();"one row"===m?c.style.background=
"transparent":(c.style.backgroundColor="#E3E3E3",c.style.backgroundImage="")});V(c,"mouseout",function(){ab();"one row"===m?c.style.background="transparent":("gradient"===Ra&&Ab(c,"bottom, #eeeeee, #ffffff"),"gray"===Ra&&(c.style.backgroundColor="#eeeeee"),"white"===Ra&&(c.style.backgroundColor="#ffffff"))});fb||L(c,a);return c}function K(a,c){var b=document.createElement("li");b.style.listStyle="none";0==w&&!1===t&&(b.style.cssFloat="left");0==w&&!1===t&&(b.style.styleFloat="left");b.style.height=
f&&u?x+2:x+"px";if("two column"==m){var d=t?3*n:Ka<=J?0:3*n;b.style.width=6===f||ab&&u?(B-d-4*n)/w+"px":(B-d-(2==w?10:0))/w+"px"}b.style.marginTop="0px";if("one column"==m){if(7==f||6==f)b.style.marginTop="-1px";f&&u?b.style.marginRight="0px":b.style.width=B-n/2+"px";b.style.marginLeft="0px"}else b.style.marginRight=n+"px";0==w&&(b.style.width=x+"px");b.style.marginBottom=(7===f||6===f||f&&u?3:n)+"px";b.style.position="relative";0!=w&&(b.style.border="1px solid "+ma);0!=w&&I(b,ha);var d=document.createElement("a"),
j=document.createElement("span"),e=document.createElement("span");"undefined"!==typeof c&&(d.tabIndex=c);d.style.fontFamily="Helvetica, lucida grande, Verdana, sans-serif";d.style.fontSize="12px";d.style.lineHeight="14px";d.style.marginLeft="auto";d.style.marginRight="auto";d.href="javascript:void(0);";d.style.textDecoration="none";d.style.display="block";d.style.paddingLeft="5px";d.style.paddingRight="5px";d.style.textAlign="left";e.className="janrain-provider-text-color-"+a;e.style.fontFamily=Qa;
e.style.cursor="pointer";e.style.marginLeft="7px";e.style.textAlign="left";30==x&&(j.className="janrain-provider-icon-24 janrain-provider-icon-"+a,j.style.marginTop="3px",e.style.marginTop="9px",e.style.verticalAlign="top",e.style.display="inline-block");50==x&&(j.className="janrain-provider-icon-32 janrain-provider-icon-"+a,j.style.marginTop="9px",j.style.backgroundColor="transparent",e.style.marginTop="16px",e.style.fontSize="16px",e.style.lineHeight="20px",e.style.verticalAlign="top",e.style.display=
"inline-block");"one column"==m&&(d.style.textAlign="center");"two column"==m&&275>B&&(e.style.textIndent="-9999px",e.style.marginLeft=0,d.style.textAlign="center");2==w&&(30==x&&(d.style.width="auto"),50==x&&(j.style.marginLeft="5px"));if(0==w&&(30==x||50==x)){var j=document.createElement("a"),g=document.createElement("span"),q=document.createTextNode(a);"undefined"!==typeof c&&(j.tabIndex=c);j.className="janrain-provider-icon-32 janrain-provider-icon-bg janrain-provider-icon-"+a;j.style.marginTop=
"0px";j.href="javascript:void(0);";j.style.textDecoration="none";j.style.display="block";g.style.display="inline-block";g.style.textIndent="-9999px"}if("customopenid"===a){var h=document.createTextNode(Q.customOpenIdProviderName);if(1==w||2==w){if(30==x||50==x)j.style.backgroundImage="url("+Q.largeIcon+")",e.appendChild(h),e.style.color=Q.customOpenIdProviderColor||"#000000";15<=h.length&&(h.textContent=h.textContent.substr(0,15))}if(0==w&&(30==x||50==x))q=document.createTextNode(Q.customOpenIdProviderName),
j.style.backgroundImage="url("+Q.largeIcon+")";f&&10>f&&(j.style.backgroundImage="none",j.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enable=true,sizingMethod=scale,src='"+Q.largeIcon+"')")}else if("blank"!==a&&(1==w||2==w))30==x&&(j.style.backgroundColor="transparent",e.innerHTML=Ha[a].friendlyName),50==x&&(j.style.backgroundColor="transparent",e.innerHTML=Ha[a].friendlyName);6===f&&"one row"!==m&&(h=document.createElement("div"),h.style.height=j.style.height,h.style.width="90px",
h.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enable=true,sizingMethod=crop,src='"+j.src+"')",j.style.filter="alpha(opacity=0)",h.appendChild(j),b.appendChild(h));0==w?(b.appendChild(j),j.appendChild(g),g.appendChild(q)):(b.appendChild(d),d.appendChild(j),d.appendChild(e));return H(a,b)}function O(a,c){var b=document.createElement("a"),d=e.translate.SIGN_IN_AS||"Sign in as {name}",d=d.replace("{name}",c),j=document.createElement("span"),d=document.createTextNode(d),g=document.createElement("span");
j.className="janrain-provider-text-color-"+a;b.href="javascript:void(0);";b.style.textDecoration="none";b.style.display="block";if("customopenid"===a){var q=document.createElement("span");document.createElement("span");q.className="janrain-provider-icon-32 janrain-provider-icon-"+a;q.style.backgroundImage="url("+Q.largeIcon+")";j.style.color=Q.customOpenIdProviderColor||"#000000";10>f&&(q.style.backgroundImage="none",q.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enable=true,sizingMethod=scale,src='"+
Q.largeIcon+"')")}else q=document.createElement("span"),q.className="janrain-provider-icon-24 janrain-provider-icon-"+a;g.style.display="inline-block";g.style.verticalAlign="top";g.style.fontFamily=Qa;var i=document.createElement("div"),k=7.5*d.length+30,l=h();i.style.fontSize="16px";i.style.height="100%";i.style.position="relative";if(0==w||120>l)15<=d.length&&(i.style.fontSize="14px",k=7*d.length+30),20<=d.length&&(i.style.fontSize="12px",k=6*d.length+30),24<=d.length&&(i.style.fontSize="10px",
k=5*d.length+50),30<=d.length&&(d.textContent=d.textContent.substr(0,26)+"...",k=162);i.style.width=k+"px";if(0==w||116>l)"customopenid"===a?(q=document.createElement("span"),document.createElement("span"),q.className="janrain-provider-icon-24 janrain-provider-icon-"+a,q.style.backgroundImage="url("+Q.largeIcon+")",j.style.color=Q.customOpenIdProviderColor||"#000000",f&&10>f&&(q.style.backgroundImage="none",q.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enable=true,sizingMethod=scale,src='"+
Q.largeIcon+"')")):(q=document.createElement("span"),q.className="janrain-provider-icon-24 janrain-provider-icon-"+a);30===x&&(g.style.marginTop="9px",g.style.fontSize="12px",q.style.marginTop="3px");50===x&&(g.style.marginTop="16px",q.className="janrain-provider-icon-32 janrain-provider-icon-"+a,q.style.marginTop="9px");"one row"===m&&30===x&&(q.style.marginTop="-1px");g.appendChild(j);j.appendChild(d);q.style.marginRight="10px";q.style.verticalAlign="top";b.style.overflow="hidden";b.style.position=
"relative";b.style.height=("one row"!==m?x:25)+"px";b.style.marginBottom="one row"===m?"-4px":"4px";"one row"===m&&(b.style.top="-4px");b.style.left="0px";f&&u&&(b.style.marginRight="5px");f&&u&&(b.style.marginLeft="3px");b.style.border="1px solid "+ma;I(b,ha);"customopenid"===a&&(b.style.color=Ha[a].color);6===f||7===f||f&&u?i.style.left="10px":i.style.margin="0 auto";i.appendChild(q);i.appendChild(g);0==w&&(i.style.paddingTop="2px",g.style.marginTop="6px");0==w||116>l?(b.appendChild(i),i.style.width=
"auto"):(50===x&&parseInt(b.style.height),g.style.cssFloat="none",g.style.styleFloat="none",b.appendChild(q),b.appendChild(g));return H(a,b)}function L(a,b){V(a,"click",function(){M(b)})}function M(a){var b=Ha[a],c={appUrl:e.appUrl,mobileDevice:ub,language:e.language,popup:ka,tokenUrl:ea||e.tokenUrl||window.location.href,facebookPermissions:Pa,forceReauth:La,widgetType:"auth",tokenAction:ya,bpChannel:X,customOpenid:Wa,customOpenidOpxblob:e.customOpenidOpxblob};b.name=a;new T(b,c,function(){fa||($a=
setTimeout(function(){Da(b)},300))})}function N(){var a=document.createElement("div");a.style.position="absolute";a.style.top="0px";a.style.left="0px";a.style.width=B+"px";a.style.zIndex="102";a.style.textAlign="center";a.style.padding=n+"px";a.style.backgroundColor="transparent"===Ma?"#ffffff":Ma;a.style.height=h()-(f&&u?0:2*n)+"px";I(a,y);return a}function P(a){var b=document.createElement("a"),c=document.createTextNode(e.translate.USE_ANOTHER_ACCOUNT||"switch accounts");b.setAttribute("class",
"janrainSwitchAccountLink");b.setAttribute("href","");b.style.fontSize="12px";b.style.fontFamily=Qa;b.style.color=W;b.onclick=a;b.appendChild(c);return b}function R(){return"modal"===A?document.getElementById("janrainModal"):"embed"===A?document.getElementById("janrainEngageEmbed"):!1}function S(){var a=parseInt(s.style.width);return a=a+2*n+2}function Z(){var a=R();null!==a&&"object"===typeof s&&s.parentNode===a&&a.removeChild(s)}function $(){var a="";"object"===typeof k&&(a=k.getState());return{type:A,
width:S(),fontFamily:Qa,fontSize:ca,fontColor:W,backgroundColor:Ma,borderColor:wa,borderRadius:y,format:m,providersPerPage:J,providers:la,buttonBackgroundStyle:Ra,buttonBorderColor:ma,buttonBorderRadius:ha,actionText:d(),showAttribution:oa,modalState:a}}function aa(a){m=r("string",["default","two column","one column","one row"],"two column",a);"default"===m&&(m="two column");"one row"==a&&(y=r("number",[0,10],5,y));na()}function U(a){"two column"===m&&(B=r("number",[225,600],380,a));"one column"===
m&&(B=r("number",[160,600],200,a));"one row"===m&&(x=30,a=Ka<=J?n*(parseInt(J)-1):n*(parseInt(J)+2),40===qa&&(a+=ta-n),B=x*J+a);if(("two column"===m||"one column"===m)&&!t)B=B-2*n-2;f&&u&&(B=B+2*n+2);"one row"!==m&&(x=380<B?50:30)}function ga(b){"string"===typeof b&&(va=!0,F=r("text",null,F,b)," "===F?y=r("number",[0,5],5,y,!0):pa="two column"!==m?a().headerHeight-5:a().headerHeight)}function ia(a){Ra=r("string",["gray","white","gradient"],"gradient",a)}function ja(a){ma=r("color",null,"#CCCCCC",
a)}function ra(a){Ma=r("color",null,"#ffffff",a)}function sa(a){"undefined"===typeof a&&(a=5);y=" "===F||!oa||"one row"===m?r("number",[0,5],5,a,!0):r("number",[0,10],10,a)}function ua(a){oa=r("boolean",null,!0,a);h();y=a?r("number",[0,10],5,y,!0):r("number",[0,5],5,y,!0)}function xa(a){wa=r("color",null,"#C0C0C0",a)}function na(){"two column"===m&&(ca=18);if("one column"===m||"one row"===m)ca=14}function Aa(a){W=r("color",null,"#333333",a)}function Ba(a){if("object"==typeof a){w=g();for(var b=0,
c=a.length;b<c;b++)Ha[a[b]]||(p.log(a[b]+" is not a valid provider: removing."),a.splice(b,1),--b,--c);la=a;Ka=a.length;"object"===typeof k&&k.setHeight(h()-2*n).refresh()}}function Ca(a){"two column"===m&&(J=r("number",[4,6,8],6,a));"one column"===m&&(J=r("number",[1,6],6,a));"one row"===m&&(J=Va?Ka:r("number",[4,8],6,a),U(B))}function Da(a){var b=document.createTextNode(e.translate&&e.translate.SIGNING_IN?e.translate.SIGNING_IN:"Signing in ..."),c=document.createElement("div");Sa=N(a.name);c.appendChild(b);
c.style.position="absolute";c.style.marginTop="-8px";c.style.top="50%";c.style.textAlign="center";c.style.width="100%";Sa.appendChild(c);s&&s.appendChild(Sa)}var ba=!1,B=380,va=!1,Qa="Helvetica, lucida grande, Verdana, sans-serif",ca=18,W="#666666",Ma="#ffffff",wa="#C0C0C0",y=10,s,da,m="two column",w,za,J=6,la=["aol","google","yahoo","openid"],Ka=4,ma="#CCCCCC",ha=5,Ra="gradient",x=30,pa=a().headerHeight,qa=60,ta=89,Fa=a().footerHeight,n=5,Ea=10,F="Sign in using your account with",Sa,Ya,Ia,Ja,oa=
!0,Na=!1,Oa=!1,Ta,Ua;janrain.events.onProviderLoginStart.addHandler(function(a){Ga("login_tab",a.provider,1)});return{build:c,setFormat:function(b){b&&aa(b);"two column"!==m&&(pa=a().headerHeight-5);"two column"===m&&(J=a().twoColumn.providersPerPage,pa=a().headerHeight);return this},setActionText:function(a){"string"===typeof a&&ga(a);return this},setFontSize:function(a){a&&na(a);return this},setFontFamily:function(a){a&&a&&(Qa=a);return this},setFontColor:function(a){a&&Aa(a);return this},setButtonBorderColor:function(a){a&&
ja(a);return this},setButtonBorderRadius:function(a){if("string"==typeof a||"number"==typeof a)ha=r("number",[0,20],5,a);return this},setButtonBackgroundStyle:function(a){a&&ia(a);return this},setWidth:function(a){("string"==typeof a||"number"==typeof a)&&U(a);return this},refresh:function(){Z();var a=R();c();var b=v("expected_tab");b&&!Za?Y("expected_tab",b):(null!==a&&"object"===typeof s&&a.appendChild(s),"object"===typeof k&&k.setHeight(parseInt(s.style.height)+2).refresh());janrain.events.onCustomizationChange.fire($());
return this},remove:function(){Z();return this},setRowHeight:function(a){if(0!==g())return this;a||(a=60);oneRowHeaderHeight=r("number",[40,60,90],60,a);40===oneRowHeaderHeight&&(x=30,qa=40);60===oneRowHeaderHeight&&(x=30);90===oneRowHeaderHeight&&(x=50);return this},setHeight:function(a){"object"==typeof s&&(s.style.height=a+"px");return this},setBackgroundColor:function(a){a&&ra(a);return this},setBorderColor:function(a){a&&xa(a);return this},setBorderRadius:function(a){("string"==typeof a||"number"==
typeof a)&&sa(a);return this},setProviders:function(a){"object"==typeof a&&Ba(a);return this},setProvidersPerPage:function(a){if("string"==typeof a||"number"==typeof a)Ca(a),"object"===typeof k&&k.setHeight(h()).refresh("janrainModal");return this},setShowAttribution:function(a){"boolean"===typeof a&&ua(a);return this},setPreviewMode:function(a){"boolean"===typeof a&&(fb=a);return this},setProviderFlow:function(a,b){return L(a,b)},triggerFlow:function(a){return M(a)},setNoReturnExperience:function(a){"boolean"===
typeof a&&(Na=a);return this},setNoReturnExperienceSwitchAccountLink:function(a){"boolean"===typeof a&&(Oa=a);return this},setConfigureMode:function(a){"boolean"===typeof a&&(t=a,w=g());return this},embed:function(a){if((za=a)&&"object"==typeof s)s.style.position="relative";return this},getContentsDiv:function(){return s},getErrorPage:function(a,b){var c=document.createTextNode(b.msg),d=document.createElement("div");d.appendChild(c);d.style.color=W;d.style.fontSize=ca+"px";d.style.width="100%";var j=
N(a);j.appendChild(d);j.appendChild(P(function(){s.removeChild(j);s.removeChild(Sa);La=!0;return!1},a));s.appendChild(j);return s},getReturnExperience:function(a,b){if(fb||Na||-1===la.indexOf(a))return s;var c=O(a,b),d=N(a),j=document.createElement("div"),e=function(){La=Za=!0;s.removeChild(d);return!1};j.style.position="relative";j.style.top="50%";30===x&&(j.style.marginTop="-25px");50===x&&(j.style.marginTop="-35px");0==w&&(j.style.top="0",j.style.marginTop="0");d.id="janrainAuthReturnExperience";
d.appendChild(j);j.appendChild(c);Oa||j.appendChild(P(e,a));s.appendChild(d);return s},getWidth:function(){return S()},getActualHeight:function(){return parseInt(s.style.height)+2},getHeight:function(){return h()-2*n},getState:function(){return $()},setState:function(b){if(l("customizable_auth_widget_styling")){var c=b.fontFamily;c&&(Qa=c);na(b.fontSize);Aa(b.fontColor);ra(b.backgroundColor);xa(b.borderColor);"embed"===A&&b.format&&(b.format&&aa(b.format),"two column"!==m&&(pa=a().headerHeight-5),
"two column"===m&&(J=a().twoColumn.providersPerPage,pa=a().headerHeight));if("string"==typeof b.providersPerPage||"number"==typeof b.providersPerPage)Ca(b.providersPerPage),"object"===typeof k&&k.setHeight(h()).refresh("janrainModal");ia(b.buttonBackgroundStyle);ja(b.buttonBorderColor);ha=r("number",[0,20],5,b.buttonBorderRadius);ga(b.actionText);ua(b.showAttribution);sa(b.borderRadius);"embed"===A&&("string"==typeof width||"number"==typeof width)&&U(b.width)}Ba(b.providers)},showNotice:function(){Da()},
removeNotice:function(){Sa&&Sa.parentNode&&Sa.parentNode.removeChild(Sa)},removeReturnExperience:function(){var a=document.getElementById("janrainAuthReturnExperience");a&&a.parentNode&&a.parentNode.removeChild(a)}}}function d(){if("object"===typeof h)if("object"===typeof K){var a=h.getState();a.width=K.width;K=a}else K=h.getState();"object"===typeof h&&h.remove();"object"===typeof k&&k.remove();E();A="modal";"object"===typeof h&&K&&l("customizable_auth_widget_styling")&&h.setState(K);"object"===
typeof k&&ha&&l("customizable_auth_widget_styling")&&k.setState(ha);"object"===typeof k&&k.show();"object"===typeof h&&h.refresh()}function c(){if("object"===typeof h){if("object"===typeof K){var a=h.getState();a.borderRadius=K.borderRadius;a.format=K.format;a.width=K.width;K=a}else K=h.getState();ha=K.modalState;delete ha.orientation}"object"===typeof h&&h.remove();"object"===typeof k&&k.remove();"object"===typeof k&&(k="");G();A="embed";"object"===typeof h&&K&&l("customizable_auth_widget_styling")&&
h.setState(K);"object"===typeof h&&h.refresh()}function b(){var a,b;E();b=document.getElementsByTagName("a");var c=RegExp("(\\s|^)"+e.linkClass+"(\\s|$)");for(a in b)c.test(b[a].className)&&(b[a].onclick=g)}function G(){var b=v("expected_tab");h=new a;h.setBackgroundColor(db).embed(!0).setPreviewMode(gb).setShowAttribution(hb).setNoReturnExperience(ib).setNoReturnExperienceSwitchAccountLink(wb).setFormat(wa).setRowHeight(W).setFontSize(jb).setFontFamily(kb).setFontColor(lb).setActionText(mb).setProviders(da).setProvidersPerPage(nb).setWidth(va).setBorderColor(Da).setBorderRadius(Ca).setButtonBorderColor(ob).setButtonBorderRadius(pb).setButtonBackgroundStyle(qb).build();
var c=document.getElementById("janrainEngageEmbed");null===c&&(c=document.getElementById("janrainModal"));S||(b?(Z("welcome_info_name",unescape(v("welcome_info_name"))),Y("expected_tab",b)):$(c,h.getContentsDiv()))}function g(){"object"===typeof k&&k.show();return!1}function E(){var b=Ua(cb,za),c=v("expected_tab");if("undefined"===typeof b||0>b)b=5;h=new a;h.setBackgroundColor(db).setPreviewMode(gb).setShowAttribution(hb).setNoReturnExperience(ib).setNoReturnExperienceSwitchAccountLink(wb).setFontSize(jb).setFontFamily(kb).setFontColor(lb).setActionText(mb).setProviders(da).setProvidersPerPage(nb).setBorderRadius(b).setButtonBorderColor(ob).setButtonBorderRadius(pb).setButtonBackgroundStyle(qb).build();
if("object"!==typeof k){k=new Fb;k.ready=!1;var d=k.addContent;k.addContent=function(a){k.ready=!0;d(a);janrain.events.onModalWidgetReady.fire()}}k.setHeight(h.getActualHeight()).setWidth(h.getWidth()).setPreviewMode(gb).setBorderColor(Aa).setBorder(za).setBorderOpacity(Ba).setBorderRadius(cb);S||(c?(Z("welcome_info_name",unescape(v("welcome_info_name"))),Y("expected_tab",c)):k.addContent(h.getContentsDiv()));k.onOrientationChange.addHandler(function(a){"portrait"===a.orientation&&h.setFormat(a.format).setWidth(200).refresh({center:!0});
"landscape"===a.orientation&&h.setHeight(a.height).setWidth(a.width).setFormat(a.format).refresh({center:!0});k.setHeight(h.getActualHeight());k.setWidth(h.getWidth())});k.onShow.addHandler(function(){"object"==typeof h&&k.setWidth(h.getWidth())});k.onBorderWidthChange.addHandler(function(a){"object"===typeof k&&"object"===typeof h&&(h.setBorderRadius(a.radius).refresh(),a=h.getState(),a.borderRadius<a.modalState.borderRadius-a.modalState.borderWidth&&k.setBorderRadius(a.borderRadius+a.modalState.borderWidth))});
k.onBorderRadiusChange.addHandler(function(a){"object"===typeof h&&(h.setBorderRadius(a.radius).refresh(),a=h.getState(),a.borderRadius<a.modalState.borderRadius-a.modalState.borderWidth&&k.setBorderRadius(a.borderRadius+a.modalState.borderWidth))})}function o(a,b){if(!l("customizable_auth_widget_styling"))return!1;if("object"===typeof h)return b(a),!0}function O(a){return o(a,function(a){h.setBackgroundColor(a).refresh()})}function C(a){return o(a,function(a){h.setBorderRadius(a).refresh()})}function L(a){return o(a,
function(a){h.setBorderColor(a).refresh()})}function H(a){return"modal"===A?!1:o(a,function(a){h.setWidth(a).refresh({center:!0})})}function P(a){return o(a,function(a){h.setActionText(a).refresh()})}function U(a){return o(a,function(a){h.setButtonBorderColor(a).refresh()})}function ja(a){return o(a,function(a){h.setButtonBorderRadius(a).refresh()})}function R(a){return o(a,function(a){h.setButtonBackgroundStyle(a).refresh()})}function ra(a){return"modal"==A?!1:o(a,function(a){h.setFormat(a).refresh()})}
function z(a){return o(a,function(a){h.setProvidersPerPage(a).refresh()})}function i(a){return o(a,function(a){h.setFontFamily(a).refresh()})}function sa(a){return o(a,function(a){h.setFontSize(a).refresh()})}function xa(a){return o(a,function(a){h.setFontColor(a).refresh()})}function v(a){var b;if("single cookie"===ga){b=N().getCookie("janrain_engage_login_data");if(!b)return;b=M.parse(b);return!b[a]?void 0:a=b[a]}if("default"===ga)return a=N().getCookie(a),!a?void 0:a}function Ga(a,b,c){var d;if(!a||
!b)return!1;c||(c=1);if("single cookie"===ga)return(oldCookieJSON=N().getCookie("janrain_engage_login_data"))||(oldCookieJSON="{}"),c=M.parse(oldCookieJSON),c[a]=b,d=new N,d.setName("janrain_engage_login_data").setValue(M.stringify(c)).setExpiration(1826).create(),!0;return"default"===ga?(d=new N,d.setName(a).setValue(b).setExpiration(c).create(),!0):!1}function aa(a,b){if(ib)return!1;if("expected_tab"===a&&!b){var c=v("login_tab");c&&aa("expected_tab",c);return!1}if(!b||"undefined"===b||"expected_tab"!==
a&&"expected_user_input"!==a&&"welcome_info_name"!==a)return!1;b="welcome_info_name"===a?escape(b):b;Ga(a,b,1826)}function ua(a,b){var c={};a||(a=xb);b||(b=xb.appUrl);if(f&&3>Oa)return c.widget_type=a.widget_type,c.provider=a.provider,c.time=(new Date).getTime(),c=tb(c),ia(b+"/signin/get_login_info"+c),Oa++,!0;"object"===typeof janrain.events.onProviderLoginCancel&&janrain.events.onProviderLoginCancel.fire(a);"undefined"!==typeof $a&&clearTimeout($a);return!1}function T(a,b,c){var d=b.appUrl+"/"+
a.flow+"/start",e=window.location.href;b.mobileDevice&&(e="mobile");var f=b.language||"en",g=b.popup?"xdr":"xdrsw",h=b.tokenUrl||window.location.href,i={};xb={appUrl:b.appUrl,provider:a.name,widget_type:b.widgetType};i.language_preference=f;i.token_url=h;i.display="popup";i.widget=!0;"object"===typeof b.facebookPermissions&&(i.ext_perm=b.facebookPermissions.toString());i.openid_identifier=a.identifier;i.origin_url=e;i.provider_name=a.name;i.force_reauth=b.forceReauth;i.xdReceiver=b.appUrl+"/"+g;i.callback=
"none";i.widget_type=b.widgetType;i.token_action="url";if("event"===b.tokenAction||"hybrid"===b.tokenAction)i.token_action="event";b.mobileDevice&&"hybrid"===b.tokenAction&&(i.token_action="url");b.bpChannel&&(i.bp_channel=b.bpChannel);b.customOpenid&&"string"===typeof b.customOpenidOpxblob&&(i.opx_blob=b.customOpenidOpxblob);d+=tb(i);(function(){janrain.events.onProviderLoginStart.fire({provider:a.name,width:a.width,height:a.height});var e;b.mobileDevice&&"event"!==b.tokenAction||!b.popup?ia(b.appUrl+
"/signin/set_login_tab?login_tab="+a.name+"&origin_url="+encodeURIComponent(window.location.href),function(){window.top.location.href=d}):(e=new Mb(d),e.setWidth(a.width).setHeight(a.height).setCallback(function(){var d={},e="";d.widget_type=b.widgetType;d.provider=a.name||"";d.time=(new Date).getTime();e=tb(d);"function"===typeof c&&c();ia(b.appUrl+"/signin/get_login_info"+e);janrain.events.onProviderLoginComplete.fire({provider:a.name})}).show())})()}function Z(a,b){if(!b||"undefined"===b||"welcome_info_name"!==
a)return!1;b&&(la=b)}function Y(a,b){function c(){janrain.events.onReturnExperienceFound.fire({returnProvider:b,welcomeName:la})}var d=function(a){var c=function(){600>a&&setTimeout(function(){d(++a)},50)};if("object"!==typeof h)return c(),!1;"modal"===A?k.addContent(h.getReturnExperience(b,la)):"embed"===A&&$(document.getElementById("janrainEngageEmbed"),h.getReturnExperience(b,la));"modal"===A&&janrain.events.onModalWidgetReady.fire()};if("expected_tab"!==a||!b)return!1;"object"===typeof h&&h.removeReturnExperience();
Na?c():janrain.events.onAuthWidgetLoad.addHandler(c);d(0)}function $(a,b){janrain.settings.capture&&(a?a.appendChild(b):(a=document.createElement("div"),a.id="janrainEngageEmbed",a.style.display="none",document.body.appendChild(a)));a?(a.appendChild(b),janrain.events.onAuthWidgetContentPlaced.fire()):(p.log('Missing container div, please place this div where you wantthe embedded widget to be displayed on your page- <div id="janrainEngageEmbed"></div>.'),p.show());return a}function na(a,b){ea=ea||
eb;tokenUrl=b?ea:eb;var c="";if(!bb(tokenUrl).query)var c=c+"?",d=!0;for(var e in a)d?(c+=e+"="+a[e],d=!1):c+="&"+e+"="+a[e];ea=tokenUrl+c}function ca(){e=janrain.settings;if("en"!==janrain.settings.language&&"undefined"===typeof janrain.settings.translate)return setTimeout(ca,5),!1;Db(zb()+"providers.css");f&&9>=f&&Db(zb()+"providers-ie.css");if(e.stop)return!0;Pb&&ia(e.appUrl+"/signin/establish_session");ya=e.tokenAction?e.tokenAction:ya;if(!e.tokenUrl&&"event"===ya)eb=window.location.href;else if(e.tokenUrl)eb=
e.tokenUrl;else return p.log("Missing tokenUrl.  tokenUrl is required."),p.show(),!1;A=r("string",["modal","embed"],"embed",e.type?e.type:A);S=e.multi?e.multi:ub?!0:S;fa=e.custom?e.custom:fa;La=e.forceReauth?e.forceReauth:La;X=e.bpChannel?e.bpChannel:X;Pa=e.facebookPermissions?e.facebookPermissions:Pa;ga=e.storageType?r("string",["default","single cookie"],"default",e.storageType):ga;ka="boolean"===typeof e.popup?e.popup:ka;ub&&"event"!==ya&&(ka=!1);ma=e.returnExperienceTimeout?e.returnExperienceTimeout:
ma;S&&(setTimeout(function(){var a=v("expected_tab");a?(Z("welcome_info_name",unescape(v("welcome_info_name"))),Y("expected_tab",a)):"modal"===A?k.addContent(h.getContentsDiv()):"embed"===A&&(a=document.getElementById("janrainEngageEmbed"),$(a,h.getContentsDiv()))},ma),ia(e.appUrl+"/signin/get_cookies"));if(e.customOpenid&&l("customizable_auth_widget_styling")){Wa=!0;if(!e.customOpenidFlow)return p.log("Missing customOpenidFlow. customOpenidFlow is required when adding a custom openid provider."),
p.show(),!1;if(!e.customOpenidIdentifier)return p.log("Missing customOpenidIdentifier. customOpenidIdentifier is required when adding a custom openid provider."),p.show(),!1;Ha.customopenid={flow:e.customOpenidFlow,identifier:e.customOpenidIdentifier,width:e.customOpenidModalWidth||800,height:e.customOpenidModalHeight||600}}if(fa)return!0;ya=e.tokenAction?e.tokenAction:ya;za=l("customizable_auth_widget_styling")?e.modalBorderWidth:za;Aa=l("customizable_auth_widget_styling")?e.modalBorderColor:Aa;
cb=l("customizable_auth_widget_styling")?e.modalBorderRadius:cb;Ba=l("customizable_auth_widget_styling")?e.modalBorderOpacity:Ba;db=l("customizable_auth_widget_styling")?e.backgroundColor:db;Ca=l("customizable_auth_widget_styling")?e.borderRadius:Ca;Da=l("customizable_auth_widget_styling")?e.borderColor:Da;wa=l("customizable_auth_widget_styling")?e.format:wa;lb=l("customizable_auth_widget_styling")?e.fontColor:lb;jb=l("customizable_auth_widget_styling")?e.fontSize:jb;kb=l("customizable_auth_widget_styling")?
e.fontFamily:kb;va=l("customizable_auth_widget_styling")?e.width:va;W=l("customizable_auth_widget_styling")?e.rowHeight:W;nb=l("customizable_auth_widget_styling")?e.providersPerPage:nb;Va=l("customizable_auth_widget_styling")?e.providersNotPaged:Va;mb=l("customizable_auth_widget_styling")?e.actionText:mb;ob=l("customizable_auth_widget_styling")?e.buttonBorderColor:ob;pb=l("customizable_auth_widget_styling")?e.buttonBorderRadius:pb;qb=l("customizable_auth_widget_styling")?e.buttonBackgroundStyle:qb;
hb=l("customizable_auth_widget_hide_attribution")?e.showAttribution:hb;gb=e.previewMode;ib=e.noReturnExperience;wb=e.noReturnExperienceSwitchAccountLink;da=e.providers;"undefined"===typeof janrain.settings.translate&&(janrain.settings.translate=e.translate={});if(e.customOpenid&&l("customizable_auth_widget_styling")){if(!e.customOpenidLargeIcon)return p.log("Missing customOpenidLargeIcon.  customOpenidLargeIcon is required and should be the full path to an image that is 50px x 50px."),p.show(),!1;
Q={largeIcon:e.customOpenidLargeIcon,customOpenIdProviderName:e.customOpenIdProviderName||janrain.settings.translate.SIGN_IN||"Sign in",customOpenIdProviderColor:e.customOpenIdProviderColor}}e.previewMode?("modal"===A&&(janrain.ready?d():V(window,"load",d)),"embed"===A&&(janrain.ready?c():V(window,"load",c))):("modal"===A&&(janrain.ready?b():V(window,"load",b)),"embed"===A&&(janrain.ready?G():V(window,"load",G)))}var Pa,X,Wa=!1,La=!1,ya="url",eb,ea,A="embed",la="unknown",S=!1,ma=300,La=!1,ka=!0,fa=
!1,ga="default",Q,ha,k,za,Aa,cb,Ba,h,K,db,Ca,Da,va,W,wa,da=[],Va=!1,nb,mb,jb,kb,lb,ob,pb,qb,gb,ib,wb,hb,Za=!1,Na=!1;janrain.events.onAuthWidgetLoad||(janrain.events.onAuthWidgetLoad=D());janrain.events.onModalWidgetReady||(janrain.events.onModalWidgetReady=D());janrain.events.onReturnExperienceFound||(janrain.events.onReturnExperienceFound=D());janrain.events.onAuthWidgetLoad.addHandler(function(){Na=!0});janrain.events.onAuthWidgetLoad.addHandler(function(){"function"===typeof janrainWidgetOnload&&
(fa?janrainWidgetOnload():h?janrainWidgetOnload(h.getState()):janrainWidgetOnload())});for(var $a,Oa=0,xb,yb="onAuthWidgetContentPlaced,onProviderLoginStart,onProviderLoginError,onProviderLoginToken,onProviderLoginCancel,onProviderLoginSuccess,onProviderLoginComplete,onProviderLogoutStart,onProviderLogoutComplete".split(","),rb=0;rb<yb.length;rb++)"undefined"===typeof janrain.events[yb[rb]]&&(janrain.events[yb[rb]]=new Fa);janrain.events.onProviderLoginError.addHandler(function(a){if(fa)return!0;
var b=v("login_tab");if("modal"===A){var c=document.getElementById("janrainModal");c&&c.appendChild(h.getErrorPage(b,a.err))}"embed"===A&&(c=document.getElementById("janrainEngageEmbed"))&&$(c,h.getErrorPage(b,a.err))});ca();return{appendTokenParams:function(a,b){na(a,b)},appendTokenParamsCumulative:function(a){na(a,!0)},setBackplaneChannel:function(a){X=a},setLoginCookie:function(a,b){aa(a,b)},loginHandler:function(a){var b=ya;a?("ok"===a.stat&&("event"===b||"hybrid"===b?ia(a.redirectUrl):(b=document.createElement("form"),
b.action=a.redirectUrl,b.method="POST",janrain.settings.targetTop&&(b.target="_top"),document.body.appendChild(b),b.submit())),"fail"===a.stat&&(a.err&&160===a.err.code?janrain.events.onProviderLoginCancel.fire(a):janrain.events.onProviderLoginError.fire(a),"undefined"!==typeof $a&&clearTimeout($a))):ua()},cancelLogin:function(a){ua(a,e.appUrl);fa||h.removeNotice()},removeNotice:function(){h.removeNotice()},setWelcomeInfoName:function(a,b){Z(a,b)},setReturnExperience:function(a,b){Y(a,b)},setNoReturnExperience:function(a,
b){var c;"boolean"===typeof a&&h?(h.setNoReturnExperience(a),b||h.refresh(),c=!0):c=!1;return c},setNoReturnExperienceSwitchAccountLink:function(a){"boolean"===typeof a&&h?(h.setNoReturnExperienceSwitchAccountLink(a).refresh(),a=!0):a=!1;return a},setPreviewMode:function(a){"boolean"===typeof a&&h?(h.setPreviewMode(a).refresh(),a=!0):a=!1;return a},setConfigureMode:function(a){"boolean"===typeof a&&h?(h.setConfigureMode(a).refresh(),a=!0):a=!1;return a},setCustom:function(a){fa=a},getState:function(){return"object"===
typeof h?h.getState():!1},setProviderFlow:function(b,c){var d;d=!l("customizable_auth_widget_styling")||!fa?!1:a().setProviderFlow(b,c);return d},triggerFlow:function(b){b=!l("customizable_auth_widget_styling")||!fa?!1:a().triggerFlow(b);return b},debugDump:function(){if("undefined"!==typeof console){console.log("-------------START---------------");null!==document.doctype?(console.log("DOCTYPE Name: "+document.doctype.name),console.log("DOCTYPE NodeType: "+document.doctype.nodeType)):console.log("DOCTYPE name: not available (probably quirks mode)");
console.log("User Agent: "+navigator.userAgent);console.log("App Version: "+navigator.appVersion);console.log("Platform: "+navigator.platform);console.log("OS CPU: "+navigator.oscpu);console.log("Language: "+navigator.language);console.log("Release: ");console.log("Web Address: "+location.href);console.log("Cookies Enabled: "+navigator.cookieEnabled);console.log("COOKIES::: "+document.cookie);console.log("AUTH SETTINGS:::");for(var a in janrain.settings)if(console.log(" ---- "+a+": "+janrain.settings[a]),
"object"===typeof janrain.settings[a])for(var b in janrain.settings[a])"function"!==typeof janrain.settings[a][b]&&console.log(" --- --- "+b+": "+janrain.settings[a][b]);console.log("-------------END---------------")}},version:"not sure",widget:{init:function(){c()},setBackgroundColor:function(a){return O(a)},setBorderColor:function(a){return L(a)},setBorderRadius:function(a){return C(a)},setWidth:function(a){return H(a)},setActionText:function(a){return P(a)},setFontFamily:function(a){return i(a)},
setFontSize:function(a){return sa(a)},setFontColor:function(a){return xa(a)},setFormat:function(a){return ra(a)},setButtonBorderColor:function(a){return U(a)},setButtonBorderRadius:function(a){return ja(a)},setButtonBackgroundStyle:function(a){return R(a)},setProviders:function(a){var b;"object"===typeof h&&(t?h.setProviders(a):h.setProviders(a).refresh(),b=!0);return b},setProvidersPerPage:function(a){return z(a)},setShowAttribution:function(a){var b;l("customizable_auth_widget_hide_attribution")?
"object"===typeof h&&h.setShowAttribution(a).refresh():b=!1;return b},refresh:function(){return h.refresh()},getWidth:function(){return h.getWidth()}},modal:{init:function(){d()},close:function(){"object"==typeof k&&k.close()},create:function(){return new Fb},setBorder:function(a){l("customizable_auth_widget_styling")?("object"===typeof k&&(k.setBorder(a),k.refresh({center:!0})),a=!0):a=!1;return a},setBorderColor:function(a){l("customizable_auth_widget_styling")?("object"===typeof k&&(k.setBorderColor(a),
k.refresh()),a=!0):a=!1;return a},setBorderOpacity:function(a){l("customizable_auth_widget_styling")?("object"===typeof k&&(k.setBorderOpacity(a),k.refresh()),a=!0):a=!1;return a},setBorderRadius:function(a){l("customizable_auth_widget_styling")?("object"==typeof k&&(k.setBorderRadius(a),k.refresh()),a=!0):a=!1;return a}}}};var O=new function(){return{status:"not loaded"}},Pa=new function(){return{status:"not loaded"}},Wa=new function(){return{status:"not loaded"}},Rb=new function(){return{status:"not loaded"}};
return{engage:{signin:janrain&&janrain.engage&&janrain.engage.signin?janrain.engage.signin:na,share:janrain&&janrain.engage&&janrain.engage.share?janrain.engage.share:O,publish:janrain&&janrain.engage&&janrain.engage.publish?janrain.engage.publish:Pa,simpleshare:janrain&&janrain.engage&&janrain.engage.simpleshare?janrain.engage.simpleshare:Wa},capture:{ui:Rb}}}();janrain.engage=janrain.apps.engage;janrain.capture=janrain.apps.capture;