/*
 -*- Engage Auth Widget -*-
 Copyright (c) 2012, Janrain, Inc. All rights reserved.
 Version: master
*/
"object"!==typeof window.janrain&&(window.janrain={});janrain.apps={};
janrain.apps=function(){var pa,fa;function wb(){return"http:"===document.location.protocol?"http://cdn.quilt.janrain.com/2.0.18/":"https://d3hmp0045zy3cs.cloudfront.net/2.0.18/"}function Ib(a,e,d){var b;if(document.getElementById(a))return!1;if(f){b="";var za=document.createElement("div");za.innerHTML=b+"<iframe "+('name="'+a+'" ')+('id="'+a+'" ')+('src="'+e+'" ')+'style="display: none;"></iframe>';document.body.appendChild(za)}else b=document.createElement("iframe"),b.setAttribute("name",a),b.id=
a,b.setAttribute("src",e),b.style.display="none",b.className="",document.body.appendChild(b);"function"===typeof d&&d()}function qa(a){for(var e="",e="",d=0;d<a;d++)e+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));return e}function Aa(){function a(a,b,d,e){b={action:a,key:b,messageId:d};"set"===a&&(b.value=e);return"janrainCapture:"+K.stringify(b)}function e(a,b){function d(){e++;if(10<e)return!1;if("undefined"!==typeof c[a])return clearTimeout(g),"get"===c[a].action&&
"function"===typeof b&&b(c[a].storedValue),!0;var g=setTimeout(d,50)}var e=0;d()}function d(b,d){_xdomainStorageIframeLoaded;var g=qa(40);window.setTimeout(function(){f.contentWindow.postMessage(a("get",b,g),Y)});return e(g,d)}function b(a,e){if(g)_xdomainStorageIframeLoaded?d(a,e):setTimeout(function(){b(a,e)},50);else return window.localStorage.getItem(a)}function za(a){var b;if(!(b=0!==a.data.indexOf("janrainCapture:"))){b=A;var d=a.origin.replace(/^https?:\/\/|:\d{1,4}$/g,"").toLowerCase();b=
!(!ga(b)?0:-1<b.indexOf(d))}if(b)return!1;a=K.parse(a.data.replace("janrainCapture:",""));c[a.messageId]=a}var g=!1,c={},f,Y,A=janrain.settings&&janrain.settings.whiteListedDomains?janrain.settings.whiteListedDomains:[];return{setItem:function(b,d){if(g){var c=qa(40);window.setTimeout(function(){f.contentWindow.postMessage(a("set",b,c,d),Y)});return e(c)}return window.localStorage.setItem(b,d)},removeItem:function(b){if(g){var d=qa(40);window.setTimeout(function(){f.contentWindow.postMessage(a("remove",
b,d),Y)});return e(d)}return window.localStorage.removeItem(b)},getItem:b,setMultiDomain:function(a){if(g=a)window.addEventListener?window.addEventListener("message",za,!1):window.attachEvent?window.attachEvent("onmessage",za):document.attachEvent&&document.attachEvent("onmessage",za),f=document.getElementById("xDomainLocalStorageJanrain"),Y=janrain.settings.storageServerDomain}}}function U(){function a(){if(c&&Ba){var a=new Aa;a.setMultiDomain(janrain.settings.multiDomainLocalStorage);a.removeItem(b);
a.removeItem(b+"_Expires")}else{var a=u?"; domain="+u:"",d=new Date;d.setTime(d.getTime()+-864E6);document.cookie=b+"="+g+";expires="+d.toUTCString()+a+"; path="+f}}function e(d,e){var g,u,f,r,Q;if(c&&Ba)if(Q=new Aa,janrain.settings.multiDomainLocalStorage)Q.setMultiDomain(!0),Q.getItem(d,function(g){g?Q.getItem(d+"_Expires",function(h){h?Math.round((new Date).getTime()/1E3)>Math.round((new Date(h)).getTime()/1E3)?(b=d,a(),"function"===typeof e&&e(!1)):"function"===typeof e&&e(g):(new U).getCookie(d+
"_session")?"function"===typeof e&&e(g):(b=d,a())}):"function"===typeof e&&e(!1)});else if(r=Q.getItem(d),g=Q.getItem(d+"_Expires"),r){if(!(g&&Math.round((new Date).getTime()/1E3)>Math.round((new Date(g)).getTime()/1E3))&&(g||(new U).getCookie(d+"_session")))return r;b=d;a()}else return!1;else{g=document.cookie.split(";");u=g.length;for(var x=0;x<u;x++)if(f=g.pop(),r=f.split("="),f=r[0],r=r[1],f.trim()===d)return r;return!1}}var d,b,c=!1,g,u,f="/";return{create:function(){if(c&&Ba){var a=new Aa;a.setMultiDomain(janrain.settings.multiDomainLocalStorage);
a.setItem(b,g);d?a.setItem(b+"_Expires",d):(new U).setName(b+"_session").setValue("session").create()}else document.cookie=b+"="+g+(d?"; expires="+d:"")+(u?"; domain="+u:"")+"; path="+f},remove:a,setExpirationDirectly:function(a){a&&(d=a);return this},setExpiration:function(a){if(a){var b=new Date;b.setTime(b.getTime()+864E5*a);d=b.toUTCString()}return this},setName:function(a){a&&(b=a);return this},setValue:function(a){"undefined"!==typeof a&&(g=a);return this},setUseLocalStorage:function(a){c=a;
return this},setPath:function(a){a&&(f=a);return this},setDomain:function(a){a&&(u=a);return this},getCookie:function(a,b){return e(a,b)}}}function $a(){return"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(O)?parseFloat(RegExp.$1):!1}function V(){var a;return O&&(a=O.match(/(\d)[\d.]+ Safari/))&&a[1]?1*a[1]:0}function V(){return!/Chrome\//.test(O)&&/Safari\//.test(O)}function G(a,e,d,b,c,g){"number"===typeof d&&"number"===typeof b&&"number"===typeof c&&"number"===
typeof g?("undefined"!==typeof a.style.borderRadius&&(a.style.borderRadius=d+"px "+b+"px "+c+"px "+g+"px"),"undefined"!==typeof a.style.MozBorderRadius&&(a.style.MozBorderRadius=d+"px "+b+"px "+c+"px "+g+"px"),"undefined"!==typeof a.style.webkitBorderRadius&&(a.style.webkitBorderRadius=d+"px "+b+"px "+c+"px "+g+"px")):("undefined"!==typeof a.style.borderRadius&&(a.style.borderRadius=e+"px"),"undefined"!==typeof a.style.MozBorderRadius&&(a.style.MozBorderRadius=e+"px"),"undefined"!==typeof a.style.webkitBorderRadius&&
(a.style.webkitBorderRadius=e+"px"));return a}function Ha(a,e){if("undefined"===typeof a||"undefined"===typeof e)return!1;var d=a-e;0>d&&(d=0);d>a&&(d=a);return d}function yb(a,e){if(f&&9>=f)return a.style.backgroundImage="url('"+lb("rel/img/c7a91677d94f4a79e1b26c8ceb31af82.png")+"')",!0;if(V()&&4>=V()||Z.getMobileDevice()){var d="",b="",c="",g=e.split(","),u={top:"left top, left bottom",right:"right top, right bottom",bottom:"left bottom, left top",left:"left top, left bottom"};g[0]&&u[g[0]]&&(d=
u[g[0]]);g[1]&&(b="from("+g[1]+")");g[g.length-1]&&(c="to("+g[g.length-1]+")");a.style.backgroundImage="-webkit-gradient(linear,"+d+","+b+","+c+")"}a.style.backgroundImage="-moz-linear-gradient("+e+")";a.style.backgroundImage="-webkit-linear-gradient("+e+")";a.style.backgroundImage="-ms-linear-gradient("+e+")";a.style.backgroundImage="-o-linear-gradient("+e+")";a.style.backgroundImage="linear-gradient("+e+")"}function Ia(a,e,d,b){var c=Xa(d),g=Xa(d,b);if(d=Kb(d))d.a=b,g="rgba("+d.r+", "+d.g+", "+
d.b+", "+d.a+")";if(0<e){a.style.backgroundColor=c;a.style.padding=e+"px";if(0<f&&8>=f||f&&t)return!1;a.style.backgroundColor=g;a.style.padding=e+"px"}else a.style.backgroundColor="",a.style.padding="0px"}function Kb(a){var e={};if("string"!==typeof a||!a)return!1;a=a.replace(/\s+/g,"");a=a.replace(/,{2,}/g,",");a=a.replace(/[^\d.,]/g,"");a=a.split(",");if(3>a.length||4<a.length)return!1;e.r=a[0];e.g=a[1];e.b=a[2];e.a=a[3]?a[3]:1;return e}function Xa(a,e){var d=a.split("");if("#"!==d[0])return a;
4===a.length&&(a=d[0]+d[1]+d[1]+d[2]+d[2]+d[3]+d[3]);var a=a.substring(1,7),d=parseInt(a.substring(0,2),16),b=parseInt(a.substring(2,4),16),c=parseInt(a.substring(4,6),16);return isNaN(e)?"rgb("+d+","+b+","+c+")":"rgba("+d+","+b+","+c+","+e+")"}function R(a,e,d){if(null==a)return!1;"object"===typeof window.attachEvent?a.attachEvent("on"+e,d):a.addEventListener(e,d,!1)}function ra(a,e,d){"object"===typeof window.detachEvent?a.detachEvent("on"+e,d):a.removeEventListener(e,d,!1)}function Ca(){var a,
e;"undefined"!=typeof window.innerWidth?(a=window.innerWidth,e=window.innerHeight):(a=document.documentElement.offsetWidth,e=document.documentElement.offsetHeight);return{width:a,height:e}}function zb(){return document.documentElement.scrollTop>=document.body.scrollTop?document.documentElement.scrollTop:document.body.scrollTop}function Ab(a){return{width:a.style&&a.style.width?parseInt(a.style.width):a.offsetWidth?parseInt(a.offsetWidth):0,height:a.style&&a.style.height?parseInt(a.style.height):a.offsetHeight?
parseInt(a.offsetHeight):0}}function p(a,e,d,b,c){var g=/^(?:[^\u0000-\u0080]|[-0-9a-z?,.!&\s#()])+$/i,u=/(?:^rgb\s*\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*\)$)|(?:^#[a-f0-9]{1,6}$)/i;if("array"===a){if(!ga(b))return c||m.log(b+" is wrong type, must be array, using default value instead"),d;if(e&&ga(e))for(var f=0;f<b.length;f++)if(0>e.indexOf(b[f]))return c||m.log(b+" is not within the valid range, using default value instead"),d;return b}if("url"===a){if("string"!==typeof b)return d;b&&(b=b.trim());if(/^http(?:s)?:\/\/[-a-z0-9._~@:!$&'()*+,;=\s/?#]+$/i.test(b))return b;
c||m.log(b+" is not the valid format, using default value instead");return d}if("text"===a){if(e){if(0<=e.indexOf(b))return b;c||m.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+d+'" instead');return d}return g.test(b)?b:d}if("usertext"===a){if("string"!==typeof b&&"number"!==typeof b)return d;if(ga(e)){if(1===e.length){if(b.length<=e[0])return b;c||m.log(b+" is too long, using default value instead");return d}if(2===e.length){if(b.length<=
e[1]&&b.length>=e[0])return b;c||m.log(b+" is not within the valid range, using default value instead");return d}c||m.log("usertext range is invalid, using default value instead");return d}return b}"string"===typeof b&&0==b.length&&(b=" ");if(!g.test(b))return c||m.log(b+" contains invalid character(s)"),d;if("boolean"===a){if("boolean"===typeof b)return b;c||m.log(b+" is wrong type, must be boolean, using default value instead");return d}if("text"===a)return b;if("number"===a){if(isNaN(parseInt(b)))return c||
m.log(b+" is wrong type, must be a valid number"),d;b=parseFloat(b)}if("color"===a){b&&(b=b.trim());if("transparent"===b||u.test(b))return b;c||m.log('Value of "'+b+'" for '+arguments.callee.caller.name+' is not a valid value, using default value of "'+d+'" instead');return d}if(typeof b!=a&&"color"!=a)return c||m.log(b+" for "+arguments.callee.caller.name+" is "+typeof b+" expected "+a),d;if("object"===typeof e&&"string"===a){if(0<=e.indexOf(b))return b;c||m.log('Value of "'+b+'" for '+arguments.callee.caller.name+
' is not a valid value, using default value of "'+d+'" instead');return d}if("object"===typeof e&&"number"===a){2===e.length?(g=e[0],u=e[1]):(g=e.shift(),u=e.pop(),f=e);if(b<g)return c||m.log("Value of "+b+" for "+arguments.callee.caller.name+" is below minimum of "+g+", using minimum value of "+g+" instead"),g;if(b>u)return c||m.log("Value of "+b+" for "+arguments.callee.caller.name+" is above maximum of "+u+", using maximum value of "+u+" instead"),u;if(f&&"number"===typeof f.indexOf(b)||b==g||
b==u)return b;return f?(c||m.log("Value of "+b+" for "+arguments.callee.caller.name+" is not a valid value, using default value of "+d+" instead"),d):b}return 0!=b&&!b?d:b}function mb(a){for(var e=mb.options,a=e.parser[e.strictMode?"strict":"loose"].exec(a),d={},b=14;b--;)d[e.key[b]]=a[b]||"";d[e.q.name]={};d[e.key[12]].replace(e.q.parser,function(a,b,c){b&&(d[e.q.name][b]=c)});return d}function Lb(a,e){function d(a){j=!0;"undefined"!==typeof A&&clearTimeout(A);if("string"===typeof a)return"function"===
typeof x&&x(a),!0;if("object"===typeof a||"undefined"===typeof a)return"object"===typeof a&&"error"===a.type?"function"===typeof x&&x(a):"function"===typeof c&&c(),!0}function b(){m++;if(j)return!0;m<g?A=setTimeout(b,50):d("Load Timeout Error")}var c=e,g=200,f=!1,x,m=0,A,E=document.createElement("script"),F=document.getElementsByTagName("script")[0],j=!1;E.src=a;E.setAttribute("type","text/javascript");E.onload=E.onerror=E.onreadystatechange=function(a){!j&&(!this.readyState||"loaded"===this.readyState||
"complete"===this.readyState)&&d(a)};return{setTimeoutCallback:function(a){f=!0;x=a;return this},setCallback:function(a){c=a;return this},setTimeoutLimit:function(a){g=a;return this},load:function(){F.parentNode.insertBefore(E,F);f&&b()}}}function sa(a,e){Lb(a,e).load()}function Bb(a,e){function d(b){m=!1;"function"===typeof e&&e();janrain.events.onCssLoad.fire({source:a,noload:b})}function b(){if(m){for(A=j.length;0<=--A;)if(j[A].href===g.href){d();break}f+=1;m&&(200>f?setTimeout(b,50):d(!0))}}function c(){var a;
try{a=!!g.sheet.cssRules}catch(b){f+=1;200>f?setTimeout(c,50):a&&d(!0);return}d()}var g,f=0,m=!0,j=document.styleSheets,A;"undefined"===typeof janrain.events.onCssLoad&&(janrain.events.onCssLoad=new ta);$?(g=document.createElement("style"),g.innerHTML='@import "'+a+'";'):(g=document.createElement("link"),g.rel="stylesheet",g.href=a,g.type="text/css");Cb||$?(Cb&&b(),$&&c()):(g.onload=function(){d()},g.onerror=function(){d(!0)});document.getElementsByTagName("head")[0].appendChild(g)}function ga(a){return"[object Array]"===
Object.prototype.toString.call(a)}function nb(a){var e="",d;for(d in a)e+="&"+encodeURIComponent(d)+"="+encodeURIComponent(a[d]);return e="?"+e.substr(1)}function ha(a){if(!a)return!1;if(a.preventDefault)a.preventDefault();else try{a.returnValue=!1}catch(e){}}function W(a){if(!a)return!1;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function Db(){function a(a){var a=a||"img",d=document.createElement(a);d.style.position="absolute";d.style.cursor="pointer";d.style.zIndex=1E3;"a"===a?(d.setAttribute("href",
"#"),d.className="janrain_modal_closebutton",ua&&(d.innerHTML=ua)):(d.src=I,U||(d.style.right="-6px",d.style.top="-7px",d.style.height="31px",d.style.width="28px"));d.onclick=K?b:e;return d}function e(a){X||(h.style.display="none",va.style.display="none",z.style.display="none");S&&Z.deactivate();("object"===typeof a||!a)&&janrain.events.onModalClose.fire();("object"===typeof a||!a)&&aa.fire();"object"===typeof a&&ha(a)}function d(){var a=document.createElement("div"),b=document.createElement("div"),
d=document.createElement("a"),c=document.createElement("a"),g=document.createElement("h3");d.innerHTML=Ja;c.innerHTML=wa;g.innerHTML=O;d.setAttribute("href","#");c.setAttribute("href","#");a.className="janrain_close_confirm_container";b.className="janrain_close_confirm";d.className="janrain_modal_confirm";c.className="janrain_modal_cancel";R(d,"click",function(a){e();h.removeChild(T);T=null;ha(a)});R(c,"click",function(a){h.removeChild(T);T=null;ha(a)});b.appendChild(g);b.appendChild(c);b.appendChild(d);
a.appendChild(b);return a}function b(a){T||(T=d(),h.appendChild(T));ha(a)}function c(a){var b=zb(),d=Ab(a),e=-1*d.width/2,d=-1*d.height/2;a.style.left="50%";a.style.marginLeft=e+"px";a.style.marginTop=d+b+"px";a.style.top="50%";0>a.offsetLeft&&(a.style.left=0,a.style.marginLeft=0);0>a.offsetTop&&(a.style.marginTop=0,a.style.top="10px");e=Ca();z.style.height=e.height+b+"px";"absolute"!==a.style.position&&(a.style.position="absolute")}function g(){if(X){var a=document.getElementById("previewMode");
a.style.position="relative";a.appendChild(h)}else c(h);X||m.show()}function u(a){ba||(H=p("number",[0,20],10,a),ca.fire({radius:Ha(P,H)}))}function x(a){ba||(s=p("color",null,"#000000",a))}function Y(a){ba||(P=p("number",[0,20],10,a),xa.fire({radius:Ha(P,H),refresh:!0}))}function A(a){ba||(ia=p("number",[0,1],0.5,a),"object"==typeof h&&Ia(h,H,s,ia))}function E(a){if("portrait"===a){da="portrait";var b="one column"}"landscape"===a&&(da="landscape",b="two column");o.fire({orientation:da,format:b,width:xb,
height:La});g()}function F(a){a&&(Da=a);f&&t&&(Da+=H-2);"object"==typeof h&&(h.style.width=Da+"px");return this}function Jb(a){a&&(ya=a);f&&t&&(ya=ya+2*H-4);a&&"object"==typeof h&&(h.style.height=ya+"px");return this}function r(){pa>=fa&&"undefined"===typeof window.orientation?"landscape"!==da&&E("landscape"):90===window.orientation||-90===window.orientation?"landscape"!==da&&E("landscape"):"portrait"!==da&&E("portrait");g()}function Q(){var a=h,b=Ca(),d=zb();Ab(a);z.style.height=b.height+d+"px"}
var xb=380,La=131,h,Eb="janrainModal",va,z,M,Da=xb,ya=La,H=10,s="#000000",P=10,ia=0.5,K=!1,I=lb("rel/img/b573cd6e318034fa17bb7e9690552ca1.png"),ua="",ba=janrain.settings&&janrain.settings.capture&&janrain.settings.capture.noModalBorderInlineCss,U=!1,O="Are you sure you want to quit?",Ja="Yes, quit",wa="No, stay",T,da="landscape",B=!0,S="boolean"===typeof S?S:"number"===typeof window.orientation?!0:!1,ja="boolean"===typeof ja?ja:janrain.settings.previewMode,X=ja,Pa=Pa||!1;janrain.settings&&janrain.settings.capture&&
janrain.settings.capture.modalCloseImage&&(I=janrain.settings.capture.modalCloseImage,U=!0);janrain.settings&&janrain.settings.capture&&janrain.settings.capture.modalCloseHtml&&(ua=janrain.settings.capture.modalCloseHtml);window.janrain.events.onModalClose||(window.janrain.events.onModalClose=D());window.janrain.events.onModalOpen||(window.janrain.events.onModalOpen=D());var aa=D(),ka=D(),xa=D(),ca=D(),o=D();Z&&Z.onOrientationChange&&Z.onViewportChange&&(Z.onOrientationChange.addHandler(function(a){E(a.orientation)}),
Z.onViewportChange.addHandler(function(){c(h)}));return{isOpen:function(){return"object"===typeof h&&"none"!==h.style.display},setWidth:function(a){F(a);return this},setHeight:function(a){Jb(a);return this},setBorder:function(a){("string"==typeof a||"number"==typeof a)&&u(a);ba||"object"==typeof h&&Ia(h,H,s,ia);return this},setBorderColor:function(a){a&&x(a);ba||"object"==typeof h&&Ia(h,H,s,ia);return this},setBorderRadius:function(a){("string"==typeof a||"number"==typeof a)&&Y(a);ba||"object"==typeof h&&
G(h,P);return this},setBorderOpacity:function(a){("number"===typeof a||"string"===typeof a)&&A(a);return this},setZIndex:function(a){z.style.zIndex=a},setPreviewMode:function(a){"boolean"===typeof a&&(X=a);return this},setId:function(a){Eb=a;h&&(h.id=a);return this},show:function(){S||(h.style.display="block");"object"==typeof va&&B&&(va.style.display="block");X?S&&(h.style.display="block"):(z.style.display="block",S?(Z.setElement(h).activate(),h.style.display="block"):(R(window,"resize",r),R(window,
"resize",Q),R(window,"scroll",Q),r(),Q()));ba||xa.fire({radius:Ha(P,H),refresh:!1});ka.fire();janrain.events.onModalOpen.fire();h.focus()},close:function(a){e(a)},closeConfirm:function(){b()},refresh:function(){Pa||h.appendChild(M);g()},remove:function(){if(X){var a=document.getElementById("previewMode");"object"===typeof M&&h.removeChild(M);"object"===typeof h&&a.removeChild(h);"object"===typeof z&&document.body.removeChild(z);if(a=document.getElementById("janrainEngageEmbed_old"))a.id="janrainEngageEmbed";
z=h=""}else"object"===typeof M&&h.removeChild(M),"object"===typeof z&&document.body.removeChild(z),"object"===typeof h&&document.body.removeChild(h)},addContent:function(b){va=b;if(!h){h=document.createElement("div");h.id=Eb;if("number"===typeof Da||"string"===typeof Da)h.style.width=Da+"px";h.style.height=ya+"px";h.style.position="absolute";ba||(h.style.padding=H+"px",G(h,P),Ia(h,H,s,ia));h.style.zIndex=1E3;h.style.display="none";z=document.createElement("div");janrain.settings&&janrain.settings.capture&&
janrain.settings.capture.captureServer&&(z.id="janrainModalOverlay");z.style.width="100%";z.style.left=0;z.style.top=0;z.style.backgroundColor="#000000";z.style.position="absolute";b=z;"undefined"!==typeof b.style.filter&&(b.style.filter="alpha(opacity=40)");"undefined"!==typeof b.style.opacity&&(b.style.opacity="0.4");"undefined"!==typeof b.style.KhtmlOpacity&&(b.style.KhtmlOpacity="0.4");"undefined"!==typeof b.style.MozOpacity&&(b.style.MozOpacity="0.4");z.style.display="none";z.style.zIndex=1E3;
M=ua?a("a"):a();h.appendChild(M);document.body.appendChild(z);document.body.appendChild(h)}h.appendChild(va);X&&g();return this},getContent:function(){return va},getBorderWidth:function(){return H},getState:function(){return{borderWidth:H,borderColor:s,borderRadius:P,borderOpacity:ia,orientation:da}},setState:function(a){j("customizable_auth_widget_styling")&&("undefined"!==typeof a.borderWidth&&u(a.borderWidth),"undefined"!==typeof a.borderColor&&x(a.borderColor),"undefined"!==typeof a.borderOpacity&&
A(a.borderOpacity),"undefined"!==typeof a.orientation&&E(a.orientation),"undefined"!==typeof a.borderRadius&&(("string"==typeof a.borderRadius||"number"==typeof a.borderRadius)&&Y(a.borderRadius),"object"==typeof h&&G(h,P)))},setConfirmClose:function(a){K=a;return this},setShowContentOnLoad:function(a){B=a;return this},setConfirmMessageText:function(a){O=a},setConfirmLinkText:function(a){Ja=a},setCancelLinkText:function(a){wa=a},onClose:aa,onShow:ka,onOrientationChange:o,onBorderRadiusChange:xa,onBorderWidthChange:ca}}
function Mb(a){function e(){var a=window.open(d,"","width="+b+", height="+c+", status=1, location=1, resizable=yes"),e=window.setInterval(function(){if(a&&a.closed||a&&"undefined"===typeof a.closed||"undefined"===typeof a)window.clearInterval(e),"function"===typeof g&&g()},500)}var d=a,b=400,c=400,g;return{show:function(){e()},setWidth:function(a){a&&(b=a);return this},setHeight:function(a){a&&(c=a);return this},setCallback:function(a){a&&(g=a);return this}}}function Nb(){function a(){F=(new Date).getTime()-
b;if(F<d){var a=Math.round(e()*A+f);c.style[j]=a+"px"}else clearInterval(E),c.style[j]=m+"px",r()}function e(){if("flat"==p)return F*(1/d);if("sinusoidal"==p)return Math.abs(Math.sin(F*(Math.PI/(2*d))))}var d="1000",b,c,g=document,f,m,j="left",A,E,F,p="flat",r;return{setAcceleration:function(a){p=a;return this},setCallback:function(a){r=a;return this},setDuration:function(a){d=a;return this},setDirection:function(a){"horizontal"===a&&(j="left");"vertical"===a&&(j="top");return this},setElement:function(a){c=
a;return this},setElementBoundry:function(a){g=a;return this},startPosition:function(a){f=a;return this},endPosition:function(a){m=a;return this},animate:function(){A=m-f;b=(new Date).getTime();E=setInterval(a,10);return this},drag:function(a){function b(a){var d=Fb({event:a,boundry:g});c.style.left=d.x()+"px";W(a);ha(a)}function d(a){var e=Fb({event:a,boundry:g});c.style.left=e.x()+"px";ra(document,"mouseup",d);ra(document,"mousemove",b);W(a);ha(a);r({pos_x:e.x()})}R(document,"mousemove",b);R(document,
"mouseup",d);W(a);ha(a)}}}function Fb(a){return{x:function(){var e,d=a.event.clientX;var b=a.boundry,c=curtop=0;if(b.offsetParent){do c+=b.offsetLeft,curtop+=b.offsetTop;while(b=b.offsetParent);e=c}e=d-e;e=e<this.boundry_x()?e:this.boundry_x();return 0<e?e:0},boundry_x:function(){return a.boundry.getBoundingClientRect().width},y:function(){},boundry_y:function(){}}}function D(){return new ta}function ta(){this.eventHandlers=[];this.firedEvents=[]}function Gb(){if(function(){if("object"!==typeof janrain.events||
"object"!==typeof janrain.apps.engage||"object"!==typeof janrain.apps.engage.signin)return!1;if(!0===janrain.settings.custom)return!0;for(var a="onAuthWidgetLoad,onCustomizationChange,onProviderLoginComplete,onProviderLoginCancel,onProviderLoginError,onProviderLoginStart,onProviderLoginSuccess,onProviderLoginToken,onReturnExperienceFound,onModalWidgetReady".split(","),d=0;d<a.length;d++)if("object"!==typeof janrain.events[a[d]])return!1;return!0}())clearTimeout(a),janrain.events.onAuthWidgetLoad.fire();
else var a=setTimeout(Gb,5)}Array.prototype.indexOf||(Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var e=Object(this),d=e.length>>>0;if(0===d)return-1;var b=0;0<arguments.length&&(b=Number(arguments[1]),b!=b?b=0:0!=b&&Infinity!=b&&-Infinity!=b&&(b=(0<b||-1)*Math.floor(Math.abs(b))));if(b>=d)return-1;for(b=0<=b?b:Math.max(d-Math.abs(b),0);b<d;b++)if(b in e&&e[b]===a)return b;return-1});Array.prototype.map||(Array.prototype.map=function(a,e){if(null===this)throw new TypeError;
var d=Object(this),b=d.length>>>0;if("function"!==typeof a)throw new TypeError;for(var c=Array(b),g=0;g<b;g++)g in d&&(c[g]=a.call(e,d[g],g,d));return c});Array.prototype.filter||(Array.prototype.filter=function(a,e){if(null==this)throw new TypeError;var d=Object(this),b=d.length>>>0;if("function"!=typeof a)throw new TypeError;for(var c=[],g=0;g<b;g++)if(g in d){var f=d[g];a.call(e,f,g,d)&&c.push(f)}return c});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,
"")});var I=window.innerWidth?window.innerWidth:document.body&&document.body.clientWidth?document.body.clientWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:0;fa=window.innerHeight?window.innerHeight:document.body&&document.body.clientHeight?document.body.clientHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:0;pa=I;var Ba=window.localStorage&&window.localStorage.getItem&&window.localStorage.removeItem&&
window.localStorage.setItem,t="CSS1Compat"!==document.compatMode,ab=!1,s=!1,c=[],I=navigator.userAgent.toLowerCase().match(/(iphone|ipod|ipad|blackberry|rim tablet|android|htc|lg|midp|mmp|mobile|nokia|opera mini|palm|pocket|psp|sgh|smartphone|symbian|treo mini|playstation portable|sonyericsson|samsung|mobileexplorer|palmsource|benq|windows phone|windows mobile|iemobile|windows ce|nintendo wii|\Wsilk\W)/i),ob=null!==I?I[0]:!1,Ob="number"===typeof window.orientation||null!==I;janrain.settings&&janrain.settings.storageServer&&
Ib("xDomainLocalStorageJanrain",janrain.settings.storageServer,function(){R(document.getElementById("xDomainLocalStorageJanrain"),"load",function(){_xdomainStorageIframeLoaded=!0})});var O=navigator.userAgent,f=$a(),$=/Gecko\//.test(O),Cb=/AppleWebKit\//.test(O);/Chrome\//.test(O);V();var j=function(){var a=function(a){for(var b=[],e=0;e<a.length;e++)b.push(a[e]);return b},e={};janrain.settings&&janrain.settings.permissions&&(e.login=a(janrain.settings.permissions));janrain.settings&&janrain.settings.share&&
janrain.settings.share.permissions&&(e.share=a(janrain.settings.share.permissions));return function(a,b){b=b||"login";return!e[b]?!1:0<=e[b].indexOf(a)}}();mb.options={strictMode:!1,key:"source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(","),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};for(var Z=function(){function a(){if("undefined"===typeof window.orientation)return!1;var a;b(document.body,F);E=f().content;m();j();document.body.style.padding="0px";document.body.style.margin="0px";"object"===typeof window.onresize&&(a="resize");"object"===typeof window.onorientationchange&&(a="orientationchange");
a&&(window.addEventListener(a,function(){La(window.orientation,{height:screen?screen.height:0,width:screen?screen.width:0},{height:window.innerHeight,width:window.innerWidth});g()},!1),setTimeout(g,30),window.addEventListener("beforeunload",function(){window.removeEventListener(a,g,!1)},!1));t.addHandler(function(){e({height:window.innerHeight,width:window.innerWidth},0)});s.addHandler(function(a){fa=a.height;pa=a.width});window.addEventListener("beforeunload",function(){window.removeEventListener(eventName,
g,!1)},!1)}function e(a,b){var d=window.innerHeight,c=window.innerWidth,g=!0,f=!0;d!=a.height&&(g=!1);c!=a.width&&(f=!1);g&&f?20>b?setTimeout(function(){e({height:d,width:c},++b)},100):s.fire({height:d,width:c}):setTimeout(function(){e({height:d,width:c},0)},100)}function d(){setTimeout(function(){A(E)},20);b(F,document.body)}function b(a,b){for(var d=0;d<a.style.length;d++){var e=a.style[d];b.style.setProperty(e,a.style.getPropertyValue(e),a.style.getPropertyPriority(e))}}function c(){var a;a=(0===
window.orientation||180===window.orientation)&&pa>fa||(90===window.orientation||-90===window.orientation)&&fa>pa?!1:!0;var b="landscape";if(a&&(0===window.orientation||180===window.orientation))b="portrait";if(!a&&(90===window.orientation||-90===window.orientation))b="portrait";return b}function g(){var a=c();A("width=device-width, initial-scale=1, maximum-scale=1");t.fire({orientation:a})}function f(){var a=document.getElementsByTagName("meta"),b;for(b in a)if("viewport"===a[b].name)return a[b];
return!1}function m(){if("undefined"===typeof document.getElementsByTagName||f())return!1;var a=document.getElementsByTagName("head")[0],b=document.createElement("meta");b.setAttribute("name","viewport");a.appendChild(b);return!0}function j(){if("undefined"===typeof document.getElementsByTagName)return!1;document.getElementsByTagName("head");var a=document.createElement("meta");a.setAttribute("name","HandheldFriendly");a.content="true"}function A(a){var b=f();if(!b||b.content==a)return!1;if("undefined"===
typeof a){var d=f();document.getElementsByTagName("head")[0].removeChild(d)}b.content=a;return!0}var E,F=document.createElement("div"),p=navigator.userAgent.toLowerCase().match(/(iphone|ipod|ipad|blackberry|rim tablet|android|htc|lg|midp|mmp|mobile|nokia|opera mini|palm|pocket|psp|sgh|smartphone|symbian|treo mini|playstation portable|sonyericsson|samsung|mobileexplorer|palmsource|benq|windows phone|windows mobile|iemobile|windows ce|nintendo wii|\Wsilk\W)/i),r=null!==p?p[0]:!1,t=D(),s=D();r&&r[0].match(/android|\Wsilk\W/);
var La=function(){var a=window.orientation,b={height:screen?screen.height:0,width:screen?screen.width:0},d={height:window.innerHeight,width:window.innerWidth},e=!1;return function(c,g,f){var m=!1,j=function(a,b){return a.height>=a.width&&b.height>=b.width||a.width>a.height&&b.width>b.height?!0:!1},A=a===c,F=j(g,b),r=j(f,d);if(!A&&(!F||!r))m=!0;!A&&!F&&(e=!0);m&&(e&&!j(g,f)&&(m=f.height,f.height=f.width,f.width=m),fa=f.height,pa=f.width);a=c;b={height:g.height,width:g.width};d={height:f.height,width:f.width}}}();
return{setElement:function(){return this},onOrientationChange:t,onViewportChange:s,getMobileDevice:function(){return r},getOrientation:function(){return c()},activate:function(){a()},deactivate:function(){d()}}}(),lb=function(a){var e;e="https:"===document.location.protocol?"https://docj27ko03fnu.cloudfront.net/":"http://cdn.rpxnow.com/";e=e.replace(/\/$/,"");return e+"/"+a},I={openId:{aol:{identifier:"aol",flow:"openid1",width:514,height:550,color:"#0FD6FF"},blogger:{identifier:"blogger",flow:"openid1",
width:800,height:600,color:"#FF6600"},livejournal:{identifier:"livejournal",flow:"openid1",width:800,height:600,color:"##213368"},netlog:{identifier:"netlog",flow:"openid1",width:800,height:600,color:"#000000"},wordpress:{identifier:"wordpress",flow:"openid1",width:800,height:600,color:"#21759b"},openid:{identifier:"openid",flow:"openid1",width:800,height:600,color:"#f79311"}},openId2:{flickr:{identifier:"https://me.yahoo.com/id",flow:"openid",width:500,height:500,color:"#FF0084"},google:{identifier:"https://www.google.com/accounts/o8/id",
flow:"openid",width:500,height:450,color:"#1C69F5"},hyves:{identifier:"http://hyves.nl/",flow:"openid",width:800,height:600,color:"#659BC8"},myopenid:{identifier:"http://myopenid.com/",flow:"openid",width:800,height:600,color:"#8cc63f"},paypal:{identifier:"https://www.paypal.com/webapps/auth/server",flow:"openid",width:800,height:600,color:"#1A3665"},verisign:{identifier:"http://pip.verisignlabs.com/",flow:"openid",width:945,height:600,color:"#B8004D"},yahoo:{identifier:"https://me.yahoo.com/id",
flow:"openid",width:500,height:500,color:"#650065",shareSettings:{broadcast:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}}},oauth:{facebook:{flow:"facebook",width:1050,height:550,color:"#3B5998",publishSettings:{},shareSettings:{broadcast:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,media:!0,actionLink:!0}},contact:{counter:{},format:{},features:{message:!0,title:!0,url:!0,
description:!0,image:!0,media:!0,actionLink:!0}}}},myspace:{flow:"myspace",width:800,height:500,color:"#000000",shareSettings:{broadcast:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},twitter:{flow:"twitter",width:800,height:500,color:"#35CCFF",shareSettings:{broadcast:{counter:{max:140,urlRegex:/\b(?:[a-z]{1}[-a-z0-9+.]+:(?:\/\/)?)?[-a-z0-9._~@:!$&'()*+,;=]+(?:\.[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\.(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx))(?::\d+)?(?:\/[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\?[-a-z0-9._~@:!$&'()*+,;=%]+)?(?:#[-a-z0-9._~@:!$&'()*+,;=%]+)?\b/ig,
urlLength:23},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}},contact:{counter:{max:140,urlRegex:/\b(?:[a-z]{1}[-a-z0-9+\.]+:(?:\/\/)?)?[-a-z0-9._~@:!$&'()*+,;=]+(?:\.[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\.(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx))(?::\d+)?(?:\/[-a-z0-9._~@:!$&'()*+,;=]+)*(?:\?[-a-z0-9._~@:!$&'()*+,;=%]+)?(?:#[-a-z0-9._~@:!$&'()*+,;=%]+)?\b/ig,urlLength:23},
format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},linkedin:{flow:"linkedin",width:550,height:750,color:"#006699",shareSettings:{broadcast:{counter:{},format:{},features:{message:!0,title:!0,url:!0,description:!0,image:!0,media:!1,actionLink:!1}},contact:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},live_id:{flow:"liveid",width:900,height:600,
color:"#666666"},salesforce:{flow:"salesforce",width:800,height:500,color:"#333333"},orkut:{flow:"orkut",width:800,height:600,color:"#333"},vzn:{flow:"vzn",width:600,height:450,color:"#333"},foursquare:{flow:"foursquare",width:950,height:550,color:"#333"},sinaweibo:{flow:"sinaweibo",width:950,height:550,color:"#333"},renren:{flow:"renren",width:950,height:550,color:"#333"},soundcloud:{flow:"soundcloud",width:950,height:550,color:"#333"},mixi:{flow:"mixi",width:950,height:550,color:"#333",shareSettings:{broadcast:{counter:{},
format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}},contact:{counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!0,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}},email:{color:"#009ddc",shareSettings:{email:{providers:{google:!0,yahoo:!0},counter:{},format:{message:"#{MESSAGE} #{URL}"},features:{message:!0,title:!1,url:!1,description:!1,image:!1,media:!1,actionLink:!1}}}}}},Ya={},Qa=["openId",
"openId2","oauth"];0<Qa.length;){var la=Qa.pop(),Ra;for(Ra in I[la])Ya[Ra]=I[la][Ra]}var m=function(){var a=[];return{log:function(e){var d={};d.id=a.length+1;d.message=e;a.push(d);return this},show:function(){if(0!=a.length){for(var e in a)if("undefined"!==typeof a[e].id){var d=a[e];"object"===typeof console&&("function"===typeof console.error?console.error("WARNING ID:"+d.id+" MESSAGE: "+d.message):"function"===typeof console.log&&console.log("WARNING ID:"+d.id+" MESSAGE: "+d.message))}a=[]}}}}();
ta.prototype.addHandler=function(a){this.eventHandlers.push(a);return this.eventHandlers.length-1};ta.prototype.removeHandler=function(a){return this.eventHandlers[a]?(this.eventHandlers[a]=null,!0):!1};ta.prototype.fire=function(a){for(var e=this.eventHandlers.length,d=0;d<e;d++)try{if("function"===typeof this.eventHandlers[d])this.eventHandlers[d](a)}catch(b){m.log(b),m.show()}this.firedEvents.push({event:this,args:a})};"undefined"===typeof janrain.events&&(janrain.events={});var K;K||(K={});(function(){function a(a){return 10>
a?"0"+a:a}function e(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var b=m[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,b){var c,m,r,p,t=g,s,h=b[a];h&&"object"===typeof h&&"function"===typeof h.toJSON&&(h=h.toJSON(a));"function"===typeof j&&(h=j.call(b,a,h));switch(typeof h){case "string":return e(h);case "number":return isFinite(h)?""+h:"null";case "boolean":case "null":return""+h;case "object":if(!h)return"null";
g+=f;s=[];if("[object Array]"===Object.prototype.toString.apply(h)){p=h.length;for(c=0;c<p;c+=1)s[c]=d(c,h)||"null";r=0===s.length?"[]":g?"[\n"+g+s.join(",\n"+g)+"\n"+t+"]":"["+s.join(",")+"]";g=t;return r}if(j&&"object"===typeof j){p=j.length;for(c=0;c<p;c+=1)"string"===typeof j[c]&&(m=j[c],(r=d(m,h))&&s.push(e(m)+(g?": ":":")+r))}else for(m in h)Object.prototype.hasOwnProperty.call(h,m)&&(r=d(m,h))&&s.push(e(m)+(g?": ":":")+r);r=0===s.length?"{}":g?"{\n"+g+s.join(",\n"+g)+"\n"+t+"}":"{"+s.join(",")+
"}";g=t;return r}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,f,m={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;"function"!==typeof K.stringify&&(K.stringify=function(a,b,c){var e;f=g="";if("number"===typeof c)for(e=0;e<c;e+=1)f+=" ";else"string"===typeof c&&(f=c);if((j=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return d("",{"":a})});
"function"!==typeof K.parse&&(K.parse=function(a,d){function c(a,b){var e,g,f=a[b];if(f&&"object"===typeof f)for(e in f)Object.prototype.hasOwnProperty.call(f,e)&&(g=c(f,e),void 0!==g?f[e]=g:delete f[e]);return d.call(a,b,f)}var e,a=""+a;b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof d?c({"":e},""):e;throw new SyntaxError("JSON.parse");})})();janrain.events.onCustomizationChange||(janrain.events.onCustomizationChange=D());janrain.events.onProviderLoginStart||(janrain.events.onProviderLoginStart=D());janrain.events.onProviderLoginComplete||(janrain.events.onProviderLoginComplete=D());janrain.events.onProviderLoginError||(janrain.events.onProviderLoginError=D());janrain.events.onProviderLoginSuccess||
(janrain.events.onProviderLoginSuccess=D());janrain.events.onProviderLoginToken||(janrain.events.onProviderLoginToken=D());janrain.events.onProviderLogoutStart||(janrain.events.onProviderLogoutStart=D());janrain.events.onProviderLogoutComplete||(janrain.events.onProviderLogoutComplete=D());Gb();Ra=new function(){function a(){function a(){return{twoColumn:{actionText:"Sign in using your account with",providersPerPage:6},oneColumn:{actionText:"Sign in with",width:200},oneRow:{actionText:"Sign in with"},
footerHeight:10,headerHeight:20}}function b(){if(ma){var a=document.createElement("div");a.style.backgroundColor=Y?"aqua":Ka;a.style.width=y+"px";a.style.height=La+"px";a.style.position="absolute";a.style.left="0px";a.style.paddingLeft=n+"px";a.style.paddingRight=n+"px";a.style.paddingBottom=n+"px";a.style.bottom="0px";a.style.fontSize="10px";a.style.textAlign="left";a.style.color=W;G(a,null,0,0,v,v);var k=document.createElement("div");k.appendChild(document.createTextNode(janrain.settings.translate.POWERED_BY_PREFIX||
"Powered by "));k.style.paddingLeft="1px";var c=document.createElement("a");c.setAttribute("href","http://www.janrain.com/products/engage/engage-introduction?utm_source=login.janrain.com&utm_medium=partner&utm_campaign=attribution");c.setAttribute("target","_blank");c.appendChild(document.createTextNode("Janrain"));k.appendChild(c);a.appendChild(k);Va=a}w=g();a=document.createElement("div");a.style.backgroundColor=Y?"orange":Ka;a.className="janrainHeader";a.style.fontSize=$+"px";a.style.color=W;a.style.position=
"relative";a.style.height=na+"px";40===oa&&(a.style.cssFloat="left");a.style.left=40===oa?"-6px":"-5px";a.style.paddingLeft=n+"px";a.style.paddingRight=n+"px";a.style.paddingTop=n+"px";a.style.paddingBottom="0px";a.style.whiteSpace="nowrap";a.style.width=40===oa?"81px":y+"px";a.style.zIndex="100";40===oa?G(a,null,v,0,0,v):G(a,null,v,v,0,0);40===oa&&(a.style.marginTop="-3px");a.style.textAlign="one column"===l?"center":"left";k=e();ca=document.createElement("div");ca.style.paddingLeft="1px";ca.style.fontFamily=
V;" "!==k&&ca.appendChild(document.createTextNode(k));a.appendChild(ca);Ua=a;q=document.createElement("div");q.className="janrainContent";q.style.width=y+"px";q.style.height=i()+"px";q.style.paddingLeft=n+"px";q.style.paddingRight=n+"px";q.style.boxSizing="content-box";40===oa&&(q.style.paddingTop=n-1+"px");s||(q.style.backgroundColor=Ka);s||(q.style.border=za?"1px solid "+ua:"1px solid "+Ka);q=G(q,v);s||(q.style.overflow="hidden");q.style.position=za?"relative":"absolute";Wa=A();2==w||0==w?(Ea=(new u).setSide("right").create(),
Fa=(new u).setSide("left").create()):(Ea=(new u).setSide("top").create(),Fa=(new u).setSide("bottom").create());a=document.createElement("div");a.id="janrainView";" "!==e()&&a.appendChild(Ua);k=F("blank");k.style.display="none";a.appendChild(k);a.appendChild(Wa);!s&&Ea&&Fa&&(a.appendChild(Ea),a.appendChild(Fa));0<w&&ma&&a.appendChild(Va);q.appendChild(a);j("customizable_auth_widget_styling")||d(q);ab||m.show()}function d(a){function b(a){var k="string"===typeof a.getAttribute("style")?a.getAttribute("style"):
null;k&&(k.cssText&&(k=k.cssText),a.style.setAttribute?a.style.setAttribute("cssText",k.replace(/(((?!!important).)+?);/g,"$1 !important;")):a.setAttribute("style",k.replace(/(((?!!important).)+?);/g,"$1 !important;")))}for(var k=a.getElementsByTagName("*"),c=0,e=k.length;c<e;c++)"janrainProviderPages"===k[c].id||"janrainSlideControl"===k[c].className||"janrainSlideControl"===k[c].parentNode.className||b(k[c]);b(a)}function e(){return Ba?N:c.translate.HEADER?c.translate.HEADER:"two column"===l?a().twoColumn.actionText:
"one column"===l?a().oneColumn.actionText:"one row"===l?a().oneRow.actionText:N}function g(){var a=l;if("default"==a||"two column"==a)return 2;if("one column"==a)return 1;if("one row"==a)return 0}function i(){var a=" "===N?0:na+n,b=ma&&"one row"!==l?La+n:0;return r()+a+b}function h(){var a=parseInt(Wa.style.left),b=parseInt(Wa.style.top),k;1==w?parseInt(Wa.style.height):parseInt(Wa.style.width);2==w&&(k=(y-3*n-(2==w?10:0))/w);if("one column"===l){if(" "===N&&(b+=11,0<b||-9<=b))return 0;if(9>b)return 1;
if(0<b||b>=-(na-(n+1)))return 0}0==w&&(k=y-100);if(0>a&&a<-k)return 1;if(0<a||a>=-n)return 0}function r(){if("two column"===l)var a=J/2;"one column"===l&&(a=J);"one row"===l&&(a=1);var b="one row"===l?0:2*a,k="one column"===l?3*n:0;if(7===f||6===f||f&&t){if("two column"===l&&(k=n,7===f||6===f))k=2*n;if("one column"===l&&(k=3*n,(7===f||6===f)&&!t))k+=n;if("one row"===l&&(7===f||6===f))k=n}"one column"===l&&Ga<=J&&(k=f&&t?k+2*n:k-2*n);return C*a+n*(a+1)+b+k}function u(){function a(){var b;i="over";
var Sa=h();if(0==Sa&&"left"===c||0==Sa&&"top"===c||1==Sa&&"right"===c||1==Sa&&"bottom"===c)return this.style.cursor="default",j.onclick="",!1;var e=this;setTimeout(function(){if(1===m){if("over"!==i)return!1;f&&(d.style.display="block");g.style.display="block";j.onclick=k;e.style.cursor="pointer";var a=document.getElementById("janrainProviderPages");b="top"==c||"bottom"==c?parseInt(a.style.top):parseInt(a.style.left);var Sa="right"===c||"bottom"===c?b-Ha:b+Ha;"top"===c||"bottom"===c?a.style.top=Sa+
"px":a.style.left=Sa+"px";m=2}},f?50:100)}function b(){var a;i="out";var k=h();if(1==k&&"right"===c||0==k&&"left"===c||0==k&&"top"===c||1==k&&"bottom"===c)return!1;setTimeout(function(){if(2===m){if("out"!==i)return!1;f&&(d.style.display="none");g.style.display="none";var b=document.getElementById("janrainProviderPages");a="top"==c||"bottom"==c?parseInt(b.style.top):parseInt(b.style.left);var k="right"===c||"bottom"===c?a+Ha:a-Ha;"top"===c||"bottom"===c?b.style.top=k+"px":b.style.left=k+"px";m=1}},
f?200:400)}function k(){g.style.display="none";j.style.cursor="default";x(c,function(a){z(a);m=1})}var d,c,e,g,ea={left:"-33px -16px",right:"0px -16px",top:"-16px -33px",bottom:"-16px 0px"},i="",m=1,j;return{setSide:function(a){c=a;return this},create:function(){var f;if(Ga<=J)f=!1;else{f=document.createElement("div");f.setAttribute("id","janrainShim_"+c);f.style.background="black";"top"===c||"bottom"===c?(f.style.height="19px",f.style.width="100%"):(f.style.height="100%",f.style.width="17px");f.style.filter=
Y?"alpha(opacity=100)":"alpha(opacity=0)";f.style.position="absolute";f.style.zindex="99";if("top"===c||"bottom"===c)f.style.left="0";f.style[c]=n+"px";f.style.top="one column"!==l?n+1+"px":"top"===c?"10px":"0px";f.style.display="none";d=f;f=document.createElement("div");f.style.backgroundColor=Y?"green":Ka;f.className="janrainSlideControllerMask";f.style.position="absolute";"one column"!==l&&(f.style.width=n+"px",f.style.height="100%",f.style.top="0px",f.style[c]="0px",f.style.borderWidth="1px",
"right"===c&&(!ma||"one row"===l)&&G(f,null,0,0,v,0),"left"===c&&(!ma||"one row"===l)&&G(f,null,0,0,0,v),"right"===c&&" "===N&&G(f,null,0,v,v,0),"left"===c&&" "===N&&G(f,null,v,0,0,v));"one column"===l&&(f.style.height=n+"px",f.style.fontSize="0px",f.style.width="100%",f.style.padding="0px",f.style[c]="0px","top"===c&&" "===N?G(f,null,v,v,0,0):"bottom"===c&&!ma&&G(f,null,0,0,v,v));"one row"===l&&(f.style.height="105.5%");e=f;f=document.createElement("div");f.setAttribute("id","janrainArrow_"+c);f.style.background=
"url("+lb("rel/img/ee9d3aa7c5896c69488b5941ef31c7bc.png")+") no-repeat scroll "+ea[c]+" transparent";f.style.height="19px";f.style.width="17px";f.style.position="absolute";if("top"===c||"bottom"===c)f.style.left=y/2+"px";f.style[c]=n+"px";f.style.top="one column"!==l?r()/2-2*n+1+"px":"top"===c?"10px":"0px";f.style.display="none";g=f;f=document.createElement("div");f.className="janrainSlideControl";f.style.backgroundColor=Y?"purple":"transparent";"one column"===l?(f.style.width=y+4+"px",f.style.left=
"3px","top"==c?(f.style.height=n+"px",f.style.top=na+n+"px"," "===N&&(f.style.left="0px",f.style.width=y+10+"px")):(f.style.height="20px",f.style.bottom=(ma?La+n:0)+"px",G(f,null,0,0,v,v))):(f.style.width="right"===c?"20px":"0px",f.style[c]="0px",f.style.height=r()-(n*(" "===N)?1:2)+"px",40===oa&&"one row"===l&&"left"===c&&(f.style.left=Ca+"px"),"right"===c&&!ma&&G(f,null,0,0,v,0),"left"===c&&!ma&&G(f,null,0,0,0,v));f.style.position="absolute";f.style.zIndex="100";f.style.cursor="pointer";f.onmouseover=
a;f.onmouseout=b;f.onclick=k;j=f;j.appendChild(e);j.appendChild(d);j.appendChild(g);f=j}return f}}}function x(a,b){var k=document.getElementById("janrainProviderPages"),c=new Nb;if("top"===a||"bottom"===a){if(" "===N)var d=-(r()-C),e=0;else d=-(r()-C-na-n),e=na+n;50===C&&(d-=20);f&&t&&(d+=n," "!==N&&(e+=n));c.setElement(k).setAcceleration("sinusoidal").setDuration(100*J).startPosition(parseInt(k.style.top)).endPosition("bottom"===a?d:e).setDirection("vertical").setCallback(function(){b(a)}).animate()}else f&&
t?(d=-(y-2*n-39),"one row"===l&&(d=-(Ca-1*n))):(d=-(y-32),"one row"===l&&(d=-(y-24))),c.setElement(k).setAcceleration("sinusoidal").setDuration(800).startPosition(parseInt(k.style.left)).endPosition("right"==a?d:n).setDirection("horizontal").setCallback(function(){b(a)}).animate()}function A(){var a,b;function k(c){c.preventDefault();c=c.touches[0];c="one column"===l?a-c.pageY:b-c.pageX;if(35<c||-35>c)"one column"===l?(d.style.top=parseInt(d.style.top)-c+"px",c=0<c?"bottom":"top"):(d.style.left=parseInt(d.style.left)-
c+"px",c=0<c?"right":"left"),x(c,function(){z()}),d.ontouchmove=""}var c,d,e,g,ea,i=w,h=[];g=E();ea=s?1:Math.ceil(Ga/J);2<ea&&m.log("Either reduce the number of providers, or increase the setting for providersPerPage.");d=document.createElement("div");d.setAttribute("id","janrainProviderPages");s&&(d.className="janrainConfigureMode");d.style.paddingTop=(6===f||7===f)&&f&&t?2*n:n+"px";if((6===f||7===f)&&!t)d.style.paddingTop=n+4+"px";d.ontouchstart=function(c){c=c.touches[0];"one column"===l?a=c.pageY:
b=c.pageX};d.ontouchmove=k;d.ontouchend=function(){d.ontouchmove=k};40===oa&&"one row"===l?d.style.left=Ca+n+"px":f&&t?"one column"!==l&&(d.style.left=n+"px"):d.style.left=n+"px";40===oa&&"one row"===l&&(d.style.cssFloat="left");40===oa&&"one row"===l&&(d.style.marginTop="1px");"one column"===l&&(d.style.top=(f&&t?1:0)+na+n+"px");"one row"!==l&&" "===N&&(d.style.top="0px");"one column"===l&&" "===N&&(d.style.top="0px");c=y*ea;d.style.position=f&&t&&"one column"===l?"relative":"absolute";"two column"===
l&&!(Ga<=J)&&(d.style.width=c+"px");"one row"===l&&(d.style.width=(!0===s?y+n:2*y)+"px");s&&(i=0);b=0;a=0;for(var j=0;j<ea;j++){for(e=0;e<=i;e++)h[e]=document.createElement("ul"),h[e].className="providers",h[e].id="janrainProviders_"+e,1<i&&(h[e].style.cssFloat="left"),1<i&&(h[e].style.styleFloat="left"),h[e].style.listStyleType="none",h[e].style.marginTop="0px",h[e].style.marginLeft="0px",h[e].style.marginRight="0px",h[e].style.marginBottom="0px",h[e].style.padding="0px";c=document.createElement("div");
c.className="janrainPage";c.setAttribute("pageIndex",j);f&&t&&1===ea&&(c.style.width="110%");for(e=0;e<=i;e++)c.appendChild(h[e]);for(var o=g.length%2,Pb=s?Ga:J,p=0;p<Pb&&!(0==g.length);p++){if(2==i)var Hb=1==o?h[g.length%2?0:1]:h[g.length%2];if(1==i||0==i)Hb=h[0];e=g.shift();Hb.appendChild(e)}d.appendChild(c)}return d}function z(a){0==h()?("left"===a&&(Fa.style.width=n+"px",Ea.style.display="block",Ea.style.width="20px"),"top"===a&&(Ea.style.height=n+"px",Fa.style.display="block",Fa.style.height=
"20px")):("right"===a&&(Ea.style.width=n+"px",Fa.style.display="block",Fa.style.width="20px"),"bottom"===a&&(Fa.style.height=n+"px",Ea.style.display="block",Ea.style.height="20px"))}function E(){for(var a=[],b=0;b<Ga;b++){var c=F(sa[b]);a.push(c)}return a}function D(a,b){b.style.cursor="pointer";b.setAttribute("id","janrain-"+a);b.setAttribute("role","button");"one row"===l?b.style.background="transparent":("gradient"===Ma&&yb(b,"bottom, #eeeeee, #ffffff"),"gray"===Ma&&(b.style.backgroundColor="#eeeeee"),
"white"===Ma&&(b.style.backgroundColor="#ffffff"));R(b,"mouseover",function(){$a();"one row"===l?b.style.background="transparent":(b.style.backgroundColor="#E3E3E3",b.style.backgroundImage="")});R(b,"mouseout",function(){$a();"one row"===l?b.style.background="transparent":("gradient"===Ma&&yb(b,"bottom, #eeeeee, #ffffff"),"gray"===Ma&&(b.style.backgroundColor="#eeeeee"),"white"===Ma&&(b.style.backgroundColor="#ffffff"))});ab||H(b,a);return b}function F(a){var b=document.createElement("li");b.style.listStyle=
"none";0==w&&!1===s&&(b.style.cssFloat="left");0==w&&!1===s&&(b.style.styleFloat="left");b.style.textAlign="center";b.style.height=f&&t?C-2:C+"px";if("two column"==l){var c=s?3*n:Ga<=J?0:3*n;b.style.width=6===f||$a&&t?(y-c-4*n)/w+"px":(y-c-(2==w?10:0))/w+"px"}b.style.marginTop="0px";if("one column"==l){if(7==f||6==f)b.style.marginTop="-1px";f&&t?b.style.marginRight="0px":b.style.width=y-n/2+"px";b.style.marginLeft="0px"}else b.style.marginRight=n+"px";0==w&&(b.style.width=C+"px");b.style.marginBottom=
(7===f||6===f||f&&t?3:n)+"px";b.style.position="relative";0!=w&&(b.style.border="1px solid "+ta);0!=w&&G(b,ra);if("customopenid"===a){c=document.createElement("img");if(1==w||2==w)30==C&&(c.src=xa.smallLogo),50==C&&(c.src=xa.largeLogo);0==w&&(30==C&&(c.src=xa.smallIcon),50==C&&(c.src=xa.largeIcon))}else if(c=document.createElement("span"),"blank"!==a){if(1==w||2==w)30==C&&(c.className="janrain-provider100-"+a,c.style.width=100),50==C&&(c.className="janrain-provider150-"+a,c.style.width=150);0==w&&
(30==C&&(c.className="janrain-provider-icon-32 janrain-provider-icon-"+a,c.style.width=32),50==C&&(c.className="janrain-provider-icon-48 janrain-provider-icon-"+a,c.style.width=48))}f&&t&&(c.style.height=C-2+"px");if(6===f&&"one row"!==l){var d=document.createElement("div");d.style.height=c.style.height;d.style.width="90px";d.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enable=true,sizingMethod=crop,src='"+c.src+"')";c.style.filter="alpha(opacity=0)";d.appendChild(c);b.appendChild(d)}else b.appendChild(c);
return D(a,b)}function I(a,b){var d=document.createElement("div"),k=c.translate.SIGN_IN_AS||"Sign in as {name}",k=k.replace("{name}",b),k=document.createTextNode(k),e=document.createElement("div");e.style.cssFloat="right";e.style.styleFloat="right";e.style.fontFamily=V;e.style.position="relative";e.style.top="one row"===l?"2px":C/4-3+"px";e.appendChild(k);var g=document.createElement("div"),ea=7.5*k.length+30,h=i();g.style.fontSize="16px";g.style.height="100%";g.style.position="relative";if(0==w||
120>h)15<=k.length&&(g.style.fontSize="14px",ea=7*k.length+30),20<=k.length&&(g.style.fontSize="12px",ea=6*k.length+30),24<=k.length&&(g.style.fontSize="10px",ea=5*k.length+25),30<=k.length&&(k.textContent=k.textContent.substr(0,26)+"...",ea=162);g.style.width=ea+"px";if(0==w||116>h){if("customopenid"===a){var j=document.createElement("img");j.src=xa.smallIcon}else j=document.createElement("span"),j.className="janrain-provider-icon-20 janrain-provider-icon-"+a;j.style.width="20px";j.style.height=
"20px";j.style.cssFloat="left";j.style.styleFloat="left"}d.style.overflow="hidden";d.style.position="relative";d.style.height=("one row"!==l?C:25)+"px";d.style.marginBottom="one row"===l?"-4px":"4px";"one row"===l&&(d.style.top="-4px");d.style.left="0px";f&&t&&(d.style.marginRight="5px");f&&t&&(d.style.marginLeft="3px");d.style.border="1px solid "+ta;G(d,ra);"customopenid"===a&&(d.style.color=Ya[a].color);if(0==w||116>h)g.style.paddingTop="2px",g.appendChild(j);6===f||7===f||f&&t?g.style.left="10px":
g.style.margin="0 auto";g.appendChild(e);0==w||116>h?d.appendChild(g):(50===C&&parseInt(d.style.height),e.style.cssFloat="none",e.style.styleFloat="none",d.appendChild(e));return D(a,d)}function H(a,b){R(a,"click",function(){L(b)})}function L(a){var b=Ya[a],d={appUrl:c.appUrl,mobileDevice:ob,language:c.language,popup:Pa,tokenUrl:da||c.tokenUrl||window.location.href,facebookPermissions:ba,forceReauth:Ja,widgetType:"auth",tokenAction:wa,bpChannel:Ia,customOpenid:Qa,customOpenidOpxblob:c.customOpenidOpxblob};
b.name=a;new Ra(b,d,function(){aa||(Za=setTimeout(function(){Aa(b)},300))})}function K(a){var b=document.createElement("div");if("customopenid"===a){var c=document.createElement("img");c.src=xa.largeLogo}else c=document.createElement("span"),c.className="janrain-provider150-"+a;c.style.width="150px";c.style.height="50px";b.style.position="absolute";b.style.top="0px";b.style.left="0px";b.style.width=y+"px";b.style.zIndex="102";b.style.textAlign="center";b.style.padding=n+"px";b.style.backgroundColor=
"transparent"===Ka?"#ffffff":Ka;b.style.height=i()-(f&&t?0:2*n)+"px";G(b,v);"one row"!==l&&116<=i()&&b.appendChild(c);return b}function O(a){var b=document.createElement("a"),d=document.createTextNode(c.translate.USE_ANOTHER_ACCOUNT||"switch accounts");b.setAttribute("class","janrainSwitchAccountLink");b.setAttribute("href","");b.style.fontSize="12px";b.style.fontFamily=V;b.style.color=W;b.onclick=a;b.appendChild(d);return b}function P(){return"modal"===B?document.getElementById("janrainModal"):"embed"===
B?document.getElementById("janrainEngageEmbed"):!1}function Q(){var a=parseInt(q.style.width);return a=a+2*n+2}function T(){var a=P();null!==a&&"object"===typeof q&&q.parentNode===a&&a.removeChild(q)}function U(){var a="";"object"===typeof o&&(a=o.getState());return{type:B,width:Q(),fontFamily:V,fontSize:$,fontColor:W,backgroundColor:Ka,borderColor:ua,borderRadius:v,format:l,providersPerPage:J,providers:sa,buttonBackgroundStyle:Ma,buttonBorderColor:ta,buttonBorderRadius:ra,actionText:e(),showAttribution:ma,
modalState:a}}function X(a){l=p("string",["default","two column","one column","one row"],"two column",a);"default"===l&&(l="two column");"one row"==a&&(v=p("number",[0,5],5,v));fa()}function S(a){"two column"===l&&(y=p("number",[225,600],380,a));"one column"===l&&(y=p("number",[160,600],200,a));"one row"===l&&(C=30,a=Ga<=J?n*(parseInt(J)-1):n*(parseInt(J)+2),40===oa&&(a+=Ca-n),y=C*J+a);if(("two column"===l||"one column"===l)&&!s)y=y-2*n-2;f&&t&&(y=y+2*n+2);"one row"!==l&&(C=380<y?50:30)}function Z(b){"string"===
typeof b&&(Ba=!0,N=p("text",null,N,b)," "===N?v=p("number",[0,5],5,v,!0):na="two column"!==l?a().headerHeight-5:a().headerHeight)}function ga(a){Ma=p("string",["gray","white","gradient"],"gradient",a)}function ha(a){ta=p("color",null,"#CCCCCC",a)}function ja(a){Ka=p("color",null,"#ffffff",a)}function ka(a){"undefined"===typeof a&&(a=5);v=" "===N||!ma||"one row"===l?p("number",[0,5],5,a,!0):p("number",[0,10],10,a)}function la(a){ma=p("boolean",null,!0,a);i();v=a?p("number",[0,10],5,v,!0):p("number",
[0,5],5,v,!0)}function pa(a){ua=p("color",null,"#C0C0C0",a)}function fa(){"two column"===l&&($=18);if("one column"===l||"one row"===l)$=14}function va(a){W=p("color",null,"#333333",a)}function ya(a){if("object"==typeof a){w=g();for(var b=0,c=a.length;b<c;b++)if(!Ya[a[b]])return qa(4),m.log(a[b]+" is not a valid provider, using default providers instead"),this;sa=a;Ga=a.length;"object"===typeof o&&o.setHeight(i()-2*n).refresh()}}function qa(a){"two column"===l&&(J=p("number",[4,6,8],6,a));"one column"===
l&&(J=p("number",[1,6],6,a));"one row"===l&&(J=pb?Ga:p("number",[4,8],6,a),S(y))}function Aa(a){var b=document.createTextNode(c.translate&&c.translate.SIGNING_IN?c.translate.SIGNING_IN:"Signing in ..."),d=document.createElement("div");Na=K(a.name);d.appendChild(b);Na.appendChild(d);q&&q.appendChild(Na)}var Y=!1,y=380,Ba=!1,V="lucida grande, Helvetica, Verdana, sans-serif",$=18,W="#666666",Ka="#ffffff",ua="#C0C0C0",v=10,q,ca,l="two column",w,za,J=6,sa=["aol","google","yahoo","openid"],Ga=4,ta="#CCCCCC",
ra=5,Ma="gradient",C=30,na=a().headerHeight,oa=60,Ca=89,La=a().footerHeight,n=5,Ha=10,N="Sign in using your account with",Na,Wa,Ea,Fa,ma=!0,Oa=!1,Ta=!1,Ua,Va;janrain.events.onProviderLoginStart.addHandler(function(a){Da("login_tab",a.provider,1)});return{build:b,setFormat:function(b){b&&X(b);"two column"!==l&&(na=a().headerHeight-5);"two column"===l&&(J=a().twoColumn.providersPerPage,na=a().headerHeight);return this},setActionText:function(a){"string"===typeof a&&Z(a);return this},setFontSize:function(a){a&&
fa(a);return this},setFontFamily:function(a){a&&a&&(V=a);return this},setFontColor:function(a){a&&va(a);return this},setButtonBorderColor:function(a){a&&ha(a);return this},setButtonBorderRadius:function(a){if("string"==typeof a||"number"==typeof a)ra=p("number",[0,20],5,a);return this},setButtonBackgroundStyle:function(a){a&&ga(a);return this},setWidth:function(a){("string"==typeof a||"number"==typeof a)&&S(a);return this},refresh:function(){T();var a=P();b();var c=M("expected_tab");c&&!Xa?ia("expected_tab",
c):(null!==a&&"object"===typeof q&&a.appendChild(q),"object"===typeof o&&o.setHeight(parseInt(q.style.height)+2).refresh());janrain.events.onCustomizationChange.fire(U());return this},remove:function(){T();return this},setRowHeight:function(a){if(0!==g())return this;a||(a=60);oneRowHeaderHeight=p("number",[40,60,90],60,a);40===oneRowHeaderHeight&&(C=30,oa=40);60===oneRowHeaderHeight&&(C=30);90===oneRowHeaderHeight&&(C=50);return this},setHeight:function(a){"object"==typeof q&&(q.style.height=a+"px");
return this},setBackgroundColor:function(a){a&&ja(a);return this},setBorderColor:function(a){a&&pa(a);return this},setBorderRadius:function(a){("string"==typeof a||"number"==typeof a)&&ka(a);return this},setProviders:function(a){"object"==typeof a&&ya(a);return this},setProvidersPerPage:function(a){if("string"==typeof a||"number"==typeof a)qa(a),"object"===typeof o&&o.setHeight(i()).refresh("janrainModal");return this},setShowAttribution:function(a){"boolean"===typeof a&&la(a);return this},setPreviewMode:function(a){"boolean"===
typeof a&&(ab=a);return this},setProviderFlow:function(a,b){return H(a,b)},triggerFlow:function(a){return L(a)},setNoReturnExperience:function(a){"boolean"===typeof a&&(Oa=a);return this},setNoReturnExperienceSwitchAccountLink:function(a){"boolean"===typeof a&&(Ta=a);return this},setConfigureMode:function(a){"boolean"===typeof a&&(s=a,w=g());return this},embed:function(a){if((za=a)&&"object"==typeof q)q.style.position="relative";return this},getContentsDiv:function(){return q},getErrorPage:function(a,
b){var c=document.createTextNode(b.msg),d=document.createElement("div");d.appendChild(c);d.style.color=W;d.style.fontSize=$+"px";d.style.width="100%";var k=K(a);k.appendChild(d);k.appendChild(O(function(){q.removeChild(k);q.removeChild(Na);Ja=!0;return!1},a));q.appendChild(k);return q},getReturnExperience:function(a,b){if(ab||Oa||-1===sa.indexOf(a))return q;var c=I(a,b),d=K(a),k=function(){Ja=Xa=!0;q.removeChild(d);return!1};d.id="janrainAuthReturnExperience";d.appendChild(c);Ta||d.appendChild(O(k,
a));q.appendChild(d);return q},getWidth:function(){return Q()},getActualHeight:function(){return parseInt(q.style.height)+2},getHeight:function(){return i()-2*n},getState:function(){return U()},setState:function(b){if(j("customizable_auth_widget_styling")){var c=b.fontFamily;c&&(V=c);fa(b.fontSize);va(b.fontColor);ja(b.backgroundColor);pa(b.borderColor);"embed"===B&&b.format&&(b.format&&X(b.format),"two column"!==l&&(na=a().headerHeight-5),"two column"===l&&(J=a().twoColumn.providersPerPage,na=a().headerHeight));
if("string"==typeof b.providersPerPage||"number"==typeof b.providersPerPage)qa(b.providersPerPage),"object"===typeof o&&o.setHeight(i()).refresh("janrainModal");ga(b.buttonBackgroundStyle);ha(b.buttonBorderColor);ra=p("number",[0,20],5,b.buttonBorderRadius);Z(b.actionText);la(b.showAttribution);ka(b.borderRadius);"embed"===B&&("string"==typeof width||"number"==typeof width)&&S(b.width)}ya(b.providers)},showNotice:function(){Aa()},removeNotice:function(){Na&&Na.parentNode&&Na.parentNode.removeChild(Na)},
removeReturnExperience:function(){var a=document.getElementById("janrainAuthReturnExperience");a&&a.parentNode&&a.parentNode.removeChild(a)}}}function e(){if("object"===typeof i)if("object"===typeof L){var a=i.getState();a.width=L.width;L=a}else L=i.getState();"object"===typeof i&&i.remove();"object"===typeof o&&o.remove();u();B="modal";"object"===typeof i&&L&&j("customizable_auth_widget_styling")&&i.setState(L);"object"===typeof o&&ca&&j("customizable_auth_widget_styling")&&o.setState(ca);"object"===
typeof o&&o.show();"object"===typeof i&&i.refresh()}function d(){if("object"===typeof i){if("object"===typeof L){var a=i.getState();a.borderRadius=L.borderRadius;a.format=L.format;a.width=L.width;L=a}else L=i.getState();ca=L.modalState;delete ca.orientation}"object"===typeof i&&i.remove();"object"===typeof o&&o.remove();"object"===typeof o&&(o="");I();B="embed";"object"===typeof i&&L&&j("customizable_auth_widget_styling")&&i.setState(L);"object"===typeof i&&i.refresh()}function b(){var a,b;u();b=
document.getElementsByTagName("a");var d=RegExp("(\\s|^)"+c.linkClass+"(\\s|$)");for(a in b)d.test(b[a].className)&&(b[a].onclick=g)}function I(){var b=M("expected_tab");i=new a;i.setBackgroundColor(Ta).embed(!0).setPreviewMode(Ua).setShowAttribution(Va).setNoReturnExperience(bb).setNoReturnExperienceSwitchAccountLink(qb).setFormat(rb).setRowHeight(sb).setFontSize(cb).setFontFamily(db).setFontColor(eb).setActionText(fb).setProviders(tb).setProvidersPerPage(gb).setWidth(W).setBorderColor($).setBorderRadius(Ba).setButtonBorderColor(hb).setButtonBorderRadius(ib).setButtonBackgroundStyle(jb).build();
var c=document.getElementById("janrainEngageEmbed");null===c&&(c=document.getElementById("janrainModal"));ja||(b?(P("welcome_info_name",unescape(M("welcome_info_name"))),ia("expected_tab",b)):ga(c,i.getContentsDiv()))}function g(){"object"===typeof o&&o.show();return!1}function u(){var b=Ha(Oa,la),c=M("expected_tab");if("undefined"===typeof b||0>b)b=5;i=new a;i.setBackgroundColor(Ta).setPreviewMode(Ua).setShowAttribution(Va).setNoReturnExperience(bb).setNoReturnExperienceSwitchAccountLink(qb).setFontSize(cb).setFontFamily(db).setFontColor(eb).setActionText(fb).setProviders(tb).setProvidersPerPage(gb).setBorderRadius(b).setButtonBorderColor(hb).setButtonBorderRadius(ib).setButtonBackgroundStyle(jb).build();
if("object"!==typeof o){o=new Db;o.ready=!1;var d=o.addContent;o.addContent=function(a){o.ready=!0;d(a);janrain.events.onModalWidgetReady.fire()}}o.setHeight(i.getActualHeight()).setWidth(i.getWidth()).setPreviewMode(Ua).setBorderColor(qa).setBorder(la).setBorderOpacity(Aa).setBorderRadius(Oa);ja||(c?(P("welcome_info_name",unescape(M("welcome_info_name"))),ia("expected_tab",c)):o.addContent(i.getContentsDiv()));o.onOrientationChange.addHandler(function(a){"portrait"===a.orientation&&i.setFormat(a.format).setWidth(200).refresh();
"landscape"===a.orientation&&i.setHeight(a.height).setWidth(a.width).setFormat(a.format).refresh();o.setHeight(i.getActualHeight());o.setWidth(i.getWidth())});o.onShow.addHandler(function(){"object"==typeof i&&o.setWidth(i.getWidth())});o.onBorderWidthChange.addHandler(function(a){"object"===typeof o&&"object"===typeof i&&(i.setBorderRadius(a.radius).refresh(),a=i.getState(),a.borderRadius<a.modalState.borderRadius-a.modalState.borderWidth&&o.setBorderRadius(a.borderRadius+a.modalState.borderWidth))});
o.onBorderRadiusChange.addHandler(function(a){"object"===typeof i&&(i.setBorderRadius(a.radius).refresh(),a=i.getState(),a.borderRadius<a.modalState.borderRadius-a.modalState.borderWidth&&o.setBorderRadius(a.borderRadius+a.modalState.borderWidth))})}function x(a,b){if(!j("customizable_auth_widget_styling"))return!1;if("object"===typeof i)return b(a),!0}function O(a){return x(a,function(a){i.setBackgroundColor(a).refresh()})}function A(a){return x(a,function(a){i.setBorderRadius(a).refresh()})}function E(a){return x(a,
function(a){i.setBorderColor(a).refresh()})}function F(a){return"modal"===B?!1:x(a,function(a){i.setWidth(a).refresh()})}function Z(a){return x(a,function(a){i.setActionText(a).refresh()})}function r(a){return x(a,function(a){i.setButtonBorderColor(a).refresh()})}function Q(a){return x(a,function(a){i.setButtonBorderRadius(a).refresh()})}function ha(a){return x(a,function(a){i.setButtonBackgroundStyle(a).refresh()})}function pa(a){return"modal"==B?!1:x(a,function(a){i.setFormat(a).refresh()})}function h(a){return x(a,
function(a){i.setProvidersPerPage(a).refresh()})}function fa(a){return x(a,function(a){i.setFontFamily(a).refresh()})}function va(a){return x(a,function(a){i.setFontSize(a).refresh()})}function z(a){return x(a,function(a){i.setFontColor(a).refresh()})}function M(a){var b;if("single cookie"===ka){b=U().getCookie("janrain_engage_login_data");if(!b)return;b=K.parse(b);return!b[a]?void 0:a=b[a]}if("default"===ka)return a=U().getCookie(a),!a?void 0:a}function Da(a,b,c){var d;if(!a||!b)return!1;c||(c=1);
if("single cookie"===ka)return(oldCookieJSON=U().getCookie("janrain_engage_login_data"))||(oldCookieJSON="{}"),c=K.parse(oldCookieJSON),c[a]=b,d=new U,d.setName("janrain_engage_login_data").setValue(K.stringify(c)).setExpiration(1826).create(),!0;return"default"===ka?(d=new U,d.setName(a).setValue(b).setExpiration(c).create(),!0):!1}function ya(a,b){if(bb)return!1;if("expected_tab"===a&&!b){var c=M("login_tab");c&&ya("expected_tab",c);return!1}if(!b||"undefined"===b||"expected_tab"!==a&&"expected_user_input"!==
a&&"welcome_info_name"!==a)return!1;b="welcome_info_name"===a?escape(b):b;Da(a,b,1826)}function H(a,b){var c={};a||(a=ub);b||(b=ub.appUrl);if(f&&3>Ca)return c.widget_type=a.widget_type,c.provider=a.provider,c.time=(new Date).getTime(),c=nb(c),sa(b+"/signin/get_login_info"+c),Ca++,!0;"object"===typeof janrain.events.onProviderLoginCancel&&janrain.events.onProviderLoginCancel.fire(a);"undefined"!==typeof Za&&clearTimeout(Za);return!1}function Ra(a,b,c){var d=b.appUrl+"/"+a.flow+"/start",e=window.location.href;
b.mobileDevice&&(e="mobile");var f=b.language||"en",g=b.popup?"xdr":"xdrsw",i=b.tokenUrl||window.location.href,h={};ub={appUrl:b.appUrl,provider:a.name,widget_type:b.widgetType};h.language_preference=f;h.token_url=i;h.display="popup";h.widget=!0;"object"===typeof b.facebookPermissions&&(h.ext_perm=b.facebookPermissions.toString());h.openid_identifier=a.identifier;h.origin_url=e;h.provider_name=a.name;h.force_reauth=b.forceReauth;h.xdReceiver=b.appUrl+"/"+g;h.callback="none";h.widget_type=b.widgetType;
h.token_action="url";if("event"===b.tokenAction||"hybrid"===b.tokenAction)h.token_action="event";b.mobileDevice&&"hybrid"===b.tokenAction&&(h.token_action="url");b.bpChannel&&(h.bpChannel=b.bpChannel);b.customOpenid&&"string"===typeof b.customOpenidOpxblob&&(h.opx_blob=b.customOpenidOpxblob);d+=nb(h);(function(){janrain.events.onProviderLoginStart.fire({provider:a.name,width:a.width,height:a.height});var e;b.mobileDevice&&"event"!==b.tokenAction||!b.popup?sa(b.appUrl+"/signin/set_login_tab?login_tab="+
a.name+"&origin_url="+window.location.href,function(){window.top.location.href=d}):(e=new Mb(d),e.setWidth(a.width).setHeight(a.height).setCallback(function(){var d={},e="";d.widget_type=b.widgetType;d.provider=a.name||"";d.time=(new Date).getTime();e=nb(d);"function"===typeof c&&c();sa(b.appUrl+"/signin/get_login_info"+e);janrain.events.onProviderLoginComplete.fire({provider:a.name})}).show())})()}function P(a,b){if(!b||"undefined"===b||"welcome_info_name"!==a)return!1;b&&(S=b)}function ia(a,b){function c(){janrain.events.onReturnExperienceFound.fire({returnProvider:b,
welcomeName:S})}var d=function(a){var c=function(){600>a&&setTimeout(function(){d(++a)},50)};if("object"!==typeof i)return c(),!1;"modal"===B?o.addContent(i.getReturnExperience(b,S)):"embed"===B&&ga(document.getElementById("janrainEngageEmbed"),i.getReturnExperience(b,S));"modal"===B&&janrain.events.onModalWidgetReady.fire()};if("expected_tab"!==a||!b)return!1;"object"===typeof i&&i.removeReturnExperience();ra?c():janrain.events.onAuthWidgetLoad.addHandler(c);d(0)}function ga(a,b){janrain.settings.capture&&
(a?a.appendChild(b):(a=document.createElement("div"),a.id="janrainEngageEmbed",a.style.display="none",document.body.appendChild(a)));a?a.appendChild(b):m.log('Missing container div, please place this div where you want the embedded widget to be displayed on your page - <div id="janrainEngageEmbed"></div>.').show();return a}function V(a,b){da=da||T;tokenUrl=b?da:T;var c="";if(!mb(tokenUrl).query)var c=c+"?",d=!0;for(var e in a)d?(c+=e+"="+a[e],d=!1):c+="&"+e+"="+a[e];da=tokenUrl+c}function ua(){c=
janrain.settings;if("en"!==janrain.settings.language&&"undefined"===typeof janrain.settings.translate)return setTimeout(ua,5),!1;Bb(wb()+"providers.css");f&&9>=f&&Bb(wb()+"providers-ie.css");if(c.stop)return!0;Ob&&sa(c.appUrl+"/signin/establish_session");wa=c.tokenAction?c.tokenAction:wa;if(!c.tokenUrl&&"event"===wa)T=window.location.href;else if(c.tokenUrl)T=c.tokenUrl;else return m.log("Missing tokenUrl.  tokenUrl is required."),m.show(),!1;B=p("string",["modal","embed"],"embed",c.type?c.type:B);
ja=c.multi?c.multi:ob?!0:ja;aa=c.custom?c.custom:aa;Ja=c.forceReauth?c.forceReauth:Ja;Ia=c.bpChannel?c.bpChannel:Ia;ba=c.facebookPermissions?c.facebookPermissions:ba;ka=c.storageType?p("string",["default","single cookie"],"default",c.storageType):ka;Pa="boolean"===typeof c.popup?c.popup:Pa;ob&&"event"!==wa&&(Pa=!1);X=c.returnExperienceTimeout?c.returnExperienceTimeout:X;ja&&(setTimeout(function(){var a=M("expected_tab");a?(P("welcome_info_name",unescape(M("welcome_info_name"))),ia("expected_tab",
a)):"modal"===B?o.addContent(i.getContentsDiv()):"embed"===B&&(a=document.getElementById("janrainEngageEmbed"),ga(a,i.getContentsDiv()))},X),sa(c.appUrl+"/signin/get_cookies"));if(c.customOpenid&&j("customizable_auth_widget_styling")){Qa=!0;if(!c.customOpenidFlow)return m.log("Missing customOpenidFlow. customOpenidFlow is required when adding a custom openid provider."),m.show(),!1;if(!c.customOpenidIdentifier)return m.log("Missing customOpenidIdentifier. customOpenidIdentifier is required when adding a custom openid provider."),
m.show(),!1;Ya.customopenid={flow:c.customOpenidFlow,identifier:c.customOpenidIdentifier}}if(aa)return!0;wa=c.tokenAction?c.tokenAction:wa;la=j("customizable_auth_widget_styling")?c.modalBorderWidth:la;qa=j("customizable_auth_widget_styling")?c.modalBorderColor:qa;Oa=j("customizable_auth_widget_styling")?c.modalBorderRadius:Oa;Aa=j("customizable_auth_widget_styling")?c.modalBorderOpacity:Aa;Ta=j("customizable_auth_widget_styling")?c.backgroundColor:Ta;Ba=j("customizable_auth_widget_styling")?c.borderRadius:
Ba;$=j("customizable_auth_widget_styling")?c.borderColor:$;rb=j("customizable_auth_widget_styling")?c.format:rb;eb=j("customizable_auth_widget_styling")?c.fontColor:eb;cb=j("customizable_auth_widget_styling")?c.fontSize:cb;db=j("customizable_auth_widget_styling")?c.fontFamily:db;W=j("customizable_auth_widget_styling")?c.width:W;sb=j("customizable_auth_widget_styling")?c.rowHeight:sb;gb=j("customizable_auth_widget_styling")?c.providersPerPage:gb;pb=j("customizable_auth_widget_styling")?c.providersNotPaged:
pb;fb=j("customizable_auth_widget_styling")?c.actionText:fb;hb=j("customizable_auth_widget_styling")?c.buttonBorderColor:hb;ib=j("customizable_auth_widget_styling")?c.buttonBorderRadius:ib;jb=j("customizable_auth_widget_styling")?c.buttonBackgroundStyle:jb;Va=j("customizable_auth_widget_hide_attribution")?c.showAttribution:Va;Ua=c.previewMode;bb=c.noReturnExperience;qb=c.noReturnExperienceSwitchAccountLink;tb=c.providers;"undefined"===typeof janrain.settings.translate&&(janrain.settings.translate=
c.translate={});if(c.customOpenid&&j("customizable_auth_widget_styling")){if(!c.customOpenidSmallLogo)return m.log("Missing customOpenidSmallLogo.  customOpenidSmallLogo is required and should be the full path to an image that has a width of 90px and height of 30px."),m.show(),!1;if(!c.customOpenidSmallIcon)return m.log("Missing customOpenidSmallIcon.  customOpenidSmallIcon is required and should be the full path to an image that is 30px x 30px."),m.show(),!1;if(!c.customOpenidLargeLogo)return m.log("Missing customOpenidLargeLogo.  customOpenidLargeLogo is required and should be the full path to an image that has a width of 150px and height of 50px."),
m.show(),!1;if(!c.customOpenidLargeIcon)return m.log("Missing customOpenidLargeIcon.  customOpenidLargeIcon is required and should be the full path to an image that is 50px x 50px."),m.show(),!1;xa={smallLogo:c.customOpenidSmallLogo,smallIcon:c.customOpenidSmallIcon,largeLogo:c.customOpenidLargeLogo,largeIcon:c.customOpenidLargeIcon}}c.previewMode?("modal"===B&&(janrain.ready?e():R(window,"load",e)),"embed"===B&&(janrain.ready?d():R(window,"load",d))):("modal"===B&&(janrain.ready?b():R(window,"load",
b)),"embed"===B&&(janrain.ready?I():R(window,"load",I)))}var ba,Ia,Qa=!1,Ja=!1,wa="url",T,da,B="embed",S="unknown",ja=!1,X=300,Ja=!1,Pa=!0,aa=!1,ka="default",xa,ca,o,la,qa,Oa,Aa,i,L,Ta,Ba,$,W,sb,rb,tb=[],pb=!1,gb,fb,cb,db,eb,hb,ib,jb,Ua,bb,qb,Va,Xa=!1,ra=!1;janrain.events.onAuthWidgetLoad||(janrain.events.onAuthWidgetLoad=D());janrain.events.onModalWidgetReady||(janrain.events.onModalWidgetReady=D());janrain.events.onReturnExperienceFound||(janrain.events.onReturnExperienceFound=D());janrain.events.onAuthWidgetLoad.addHandler(function(){ra=
!0});janrain.events.onAuthWidgetLoad.addHandler(function(){"function"===typeof janrainWidgetOnload&&(aa?janrainWidgetOnload():i?janrainWidgetOnload(i.getState()):janrainWidgetOnload())});for(var Za,Ca=0,ub,vb="onProviderLoginStart,onProviderLoginError,onProviderLoginToken,onProviderLoginCancel,onProviderLoginSuccess,onProviderLoginComplete,onProviderLogoutStart,onProviderLogoutComplete".split(","),kb=0;kb<vb.length;kb++)"undefined"===typeof janrain.events[vb[kb]]&&(janrain.events[vb[kb]]=new ta);
janrain.events.onProviderLoginError.addHandler(function(a){if(aa)return!0;var b=M("login_tab");if("modal"===B){var c=document.getElementById("janrainModal");c&&c.appendChild(i.getErrorPage(b,a.err))}"embed"===B&&(c=document.getElementById("janrainEngageEmbed"))&&ga(c,i.getErrorPage(b,a.err))});ua();return{appendTokenParams:function(a,b){V(a,b)},appendTokenParamsCumulative:function(a){V(a,!0)},setBackplaneChannel:function(a){Ia=a},setLoginCookie:function(a,b){ya(a,b)},loginHandler:function(a){var b=
wa;a?("ok"===a.stat&&("event"===b||"hybrid"===b?sa(a.redirectUrl):(b=document.createElement("form"),b.action=a.redirectUrl,b.method="POST",janrain.settings.targetTop&&(b.target="_top"),document.body.appendChild(b),b.submit())),"fail"===a.stat&&(janrain.events.onProviderLoginError.fire(a),"undefined"!==typeof Za&&clearTimeout(Za))):H()},cancelLogin:function(a){H(a,c.appUrl);aa||i.removeNotice()},removeNotice:function(){i.removeNotice()},setWelcomeInfoName:function(a,b){P(a,b)},setReturnExperience:function(a,
b){ia(a,b)},setNoReturnExperience:function(a){"boolean"===typeof a&&i?(i.setNoReturnExperience(a).refresh(),a=!0):a=!1;return a},setNoReturnExperienceSwitchAccountLink:function(a){"boolean"===typeof a&&i?(i.setNoReturnExperienceSwitchAccountLink(a).refresh(),a=!0):a=!1;return a},setPreviewMode:function(a){"boolean"===typeof a&&i?(i.setPreviewMode(a).refresh(),a=!0):a=!1;return a},setConfigureMode:function(a){"boolean"===typeof a&&i?(i.setConfigureMode(a).refresh(),a=!0):a=!1;return a},setCustom:function(a){aa=
a},getState:function(){return"object"===typeof i?i.getState():!1},setProviderFlow:function(b,c){var d;d=!j("customizable_auth_widget_styling")||!aa?!1:a().setProviderFlow(b,c);return d},triggerFlow:function(b){b=!j("customizable_auth_widget_styling")||!aa?!1:a().triggerFlow(b);return b},debugDump:function(){if("undefined"!==typeof console){console.log("-------------START---------------");null!==document.doctype?(console.log("DOCTYPE Name: "+document.doctype.name),console.log("DOCTYPE NodeType: "+
document.doctype.nodeType)):console.log("DOCTYPE name: not available (probably quirks mode)");console.log("User Agent: "+navigator.userAgent);console.log("App Version: "+navigator.appVersion);console.log("Platform: "+navigator.platform);console.log("OS CPU: "+navigator.oscpu);console.log("Language: "+navigator.language);console.log("Release: ");console.log("Web Address: "+location.href);console.log("Cookies Enabled: "+navigator.cookieEnabled);console.log("COOKIES::: "+document.cookie);console.log("AUTH SETTINGS:::");
for(var a in janrain.settings)if(console.log(" ---- "+a+": "+janrain.settings[a]),"object"===typeof janrain.settings[a])for(var b in janrain.settings[a])"function"!==typeof janrain.settings[a][b]&&console.log(" --- --- "+b+": "+janrain.settings[a][b]);console.log("-------------END---------------")}},version:"not sure",widget:{init:function(){d()},setBackgroundColor:function(a){return O(a)},setBorderColor:function(a){return E(a)},setBorderRadius:function(a){return A(a)},setWidth:function(a){return F(a)},
setActionText:function(a){return Z(a)},setFontFamily:function(a){return fa(a)},setFontSize:function(a){return va(a)},setFontColor:function(a){return z(a)},setFormat:function(a){return pa(a)},setButtonBorderColor:function(a){return r(a)},setButtonBorderRadius:function(a){return Q(a)},setButtonBackgroundStyle:function(a){return ha(a)},setProviders:function(a){var b;"object"===typeof i&&(s?i.setProviders(a):i.setProviders(a).refresh(),b=!0);return b},setProvidersPerPage:function(a){return h(a)},setShowAttribution:function(a){var b;
j("customizable_auth_widget_hide_attribution")?"object"===typeof i&&i.setShowAttribution(a).refresh():b=!1;return b},refresh:function(){return i.refresh()},getWidth:function(){return i.getWidth()}},modal:{init:function(){e()},close:function(){"object"==typeof o&&o.close()},create:function(){return new Db},setBorder:function(a){j("customizable_auth_widget_styling")?("object"===typeof o&&(o.setBorder(a),o.refresh()),a=!0):a=!1;return a},setBorderColor:function(a){j("customizable_auth_widget_styling")?
("object"===typeof o&&(o.setBorderColor(a),o.refresh()),a=!0):a=!1;return a},setBorderOpacity:function(a){j("customizable_auth_widget_styling")?("object"===typeof o&&(o.setBorderOpacity(a),o.refresh()),a=!0):a=!1;return a},setBorderRadius:function(a){j("customizable_auth_widget_styling")?("object"==typeof o&&(o.setBorderRadius(a),o.refresh()),a=!0):a=!1;return a}}}};var I=new function(){return{status:"not loaded"}},Qa=new function(){return{status:"not loaded"}},la=new function(){return{status:"not loaded"}},
Qb=new function(){return{status:"not loaded"}};return{engage:{signin:janrain&&janrain.engage&&janrain.engage.signin?janrain.engage.signin:Ra,share:janrain&&janrain.engage&&janrain.engage.share?janrain.engage.share:I,publish:janrain&&janrain.engage&&janrain.engage.publish?janrain.engage.publish:Qa,simpleshare:janrain&&janrain.engage&&janrain.engage.simpleshare?janrain.engage.simpleshare:la},capture:{ui:Qb}}}();janrain.engage=janrain.apps.engage;janrain.capture=janrain.apps.capture;